import type { LessonPlanItem } from "@/types/schemas";

/**
 * Szkielet 50 lekcji, 9 blokow tematycznych.
 * Generator lekcji uzywa tego planu jako brief dla agenta Opus.
 */
export const LESSON_PLAN: LessonPlanItem[] = [
  // ============ BLOK A: Liczby i dzialania (1-8) ============
  {
    number: 1,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Dodawanie i odejmowanie do 1000",
    topic: "arytmetyka",
    subtopic: "dodawanie/odejmowanie pisemne i w pamieci",
    goals: ["rozgrzewka rachunkowa", "sprytne sposoby obliczania", "kontrola wyniku przez oszacowanie"],
  },
  {
    number: 2,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Mnozenie - tabliczka i zastosowania",
    topic: "arytmetyka",
    subtopic: "mnozenie liczby dwucyfrowej przez jednocyfrowa",
    goals: ["pewnosc tabliczki mnozenia", "mnozenie przez 10/100", "rozkladanie liczb"],
  },
  {
    number: 3,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Dzielenie i reszty z dzielenia",
    topic: "arytmetyka",
    subtopic: "dzielenie z reszta, podzielnosc",
    goals: ["co to reszta", "podzielnosc przez 2, 3, 5, 10", "ile pelnych grup"],
  },
  {
    number: 4,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Kolejnosc wykonywania dzialan",
    topic: "arytmetyka",
    subtopic: "nawiasy, mnozenie przed dodawaniem",
    goals: ["zasady kolejnosci", "rola nawiasow", "wstawianie znakow w lamiglowkach"],
  },
  {
    number: 5,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Liczby parzyste i nieparzyste",
    topic: "arytmetyka",
    subtopic: "wlasnosci parzystosci, suma parzystych i nieparzystych",
    goals: ["co daje parzysta + parzysta", "parzysta razy cokolwiek", "wnioski z parzystosci"],
  },
  {
    number: 6,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Sprytne liczenie: laczenie i grupowanie",
    topic: "arytmetyka",
    subtopic: "lacznosc, przemiennosc, rozdzielnosc",
    goals: ["zamiana kolejnosci dla wygody", "rozkladanie na pelne dziesiatki", "ulamek w kontekscie liczenia"],
  },
  {
    number: 7,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Zaokraglanie i szacowanie",
    topic: "arytmetyka",
    subtopic: "zaokraglanie do 10, 100, szacowanie wyniku",
    goals: ["po co szacujemy", "zaokraglanie", "szybka eliminacja zlej odpowiedzi"],
  },
  {
    number: 8,
    blockCode: "A",
    block: "Liczby i dzialania",
    title: "Lamiglowki rachunkowe i kryptarytmy",
    topic: "lamiglowki",
    subtopic: "wstaw cyfre, kryptarytm, brakujace znaki",
    goals: ["analiza cyfra po cyfrze", "przenoszenie z kolumny", "sprawdzanie hipotezy"],
  },

  // ============ BLOK B: Wzory, ciagi, regularnosci (9-13) ============
  {
    number: 9,
    blockCode: "B",
    block: "Wzory, ciagi, regularnosci",
    title: "Ciagi liczbowe - co dalej?",
    topic: "wzory_i_ciagi",
    subtopic: "ciag arytmetyczny prosty, roznice",
    goals: ["znalezienie roznicy", "kontynuacja ciagu", "uogolnienie wzoru"],
  },
  {
    number: 10,
    blockCode: "B",
    block: "Wzory, ciagi, regularnosci",
    title: "Wzory w obrazkach",
    topic: "wzory_i_ciagi",
    subtopic: "ciagi figuralne, rosnace ulozenia",
    goals: ["liczenie elementow", "tlumaczenie obrazka na liczby", "znalezienie wzoru przyrostu"],
  },
  {
    number: 11,
    blockCode: "B",
    block: "Wzory, ciagi, regularnosci",
    title: "Magiczne kwadraty",
    topic: "wzory_i_ciagi",
    subtopic: "kwadrat 3x3 z rownymi sumami",
    goals: ["zasada rownej sumy", "wnioskowanie z czesciowych danych", "sprawdzanie spojnosci"],
  },
  {
    number: 12,
    blockCode: "B",
    block: "Wzory, ciagi, regularnosci",
    title: "Rozkladanie na sume lub iloczyn",
    topic: "wzory_i_ciagi",
    subtopic: "rozklad liczby na skladniki, czynniki",
    goals: ["systematyczne przegladanie", "na ile sposobow", "rola ograniczen"],
  },
  {
    number: 13,
    blockCode: "B",
    block: "Wzory, ciagi, regularnosci",
    title: "Znajdz regule i przewidz nastepny krok",
    topic: "wzory_i_ciagi",
    subtopic: "regularnosci w ciagach mieszanych",
    goals: ["obserwacja kilku przykladow", "test hipotezy", "podsumowanie reguly"],
  },

  // ============ BLOK C: Geometria plaska (14-21) ============
  {
    number: 14,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Punkty, odcinki, proste, polproste",
    topic: "geometria_plaska",
    subtopic: "podstawowe pojecia geometryczne",
    goals: ["nazewnictwo elementow", "liczenie punktow przeciec", "odcinki w figurze"],
  },
  {
    number: 15,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Katy i ich rodzaje",
    topic: "geometria_plaska",
    subtopic: "katy ostre, proste, rozwarte, polpelne",
    goals: ["rozpoznawanie typu kata", "porownywanie katow", "katy w ulozeniach"],
  },
  {
    number: 16,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Trojkaty i ich rodzaje",
    topic: "geometria_plaska",
    subtopic: "rownoboczne, rownoramienne, prostokatne",
    goals: ["klasyfikacja trojkatow", "liczenie trojkatow w figurze", "zlozone figury"],
  },
  {
    number: 17,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Czworokaty: kwadrat, prostokat, trapez",
    topic: "geometria_plaska",
    subtopic: "wlasnosci czworokatow",
    goals: ["rozpoznawanie", "dlugosci bokow", "skladanie figur"],
  },
  {
    number: 18,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Obwod figur",
    topic: "geometria_plaska",
    subtopic: "suma dlugosci bokow, figury zlozone",
    goals: ["definicja obwodu", "obwod figury zlozonej z prostokatow", "porownywanie obwodow"],
  },
  {
    number: 19,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Pole figur - liczenie kratek",
    topic: "geometria_plaska",
    subtopic: "pole prostokata, sumowanie czesci",
    goals: ["liczenie cale i polowki kratek", "rozkladanie figury", "pole kwadratu"],
  },
  {
    number: 20,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Symetria osiowa",
    topic: "geometria_plaska",
    subtopic: "os symetrii, odbicia",
    goals: ["znajdowanie osi", "rysowanie odbicia", "ile osi symetrii"],
  },
  {
    number: 21,
    blockCode: "C",
    block: "Geometria plaska",
    title: "Tangram i ukladanie figur",
    topic: "geometria_plaska",
    subtopic: "rozcinanie i ukladanie figur z czesci",
    goals: ["dopasowanie ksztaltow", "rownosc pol przy roznych ukladach", "obracanie i odbicia"],
  },

  // ============ BLOK D: Geometria przestrzenna (22-26) ============
  {
    number: 22,
    blockCode: "D",
    block: "Geometria przestrzenna",
    title: "Bryly: szescian i prostopadloscian",
    topic: "geometria_przestrzenna",
    subtopic: "podstawowe bryly, wierzcholki, krawedzie, sciany",
    goals: ["liczenie elementow szescianu", "rozroznianie bryl", "krawedzie wspolne"],
  },
  {
    number: 23,
    blockCode: "D",
    block: "Geometria przestrzenna",
    title: "Widoki bryly z roznych stron",
    topic: "geometria_przestrzenna",
    subtopic: "widok z przodu, z gory, z boku",
    goals: ["tlumaczenie 3D na 2D", "dopasowanie widokow", "rekonstrukcja bryly"],
  },
  {
    number: 24,
    blockCode: "D",
    block: "Geometria przestrzenna",
    title: "Liczenie kostek w budowli",
    topic: "geometria_przestrzenna",
    subtopic: "klocki niewidoczne, suma kostek",
    goals: ["liczenie warstwami", "kostki ukryte w srodku", "porownanie budowli"],
  },
  {
    number: 25,
    blockCode: "D",
    block: "Geometria przestrzenna",
    title: "Siatki szescianu",
    topic: "geometria_przestrzenna",
    subtopic: "rozwiniecia, przeciwlegle sciany",
    goals: ["rozpoznanie poprawnej siatki", "przeciwlegle sciany", "zlozenie w glowie"],
  },
  {
    number: 26,
    blockCode: "D",
    block: "Geometria przestrzenna",
    title: "Drogi i sciezki po bryle",
    topic: "geometria_przestrzenna",
    subtopic: "najkrotsza droga po krawedziach",
    goals: ["liczenie krokow", "porownanie tras", "wybor najkrotszej"],
  },

  // ============ BLOK E: Pomiary i jednostki (27-32) ============
  {
    number: 27,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Dlugosc: mm, cm, dm, m, km",
    topic: "pomiary_jednostki",
    subtopic: "zamiana jednostek dlugosci",
    goals: ["pamiec relacji 10/100/1000", "porownywanie dlugosci", "obliczenia mieszane"],
  },
  {
    number: 28,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Masa: g, dag, kg, t",
    topic: "pomiary_jednostki",
    subtopic: "zamiana jednostek masy, wagi",
    goals: ["relacje miedzy jednostkami", "zadania z wagami", "porownywanie mas"],
  },
  {
    number: 29,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Pojemnosc: ml, l",
    topic: "pomiary_jednostki",
    subtopic: "objetosc, przelewanie cieczy",
    goals: ["szacowanie objetosci", "zadania z naczyniami", "porcje"],
  },
  {
    number: 30,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Czas: minuty, godziny, doba",
    topic: "pomiary_jednostki",
    subtopic: "zamiana jednostek czasu",
    goals: ["minuty do godzin", "ile sekund w...", "dlugosc trwania"],
  },
  {
    number: 31,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Pieniadze, reszta, zakupy",
    topic: "pieniadze",
    subtopic: "zlotowki i grosze, reszta",
    goals: ["liczenie zlotowek i groszy", "wydawanie reszty", "ile mozna kupic"],
  },
  {
    number: 32,
    blockCode: "E",
    block: "Pomiary i jednostki",
    title: "Mieszane zadania z jednostkami",
    topic: "pomiary_jednostki",
    subtopic: "porownanie wielkosci roznych jednostek",
    goals: ["sprowadzanie do tej samej jednostki", "wybor najwiekszej/najmniejszej", "praktyczne zastosowanie"],
  },

  // ============ BLOK F: Czas i kalendarz (33-35) ============
  {
    number: 33,
    blockCode: "F",
    block: "Czas i kalendarz",
    title: "Zegar - godziny i minuty",
    topic: "czas_kalendarz",
    subtopic: "odczyt zegara, czas miedzy godzinami",
    goals: ["odczyt analogowy i cyfrowy", "ile czasu uplynelo", "kat miedzy wskazowkami"],
  },
  {
    number: 34,
    blockCode: "F",
    block: "Czas i kalendarz",
    title: "Dni tygodnia - co bedzie za N dni",
    topic: "czas_kalendarz",
    subtopic: "modulo 7 w praktyce",
    goals: ["liczenie po dniach tygodnia", "tydzien temu / za tydzien", "dlugie odstepy"],
  },
  {
    number: 35,
    blockCode: "F",
    block: "Czas i kalendarz",
    title: "Daty, miesiace, odstepy",
    topic: "czas_kalendarz",
    subtopic: "liczba dni miedzy datami, rok przestepny",
    goals: ["dlugosci miesiecy", "liczenie dni miedzy datami", "rok przestepny"],
  },

  // ============ BLOK G: Logika (36-41) ============
  {
    number: 36,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Prawda czy falsz",
    topic: "logika",
    subtopic: "zdania logiczne, ocena prawdziwosci",
    goals: ["odroznienie zdania od pytania", "sprawdzanie warunkow", "wyjatki"],
  },
  {
    number: 37,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Kto powiedzial prawde - zagadki",
    topic: "logika",
    subtopic: "klamcy i prawdomowni, rozumowanie",
    goals: ["zalozenia i wnioski", "sprzecznosc jako narzedzie", "systematyczne sprawdzanie"],
  },
  {
    number: 38,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Tabelki logiczne i przyporzadkowania",
    topic: "logika",
    subtopic: "kto ma co, kto gdzie mieszka",
    goals: ["wypelnianie tabeli", "wykluczanie", "wnioskowanie laczne"],
  },
  {
    number: 39,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Eliminacja mozliwosci",
    topic: "logika",
    subtopic: "metoda 'co zostaje gdy wykluczamy'",
    goals: ["wykluczanie krok po kroku", "ostatnia mozliwosc", "kontrola dwoch warunkow"],
  },
  {
    number: 40,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Wagi i porownania",
    topic: "logika",
    subtopic: "ktora cieższa, balansowanie",
    goals: ["porownywanie parami", "wagi szalkowe", "wnioski z rownowagi"],
  },
  {
    number: 41,
    blockCode: "G",
    block: "Logika i myslenie",
    title: "Przelewanie, przesypywanie, podzialy",
    topic: "logika",
    subtopic: "klasyczne zagadki z naczyniami",
    goals: ["mysleienie sekwencyjne", "stany posrednie", "minimalna liczba krokow"],
  },

  // ============ BLOK H: Kombinatoryka (42-45) ============
  {
    number: 42,
    blockCode: "H",
    block: "Kombinatoryka i liczenie",
    title: "Na ile sposobow - proste przypadki",
    topic: "kombinatoryka",
    subtopic: "wybor z kilku elementow",
    goals: ["wymienianie po kolei", "iloczyn mozliwosci", "co znaczy 'na ile sposobow'"],
  },
  {
    number: 43,
    blockCode: "H",
    block: "Kombinatoryka i liczenie",
    title: "Drzewo mozliwosci",
    topic: "kombinatoryka",
    subtopic: "diagram drzewa, galeziownie",
    goals: ["rysowanie drzewa", "zliczanie galezi", "porzadek wybierania"],
  },
  {
    number: 44,
    blockCode: "H",
    block: "Kombinatoryka i liczenie",
    title: "Liczenie tras na siatce",
    topic: "kombinatoryka",
    subtopic: "drogi w kratownicy, najkrotsze trasy",
    goals: ["co to znaczy najkrotsza", "liczenie pol siatki", "systematycznosc"],
  },
  {
    number: 45,
    blockCode: "H",
    block: "Kombinatoryka i liczenie",
    title: "Ustawianie i kolory",
    topic: "kombinatoryka",
    subtopic: "permutacje, malowanie figur",
    goals: ["na ile sposobow ustawic 3 osoby", "kolorowanie pod warunkiem", "symetria w liczeniu"],
  },

  // ============ BLOK I: Strategie konkursowe (46-50) ============
  {
    number: 46,
    blockCode: "I",
    block: "Strategie konkursowe",
    title: "Jak czytac zadanie Kangurka",
    topic: "lamiglowki",
    subtopic: "rozumienie polecenia, podkreslanie kluczowych slow",
    goals: ["czego szukamy", "co jest dane", "pulapki w jezyku zadania"],
  },
  {
    number: 47,
    blockCode: "I",
    block: "Strategie konkursowe",
    title: "Szukaj wzoru zamiast liczyc",
    topic: "lamiglowki",
    subtopic: "kiedy nie warto liczyc kazdej rzeczy",
    goals: ["rozpoznanie schematu", "uogolnianie", "ostatnia cyfra / parzystosc jako skrot"],
  },
  {
    number: 48,
    blockCode: "I",
    block: "Strategie konkursowe",
    title: "Eliminacja odpowiedzi ABCDE",
    topic: "lamiglowki",
    subtopic: "wykluczanie zlych odpowiedzi, podstawianie",
    goals: ["sprawdzenie wartosci z odpowiedzi", "szacowanie i wybor zakresu", "wybor 'najbardziej sensownej'"],
  },
  {
    number: 49,
    blockCode: "I",
    block: "Strategie konkursowe",
    title: "Symulacja konkursu - czesc 1 (12 zadan, 35 min)",
    topic: "lamiglowki",
    subtopic: "polowa pelnego konkursu, polowa czasu",
    goals: ["rozplanowanie czasu", "trening pod presja", "swiadomy wybor zadan"],
  },
  {
    number: 50,
    blockCode: "I",
    block: "Strategie konkursowe",
    title: "Symulacja konkursu - czesc 2 + omowienie",
    topic: "lamiglowki",
    subtopic: "druga polowa zadan + analiza wynikow",
    goals: ["dokonczenie symulacji", "rozpoznanie wlasnych slabych punktow", "plan dalszej pracy"],
  },
];

export const BLOCKS = [
  { code: "A", title: "Liczby i dzialania", lessons: "1-8" },
  { code: "B", title: "Wzory, ciagi, regularnosci", lessons: "9-13" },
  { code: "C", title: "Geometria plaska", lessons: "14-21" },
  { code: "D", title: "Geometria przestrzenna", lessons: "22-26" },
  { code: "E", title: "Pomiary i jednostki", lessons: "27-32" },
  { code: "F", title: "Czas i kalendarz", lessons: "33-35" },
  { code: "G", title: "Logika i myslenie", lessons: "36-41" },
  { code: "H", title: "Kombinatoryka i liczenie", lessons: "42-45" },
  { code: "I", title: "Strategie konkursowe", lessons: "46-50" },
] as const;
