import json, os
problems = [
    dict(id="kangur-maluch-2015-1", source="kangur-maluch-2015-1", year=2015, number=1,
         difficulty="3pkt", topic="arytmetyka", subtopic="sekwencja dzialan na chmurkach",
         statement="Pod chmurkami kryja sie liczby. Start: 2, potem -0, potem +1, potem razy 5. Jaka liczba kryje sie pod ostatnia chmurka ze znakiem zapytania?",
         hasImage=True, imageNote="Lancuch chmurek z dzialaniami: 2, -0, +1, razy 5, ?.",
         choices={"A":"6","B":"7","C":"8","D":"10","E":"15"}, correct="E"),
    dict(id="kangur-maluch-2015-2", source="kangur-maluch-2015-2", year=2015, number=2,
         difficulty="3pkt", topic="geometria_plaska", subtopic="porownanie dlugosci paskow",
         statement="Stas mial 10 jednakowych blaszanych paskow. Polaczyl je po dwa i otrzymal 5 dluzszych paskow. Ktory z otrzymanych paskow jest najdluzszy?",
         hasImage=True, imageNote="10 paskow polaczonych w 5, oznaczonych A-E, o roznych dlugosciach nakladania.",
         choices={"A":"A","B":"B","C":"C","D":"D","E":"E"}, correct="B"),
    dict(id="kangur-maluch-2015-3", source="kangur-maluch-2015-3", year=2015, number=3,
         difficulty="3pkt", topic="lamiglowki", subtopic="uklad rownan z figurami",
         statement="Helenka wykonala dwa dzialania: trojkat + 4 = 7 oraz kwadrat + trojkat = 9. Jaka liczbe Helenka zakryla kwadratem?",
         hasImage=False, imageNote=None,
         choices={"A":"2","B":"3","C":"4","D":"5","E":"6"}, correct="E"),
    dict(id="kangur-maluch-2015-4", source="kangur-maluch-2015-4", year=2015, number=4,
         difficulty="3pkt", topic="arytmetyka", subtopic="porownanie ilorazow",
         statement="Ktory z ponizszych ilorazow jest najwiekszy: A) (1000-100):10, B) (1000-10):9, C) (1000-1):9, D) (1000-100):9, E) (1000-10):10?",
         hasImage=False, imageNote=None,
         choices={"A":"(1000-100):10","B":"(1000-10):9","C":"(1000-1):9","D":"(1000-100):9","E":"(1000-10):10"}, correct="C"),
    dict(id="kangur-maluch-2015-5", source="kangur-maluch-2015-5", year=2015, number=5,
         difficulty="3pkt", topic="geometria_plaska", subtopic="rysowanie gwiazdy co druga liczba",
         statement="Na okregu rozmieszczono liczby 1-9. Od liczby 1 rysujemy odcinki laczace co druga liczbe, az wrocimy do 1. Ktory obrazek otrzymamy?",
         hasImage=True, imageNote="Okrag z liczbami 1-9, dwa pierwsze odcinki narysowane, 5 wariantow gwiazdy.",
         choices={"A":"wzor A","B":"wzor B","C":"wzor C","D":"wzor D","E":"wzor E"}, correct="D"),
    dict(id="kangur-maluch-2015-6", source="kangur-maluch-2015-6", year=2015, number=6,
         difficulty="3pkt", topic="arytmetyka", subtopic="iloczyn i suma cyfr",
         statement="Iloczyn cyfr pewnej liczby dwucyfrowej jest rowny 15. Ile wynosi suma cyfr tej liczby?",
         hasImage=False, imageNote=None,
         choices={"A":"2","B":"4","C":"6","D":"7","E":"8"}, correct="E"),
    dict(id="kangur-maluch-2015-7", source="kangur-maluch-2015-7", year=2015, number=7,
         difficulty="3pkt", topic="logika", subtopic="liczenie obiektow w obszarze",
         statement="Rysunek przedstawia wyspe o zawiłej linii brzegowej z palma i zabami. Ile zab siedzi NA wyspie (a nie w wodzie)?",
         hasImage=True, imageNote="Wyspa o nieregularnym ksztalcie z zabami w roznych miejscach.",
         choices={"A":"4","B":"6","C":"7","D":"8","E":"10"}, correct="B"),
    dict(id="kangur-maluch-2015-8", source="kangur-maluch-2015-8", year=2015, number=8,
         difficulty="3pkt", topic="czas_kalendarz", subtopic="dzien tygodnia za N dni",
         statement="Dzis, 19 marca, jest czwartek. Jaki dzien tygodnia bedzie za 30 dni?",
         hasImage=False, imageNote=None,
         choices={"A":"sroda","B":"czwartek","C":"piatek","D":"sobota","E":"niedziela"}, correct="D"),
    dict(id="kangur-maluch-2015-9", source="kangur-maluch-2015-9", year=2015, number=9,
         difficulty="4pkt", topic="geometria_plaska", subtopic="obroty napisu na parasolu",
         statement="Parasol ma na gorze napis KANGAROO ulozony dookola. Na ktorym z 5 rysunkow przedstawiono ten sam parasol (obrocony)?",
         hasImage=True, imageNote="Parasol z napisem KANGAROO dookola i 5 wariantow obroconych.",
         choices={"A":"parasol A","B":"parasol B","C":"parasol C","D":"parasol D","E":"parasol E"}, correct="E"),
    dict(id="kangur-maluch-2015-10", source="kangur-maluch-2015-10", year=2015, number=10,
         difficulty="4pkt", topic="geometria_plaska", subtopic="podzial figury na trojkaty",
         statement="Franek pociął figure narysowana na kratkowanym papierze na jednakowe trojkaty. Ile takich trojkatow otrzymal?",
         hasImage=True, imageNote="Figura na kratce pocieta na jednakowe trojkaty.",
         choices={"A":"8","B":"12","C":"14","D":"15","E":"16"}, correct="E"),
    dict(id="kangur-maluch-2015-11", source="kangur-maluch-2015-11", year=2015, number=11,
         difficulty="4pkt", topic="arytmetyka", subtopic="wymiana i wyrownanie ilosci",
         statement="Tomek mial 7 jablek i 2 banany. Dal 2 jablka Slawkowi, w zamian dostal banany. Teraz ma tyle samo jablek co bananow. Ile bananow dostal od Slawka?",
         hasImage=False, imageNote=None,
         choices={"A":"2","B":"3","C":"4","D":"5","E":"6"}, correct="B"),
    dict(id="kangur-maluch-2015-12", source="kangur-maluch-2015-12", year=2015, number=12,
         difficulty="4pkt", topic="arytmetyka", subtopic="zadanie z reszta i niedoborem",
         statement="Babcia dala kazdemu wnukowi po 4 cukierki i zostaly jej 2. Gdyby dala po 5, zabrakloby jej 2 cukierkow. Ilu wnukow miala babcia?",
         hasImage=False, imageNote=None,
         choices={"A":"3","B":"4","C":"5","D":"6","E":"7"}, correct="B"),
    dict(id="kangur-maluch-2015-13", source="kangur-maluch-2015-13", year=2015, number=13,
         difficulty="4pkt", topic="logika", subtopic="miejsce w biegu z warunkiem",
         statement="Bieg ukonczylo 10 zawodnikow. Przed Frankiem przybieglo o 3 zawodnikow mniej niz za nim. Ktore miejsce zajal Franek?",
         hasImage=False, imageNote=None,
         choices={"A":"1","B":"3","C":"4","D":"6","E":"7"}, correct="C"),
    dict(id="kangur-maluch-2015-14", source="kangur-maluch-2015-14", year=2015, number=14,
         difficulty="4pkt", topic="kombinatoryka", subtopic="ustawienia z warunkiem sasiedztwa",
         statement="Bartek ma 4 zabawki: auto, samolot, pilke, statek. Ustawia je w rzedzie tak, aby zarowno statek jak i samolot staly obok auta. Na ile sposobow moze to zrobic?",
         hasImage=False, imageNote=None,
         choices={"A":"2","B":"4","C":"5","D":"6","E":"8"}, correct="B"),
    dict(id="kangur-maluch-2015-15", source="kangur-maluch-2015-15", year=2015, number=15,
         difficulty="4pkt", topic="geometria_plaska", subtopic="ruch po alejkach ze skretami",
         statement="Pawel jezdzi rowerem po alejkach parku. Wyrusza z linii S, na skrzyzowaniach skreca na przemian: prawo, lewo, prawo, lewo... Kolo ktorego znaku NIE przejedzie?",
         hasImage=True, imageNote="Park z alejkami w ksztalcie kwiatka, znaki A-E, linia startu S.",
         choices={"A":"A","B":"B","C":"C","D":"D","E":"E"}, correct="C"),
    dict(id="kangur-maluch-2015-16", source="kangur-maluch-2015-16", year=2015, number=16,
         difficulty="4pkt", topic="logika", subtopic="liczenie polaczen wg roznicy kropek",
         statement="Na krzaku mieszka 5 biedronek. Dwie biedronki przyjaznia sie, gdy liczby ich kropek roznia sie o 1. Kazda biedronka wyslala SMS do kazdej przyjaciolki. Ile SMS-ow wyslano lacznie?",
         hasImage=True, imageNote="Piec biedronek z roznymi liczbami kropek.",
         choices={"A":"3","B":"4","C":"6","D":"8","E":"9"}, correct="D"),
    dict(id="kangur-maluch-2015-17", source="kangur-maluch-2015-17", year=2015, number=17,
         difficulty="5pkt", topic="geometria_plaska", subtopic="podzial figury na 3 identyczne czesci",
         statement="Figure podzielono na trzy identyczne czesci. Ktory z ponizszych ksztaltow moga miec te czesci?",
         hasImage=True, imageNote="Figura z kwadracikow i 5 wariantow ksztaltu czesci.",
         choices={"A":"ksztalt A","B":"ksztalt B","C":"ksztalt C","D":"ksztalt D","E":"ksztalt E"}, correct="D"),
    dict(id="kangur-maluch-2015-18", source="kangur-maluch-2015-18", year=2015, number=18,
         difficulty="5pkt", topic="geometria_przestrzenna", subtopic="kolorowanie szescianu - bez wspolnych scian",
         statement="Szescian 3x3x3 z 27 malych klockow, kazdy bialy lub szary. Zadne dwa klocki tego samego koloru nie maja wspolnej sciany. Ilu bialych klockow uzyto?",
         hasImage=True, imageNote="Szescian 3x3x3 w kolorach bialym i szarym jak szachownica 3D.",
         choices={"A":"9","B":"12","C":"13","D":"14","E":"17"}, correct="D"),
    dict(id="kangur-maluch-2015-19", source="kangur-maluch-2015-19", year=2015, number=19,
         difficulty="5pkt", topic="logika", subtopic="uklad rownan - pojemnosci dzbanow",
         statement="Beczka napelni sie woda z 6 malych dzbanuszkow + 3 srednich dzbankow + 1 duzy dzban. Napelni sie tez z 2 malych + 1 sredni + 3 duze. Ile duzych dzbanow wody potrzeba, by napelnic beczke?",
         hasImage=False, imageNote=None,
         choices={"A":"4","B":"5","C":"6","D":"7","E":"8"}, correct="A"),
    dict(id="kangur-maluch-2015-20", source="kangur-maluch-2015-20", year=2015, number=20,
         difficulty="5pkt", topic="lamiglowki", subtopic="rownosc sum w krzyzu liczb",
         statement="W krzyz z 5 pol wpisujemy liczby 2, 3, 5, 6, 7 tak, by suma trzech liczb w kolumnie rownala sie sumie trzech w rzedzie. Ktora liczbe mozna wpisac w pole oznaczone znakiem zapytania?",
         hasImage=True, imageNote="Figura w ksztalcie krzyza z 5 polami, jedno oznaczone ?.",
         choices={"A":"Tylko 3","B":"Tylko 5","C":"Tylko 7","D":"Tylko 5 i 7","E":"Tylko 3, 5 i 7"}, correct="E"),
    dict(id="kangur-maluch-2015-21", source="kangur-maluch-2015-21", year=2015, number=21,
         difficulty="5pkt", topic="lamiglowki", subtopic="podzial kul wg iloczynow",
         statement="Helenka miala 10 kul ponumerowanych 0-9. Cztery dala Agnieszce, trzy Lusi, trzy zatrzymala. Iloczyn numerow: Helenka 0, Agnieszka 72, Lusia 90. Ile wynosi suma numerow kul Helenki?",
         hasImage=True, imageNote="Dziesiec kul z numerami 0-9.",
         choices={"A":"11","B":"12","C":"13","D":"14","E":"15"}, correct="E"),
    dict(id="kangur-maluch-2015-22", source="kangur-maluch-2015-22", year=2015, number=22,
         difficulty="5pkt", topic="logika", subtopic="laczenie lin w jedna",
         statement="Trzy liny leza na podlodze. Dowiazanie koncow lin jednego z zestawow daje jedna line. Ktory zestaw ma te wlasnosc?",
         hasImage=True, imageNote="Trzy liny i 5 wariantow zestawow dowiazan koncow.",
         choices={"A":"zestaw A","B":"zestaw B","C":"zestaw C","D":"zestaw D","E":"zestaw E"}, correct="C"),
    dict(id="kangur-maluch-2015-23", source="kangur-maluch-2015-23", year=2015, number=23,
         difficulty="5pkt", topic="geometria_plaska", subtopic="nakladanie przezroczystych arkuszy",
         statement="Trzy kwadratowe arkusze przezroczystej folii z zamalowanymi kwadracikami. Mozna je obracac (ale nie odwracac). Ukladamy jeden na drugim. Ile co najwyzej czarnych kwadracikow mozemy zobaczyc?",
         hasImage=True, imageNote="Trzy arkusze 3x3 z roznie zamalowanymi czarnymi kwadracikami.",
         choices={"A":"4","B":"5","C":"6","D":"7","E":"8"}, correct="D"),
    dict(id="kangur-maluch-2015-24", source="kangur-maluch-2015-24", year=2015, number=24,
         difficulty="5pkt", topic="logika", subtopic="podzielnosc - ile upieczono w piatek",
         statement="Ania upiekla 24 ciastka, Basia 25, Celina 26, Danka 27, Ewa 28. Jedna upiekla lacznie 2 razy tyle co w piatek, jedna 3 razy, jedna 4, jedna 5, jedna 6 razy. Ktora upiekla najwiecej ciastek w piatek?",
         hasImage=False, imageNote=None,
         choices={"A":"Ania","B":"Basia","C":"Celina","D":"Danka","E":"Ewa"}, correct="C"),
]
os.makedirs("data/parsed", exist_ok=True)
with open("data/parsed/2015.json","w",encoding="utf-8") as f:
    json.dump({"year":2015,"category":"MALUCH","problems":problems}, f, ensure_ascii=False, indent=2)
print("OK 2015:", len(problems))
