import json, os
problems = [
    dict(id="kangur-maluch-2020-1", source="kangur-maluch-2020-1", year=2020, number=1,
         difficulty="3pkt", topic="arytmetyka", subtopic="suma symetrycznego ciagu",
         statement="Ile to jest 1 + 2 + 3 + 4 + 5 + 4 + 3 + 2 + 1?",
         hasImage=False, imageNote=None,
         choices={"A":"20","B":"22","C":"24","D":"25","E":"31"}, correct="D"),
    dict(id="kangur-maluch-2020-2", source="kangur-maluch-2020-2", year=2020, number=2,
         difficulty="3pkt", topic="logika", subtopic="kolejnosc wzrostu - drugi etap",
         statement="W poniedzialek wyrosl grzyb i kazdego dnia podrastal. Alicja zrobila zdjecie kazdego dnia od poniedzialku do piatku. Ktore zdjecie zrobila we wtorek (drugi dzien)?",
         hasImage=True, imageNote="Piec zdjec grzyba o rosnacej wielkosci.",
         choices={"A":"zdjecie A","B":"zdjecie B","C":"zdjecie C","D":"zdjecie D","E":"zdjecie E"}, correct="B"),
    dict(id="kangur-maluch-2020-3", source="kangur-maluch-2020-3", year=2020, number=3,
         difficulty="3pkt", topic="arytmetyka", subtopic="kolorowanie kratek z wynikiem 20",
         statement="W tabeli sa dzialania: 16+4, 19+1, 28-8, 2 razy 10, 16-4, 7 razy 3. Pokoloruj kratki, w ktorych wynik wynosi 20. Ktora kolorowanke otrzymamy?",
         hasImage=True, imageNote="Tabela 2x3 z dzialaniami, 5 wariantow kolorowanki.",
         choices={"A":"wzor A","B":"wzor B","C":"wzor C","D":"wzor D","E":"wzor E"}, correct="A"),
    dict(id="kangur-maluch-2020-4", source="kangur-maluch-2020-4", year=2020, number=4,
         difficulty="3pkt", topic="geometria_plaska", subtopic="ukladanie figury z kartonikow",
         statement="Franek mial 6 kartonikow (2 kola, 2 trojkaty, prostokat, kreska). Ulozyl z nich jedna z figur. Ktora?",
         hasImage=True, imageNote="Szesc kartonikow i 5 figur do ulozenia.",
         choices={"A":"figura A","B":"figura B","C":"figura C","D":"figura D","E":"figura E"}, correct="D"),
    dict(id="kangur-maluch-2020-5", source="kangur-maluch-2020-5", year=2020, number=5,
         difficulty="3pkt", topic="geometria_plaska", subtopic="porownanie pol zamalowanych",
         statement="Na ktorym z 5 rysunkow (siatki 4x4) obszar zamalowany na szaro jest najwiekszy?",
         hasImage=True, imageNote="Piec siatek 4x4 z roznymi zamalowanymi obszarami.",
         choices={"A":"rysunek A","B":"rysunek B","C":"rysunek C","D":"rysunek D","E":"rysunek E"}, correct="E"),
    dict(id="kangur-maluch-2020-6", source="kangur-maluch-2020-6", year=2020, number=6,
         difficulty="3pkt", topic="wzory_i_ciagi", subtopic="ciag co 3 - najwieksza osiagalna liczba",
         statement="Ela stanela na kwadracie z liczba 1 i przeskakiwala na liczbe o 3 wieksza. Dostepne liczby: 1,4,5,7,8,10,11,13,14,16,18,19,20,21,23,24. Jaka najwieksza liczba, na ktorej mogla stanac?",
         hasImage=True, imageNote="Kwadraty z liczbami narysowane kreda na chodniku.",
         choices={"A":"11","B":"14","C":"18","D":"19","E":"24"}, correct="D"),
    dict(id="kangur-maluch-2020-7", source="kangur-maluch-2020-7", year=2020, number=7,
         difficulty="3pkt", topic="geometria_przestrzenna", subtopic="sciana naprzeciw na kostce",
         statement="Na scianach kostki jest 6 obrazkow (kaczka, slon, mysz, biedronka, pies, mucha). Kostka pokazana w dwoch pozycjach. Ktory obrazek jest naprzeciw kaczki?",
         hasImage=True, imageNote="Kostka z obrazkami pokazana w dwoch ujeciach.",
         choices={"A":"slon","B":"mysz","C":"biedronka","D":"pies","E":"mucha"}, correct="C"),
    dict(id="kangur-maluch-2020-8", source="kangur-maluch-2020-8", year=2020, number=8,
         difficulty="3pkt", topic="wzory_i_ciagi", subtopic="liczba listew w plocie",
         statement="Z listew 1-metrowych Jozek buduje plot. Plot dlugosci 4 m ma okreslona strukture listew. Ile listew potrzebuje Jozek na plot dlugosci 8 m?",
         hasImage=True, imageNote="Plot dlugosci 4 m zbudowany z listew poziomych i pionowych.",
         choices={"A":"36","B":"22","C":"23","D":"32","E":"34"}, correct="E"),
    dict(id="kangur-maluch-2020-9", source="kangur-maluch-2020-9", year=2020, number=9,
         difficulty="4pkt", topic="geometria_plaska", subtopic="kolorowanie obszarow trzema kolorami",
         statement="Kasia pomalowala obrazek z koncentrycznymi pierscieniami trzema kolorami tak, by sasiednie obszary mialy rozne kolory. Zewnetrzny pierscien jest czerwony. Ile obszarow jest czerwonych?",
         hasImage=True, imageNote="Obrazek z koncentrycznymi pierscieniami.",
         choices={"A":"1","B":"2","C":"3","D":"4","E":"5"}, correct="C"),
    dict(id="kangur-maluch-2020-10", source="kangur-maluch-2020-10", year=2020, number=10,
         difficulty="4pkt", topic="logika", subtopic="suma calkowita minus zaslonięte grupy",
         statement="Na tablicy zapisano liczby 1-8. Cztery liczby pod trojkatami daja sume 10, trzy pod kwadratami sume 20. Jaka liczbe przykrywa kolo?",
         hasImage=True, imageNote="Liczby 1-8 zaslonięte magnesami w ksztaltach trojkatow, kwadratow i kola.",
         choices={"A":"3","B":"4","C":"5","D":"6","E":"7"}, correct="D"),
    dict(id="kangur-maluch-2020-11", source="kangur-maluch-2020-11", year=2020, number=11,
         difficulty="4pkt", topic="arytmetyka", subtopic="spotkanie w ruchu - schody",
         statement="Kangur wchodzi 7 schodkow do gory w czasie, gdy krolik schodzi 3 schodki w dol. Schodkow jest 100. Kangur startuje z dolu, krolik z gory. Na ktorym schodku sie spotkaja?",
         hasImage=True, imageNote="Schody ze 100 stopniami, kangur u dolu, krolik u gory.",
         choices={"A":"53","B":"60","C":"63","D":"70","E":"73"}, correct="D"),
    dict(id="kangur-maluch-2020-12", source="kangur-maluch-2020-12", year=2020, number=12,
         difficulty="4pkt", topic="arytmetyka", subtopic="odtworzenie liczb z roznicy",
         statement="Helena zapisala trzy liczby o sumie 50. Od kazdej odjela te sama liczbe i otrzymala wyniki 24, 13 i 7. Ktora z liczb byla jedna z poczatkowych?",
         hasImage=False, imageNote=None,
         choices={"A":"9","B":"11","C":"13","D":"17","E":"23"}, correct="A"),
    dict(id="kangur-maluch-2020-13", source="kangur-maluch-2020-13", year=2020, number=13,
         difficulty="4pkt", topic="geometria_plaska", subtopic="maksymalne pokrycie paska kartonikami",
         statement="Kajtek ma 7 kartonikow roznej dlugosci. Uklada je na pasku bez nakladania i bez wystawania poza pasek. Ilu najwiecej kartonikow moze uzyc, by pokryc caly pasek?",
         hasImage=True, imageNote="Siedem kartonikow roznej dlugosci i pasek do pokrycia.",
         choices={"A":"3","B":"4","C":"5","D":"6","E":"7"}, correct="B"),
    dict(id="kangur-maluch-2020-14", source="kangur-maluch-2020-14", year=2020, number=14,
         difficulty="4pkt", topic="geometria_plaska", subtopic="ukladanie kwadratu z patyczkow",
         statement="Jurek ma patyczki krotsze (1 cm) i dluzsze (3 cm). Z ktorego zestawu moze ulozyc kwadrat (bez lamania i nakladania patyczkow)?",
         hasImage=False, imageNote=None,
         choices={"A":"5 krotszych i 2 dluzsze","B":"3 krotsze i 3 dluzsze","C":"6 krotszych","D":"4 krotsze i 2 dluzsze","E":"6 dluzszych"}, correct="B"),
    dict(id="kangur-maluch-2020-15", source="kangur-maluch-2020-15", year=2020, number=15,
         difficulty="4pkt", topic="geometria_plaska", subtopic="ukladanie wzoru z pieciokatow",
         statement="Zosia uklada wzor w ksztalcie korony z pieciokatnych kartonikow, stykajac trojkaty oznaczone tymi samymi liczbami. Jaka liczba bedzie w szarym trojkacie po skonczeniu wzoru?",
         hasImage=True, imageNote="Pieciokatny kartonik z liczbami 1-5 w trojkatach i wzor korony.",
         choices={"A":"1","B":"2","C":"3","D":"4","E":"5"}, correct="B"),
    dict(id="kangur-maluch-2020-16", source="kangur-maluch-2020-16", year=2020, number=16,
         difficulty="4pkt", topic="arytmetyka", subtopic="rownanie z druzynami 5 lub 6 osob",
         statement="Na oboz przybyly druzyny po 5 lub 6 osob. Lacznie bylo 43 uczestnikow. Ile druzyn przybylo?",
         hasImage=False, imageNote=None,
         choices={"A":"9","B":"8","C":"7","D":"6","E":"4"}, correct="B"),
    dict(id="kangur-maluch-2020-17", source="kangur-maluch-2020-17", year=2020, number=17,
         difficulty="5pkt", topic="geometria_przestrzenna", subtopic="toczenie kostki - suma scian",
         statement="Kostka (suma przeciwleglych scian = 7) toczy sie w prawo po 6 kwadracikach. Jaka bedzie suma oczek na trzech sciankach oznaczonych znakami zapytania na ostatnim kwadraciku?",
         hasImage=True, imageNote="Kostka toczaca sie po 6 kwadracikach, koncowa pozycja z trzema ? na sciankach.",
         choices={"A":"6","B":"7","C":"9","D":"11","E":"12"}, correct="D"),
    dict(id="kangur-maluch-2020-18", source="kangur-maluch-2020-18", year=2020, number=18,
         difficulty="5pkt", topic="czas_kalendarz", subtopic="urodziny w marcu wzgledem dnia konkursu",
         statement="Szescioro dzieci ma urodziny w marcu: 14, 15, 20, 21, 22 i 27. Ile z nich obchodzilo juz lub bedzie obchodzic urodziny w marcu, liczac od dnia konkursu (trzeci czwartek marca)?",
         hasImage=False, imageNote=None,
         choices={"A":"2","B":"3","C":"4","D":"5","E":"6"}, correct="E"),
    dict(id="kangur-maluch-2020-19", source="kangur-maluch-2020-19", year=2020, number=19,
         difficulty="5pkt", topic="kombinatoryka", subtopic="przyporzadkowanie smakow i dodatkow",
         statement="Szescioro dzieci: 3 lody waniliowe, 2 czekoladowe, 1 cytrynowy. Dodatki: 1 posypka, 2 ciasteczka, 3 wisnie. Zadne dwoje nie ma tej samej kombinacji. Jakich lodow NIE kupilo zadne dziecko?",
         hasImage=True, imageNote="Lody o roznych smakach i dodatkach.",
         choices={"A":"Czekoladowych z wisniami","B":"Waniliowych z wisniami","C":"Cytrynowych z ciastkiem","D":"Czekoladowych z ciastkiem","E":"Waniliowych z posypka"}, correct="C"),
    dict(id="kangur-maluch-2020-20", source="kangur-maluch-2020-20", year=2020, number=20,
         difficulty="5pkt", topic="logika", subtopic="wybor kodu z unikalnymi symbolami",
         statement="Kod tworza 4 symbole na 4 pozycjach. Poprawny kod ma te wlasnosc, ze kazdy jego symbol na danej pozycji nie wystepuje w zadnym innym kodzie na tej pozycji. Ktorego kodu uzyc?",
         hasImage=True, imageNote="Piec kodow A-E zlozonych z 4 symboli (kolo, trojkat, kwadrat, gwiazda).",
         choices={"A":"kod A","B":"kod B","C":"kod C","D":"kod D","E":"kod E"}, correct="D"),
    dict(id="kangur-maluch-2020-21", source="kangur-maluch-2020-21", year=2020, number=21,
         difficulty="5pkt", topic="logika", subtopic="minimalna liczba dzieci w rodzinie",
         statement="W rodzinie kazde dziecko ma co najmniej jednego brata i kazde ma wiecej siostr niz braci. Ile co najmniej dzieci jest w tej rodzinie?",
         hasImage=False, imageNote=None,
         choices={"A":"6","B":"5","C":"4","D":"3","E":"2"}, correct="A"),
    dict(id="kangur-maluch-2020-22", source="kangur-maluch-2020-22", year=2020, number=22,
         difficulty="5pkt", topic="geometria_plaska", subtopic="podzial figury na 3 rozne czesci",
         statement="Ktorej z 5 figur NIE da sie pociac na trzy czesci tak, by kazda miala inny ksztalt i kazda byla zlozona z 5 zacieniowanych kratek (ciac tylko wzdluz linii)?",
         hasImage=True, imageNote="Piec figur zlozonych z 15 zacieniowanych kratek kazda.",
         choices={"A":"figura A","B":"figura B","C":"figura C","D":"figura D","E":"figura E"}, correct="D"),
    dict(id="kangur-maluch-2020-23", source="kangur-maluch-2020-23", year=2020, number=23,
         difficulty="5pkt", topic="lamiglowki", subtopic="kryptarytm - maksymalizacja wyniku",
         statement="W lamiglowce NAR - RAC + JA pod kazda litera ukryta jest cyfra 1-9 (takie same litery = ta sama cyfra, rozne litery = rozne cyfry). Jaki najwiekszy wynik mozna otrzymac?",
         hasImage=False, imageNote=None,
         choices={"A":"976","B":"929","C":"886","D":"877","E":"261"}, correct="C"),
    dict(id="kangur-maluch-2020-24", source="kangur-maluch-2020-24", year=2020, number=24,
         difficulty="5pkt", topic="logika", subtopic="dekodowanie bajkowego jezyka",
         statement="Bajkowy jezyk. Tlumaczenia zdan 'Mama lubi banany', 'Tata lubi jablka', 'Brat uwielbia banany', 'Siostra uwielbia banany' (nie w tej kolejnosci) to: 'Ewe tum kete', 'Ato bem kito', 'Awe tum kete', 'Alo tum kito'. Jak brzmi 'Mama uwielbia jablka'?",
         hasImage=False, imageNote=None,
         choices={"A":"Alo tum kete","B":"Ewe bem kete","C":"Alo bem kete","D":"Alo tum kito","E":"Alo bem kito"}, correct="C"),
]
os.makedirs("data/parsed", exist_ok=True)
with open("data/parsed/2020.json","w",encoding="utf-8") as f:
    json.dump({"year":2020,"category":"MALUCH","problems":problems}, f, ensure_ascii=False, indent=2)
print("OK 2020:", len(problems))
