import json, os
problems = [
    dict(id="kangur-maluch-2021-1", source="kangur-maluch-2021-1", year=2021, number=1,
         difficulty="3pkt", topic="geometria_przestrzenna", subtopic="budowla z 4 klockow",
         statement="Kajtek ma 4 prostopadlosc1enne klocki. Ktora z 5 ponizszych budowli mogl z nich zbudowac?",
         hasImage=True, imageNote="Cztery klocki i 5 wariantow budowli.",
         choices={"A":"budowla A","B":"budowla B","C":"budowla C","D":"budowla D","E":"budowla E"}, correct="A"),
    dict(id="kangur-maluch-2021-2", source="kangur-maluch-2021-2", year=2021, number=2,
         difficulty="3pkt", topic="logika", subtopic="liczenie ryb po wyprostowaniu linki",
         statement="Ile ryb bedzie mialo glowe zwrocona w strone kolka, gdy wyprostujemy linke?",
         hasImage=True, imageNote="Zakrecona linka z rybami i kolkiem na koncu.",
         choices={"A":"3","B":"5","C":"6","D":"7","E":"8"}, correct="C"),
    dict(id="kangur-maluch-2021-3", source="kangur-maluch-2021-3", year=2021, number=3,
         difficulty="3pkt", topic="lamiglowki", subtopic="dzialanie z elementow ukladanki",
         statement="Z czterech elementow ukladanki Jozek ulozyl prostokat z zapisem dzialania arytmetycznego (cyfry 3, 2, 1 i znak +). Jaki jest wynik tego dzialania?",
         hasImage=True, imageNote="Cztery elementy ukladanki z cyframi 3, 2, 1 i znakiem +.",
         choices={"A":"6","B":"15","C":"18","D":"24","E":"33"}, correct="D"),
    dict(id="kangur-maluch-2021-4", source="kangur-maluch-2021-4", year=2021, number=4,
         difficulty="3pkt", topic="geometria_plaska", subtopic="rozpoznanie fragmentu rysunku",
         statement="Ala narysowala sloneczko. Ktory z 5 obrazkow NIE przedstawia fragmentu rysunku Ali?",
         hasImage=True, imageNote="Sloneczko z promieniami i 5 wariantow fragmentow.",
         choices={"A":"fragment A","B":"fragment B","C":"fragment C","D":"fragment D","E":"fragment E"}, correct="D"),
    dict(id="kangur-maluch-2021-5", source="kangur-maluch-2021-5", year=2021, number=5,
         difficulty="3pkt", topic="arytmetyka", subtopic="najwieksza suma punktow na tarczy",
         statement="Franek i czterej koledzy strzelali po 3 razy do tarczy (pierscienie 10, 9, 8, 7, 6 - srodek 10). Franek zdobyl najwiecej punktow. Do ktorej tarczy strzelal Franek?",
         hasImage=True, imageNote="Piec tarcz z trzema trafieniami kazda.",
         choices={"A":"tarcza A","B":"tarcza B","C":"tarcza C","D":"tarcza D","E":"tarcza E"}, correct="A"),
    dict(id="kangur-maluch-2021-6", source="kangur-maluch-2021-6", year=2021, number=6,
         difficulty="3pkt", topic="arytmetyka", subtopic="rownanie z roznica grzybow",
         statement="Dziadek zebral 20 grzybow: kozlarze i borowiki. Borowikow bylo o 6 wiecej niz kozlarzy. Ile borowikow zebral dziadek?",
         hasImage=False, imageNote=None,
         choices={"A":"9","B":"10","C":"12","D":"13","E":"15"}, correct="D"),
    dict(id="kangur-maluch-2021-7", source="kangur-maluch-2021-7", year=2021, number=7,
         difficulty="3pkt", topic="logika", subtopic="uklad rownan - wagi z kulami",
         statement="Na wagach leza kule trzech kolorow (te same kolory waza tyle samo). Waga 1: biala + szara = 6 kg. Waga 2: czarna + czarna + biala = 14 kg. Waga 3: szara + biala + biala = 10 kg. Ile wazy czarna kula?",
         hasImage=True, imageNote="Trzy wagi z kulami w trzech kolorach.",
         choices={"A":"3 kg","B":"4 kg","C":"5 kg","D":"6 kg","E":"7 kg"}, correct="C"),
    dict(id="kangur-maluch-2021-8", source="kangur-maluch-2021-8", year=2021, number=8,
         difficulty="3pkt", topic="logika", subtopic="zamiana dwoch kart - grupowanie owocow",
         statement="Ignacy ma karty z owocami w 3 rodzajach. Na ktorym z 5 obrazkow NIE moze zamienic dwoch kart miejscami tak, by owoce tego samego rodzaju lezaly obok siebie?",
         hasImage=True, imageNote="Piec ukladow kart z owocami.",
         choices={"A":"uklad A","B":"uklad B","C":"uklad C","D":"uklad D","E":"uklad E"}, correct="D"),
    dict(id="kangur-maluch-2021-9", source="kangur-maluch-2021-9", year=2021, number=9,
         difficulty="4pkt", topic="kombinatoryka", subtopic="wybor figur o roznych ksztaltach",
         statement="Ania chce wyjac z 5 pudelek 5 figur o roznych ksztaltach, z kazdego pudelka jedna. Ktora figure powinna wyjac z czwartego pudelka?",
         hasImage=True, imageNote="Piec pudelek z figurami roznych ksztaltow.",
         choices={"A":"gwiazda","B":"kolo","C":"pieciokat","D":"trojkat","E":"romb"}, correct="C"),
    dict(id="kangur-maluch-2021-10", source="kangur-maluch-2021-10", year=2021, number=10,
         difficulty="4pkt", topic="geometria_przestrzenna", subtopic="szara czesc budowli",
         statement="Slawek skleil osobno klocki biale, czarne i szare. Z trzech czesci zbudowal prostopadlosc1enna budowle z 18 kostek. Na ktorym obrazku przedstawiona jest szara czesc?",
         hasImage=True, imageNote="Budowla z 18 kostek w 3 kolorach, 5 wariantow szarej czesci.",
         choices={"A":"czesc A","B":"czesc B","C":"czesc C","D":"czesc D","E":"czesc E"}, correct="B"),
    dict(id="kangur-maluch-2021-11", source="kangur-maluch-2021-11", year=2021, number=11,
         difficulty="4pkt", topic="logika", subtopic="ulozenie nalepek wedlug warunkow",
         statement="Ewa naklejala 5 nalepek (trojkat, kolo, gwiazda, kwiatek, jablko) na kratki 1-5. Gwiazda nie na kratce 5, jablko na kratce 1, kwiatek dokladnie miedzy kolem a trojkatem. Na ktorej kratce jest kwiatek?",
         hasImage=True, imageNote="Piec nalepek i prostokat z kratkami 1-5.",
         choices={"A":"5","B":"4","C":"3","D":"2","E":"1"}, correct="B"),
    dict(id="kangur-maluch-2021-12", source="kangur-maluch-2021-12", year=2021, number=12,
         difficulty="4pkt", topic="arytmetyka", subtopic="liczenie pozostalych lisci",
         statement="Na kazdej z 3 galezi roslo 20 lisci. Z pierwszej koala zjadl kilka lisci. Z drugiej zjadl tyle, ile pozostalo na pierwszej. Z trzeciej zjadl 2 liscie. Ile lisci lacznie pozostalo na trzech galeziach?",
         hasImage=False, imageNote=None,
         choices={"A":"38","B":"32","C":"28","D":"22","E":"20"}, correct="A"),
    dict(id="kangur-maluch-2021-13", source="kangur-maluch-2021-13", year=2021, number=13,
         difficulty="4pkt", topic="pieniadze", subtopic="kwota poczatkowa z dwoch stanow kasy",
         statement="W kasie lodziarni byla pewna kwota. Po sprzedazy 6 porcji lodow bylo 70 zl, po sprzedazy 16 porcji bylo 120 zl. Ile zlotych bylo w kasie przed otwarciem?",
         hasImage=False, imageNote=None,
         choices={"A":"20","B":"30","C":"40","D":"50","E":"60"}, correct="C"),
    dict(id="kangur-maluch-2021-14", source="kangur-maluch-2021-14", year=2021, number=14,
         difficulty="4pkt", topic="logika", subtopic="zderzenia figur - kumulacja wartosci",
         statement="Piec figur z liczbami 10, 9, 3, 7, 20 porusza sie w jednej linii. Gdy figury jada na siebie, wieksza pozera mniejsza i zwieksza swoja wartosc o liczbe pokonanej. Jaki bedzie wynik zderzenia wszystkich pieciu figur?",
         hasImage=True, imageNote="Piec figur z liczbami 10, 9, 3, 7, 20 i strzalkami kierunku.",
         choices={"A":"50 (kwadrat)","B":"48 (kwadrat)","C":"49 (romb)","D":"50 (kolo)","E":"49 (szesciokat)"}, correct="C"),
    dict(id="kangur-maluch-2021-15", source="kangur-maluch-2021-15", year=2021, number=15,
         difficulty="4pkt", topic="geometria_plaska", subtopic="dlugosc z wymiarow prostokatow",
         statement="Na obrazku widzimy prostokaty z wymiarami 32 cm, 36 cm i 48 cm. Jaka dlugosc oznaczono znakiem zapytania?",
         hasImage=True, imageNote="Uklad prostokatow z wymiarami 32, 36, 48 cm i odcinkiem ?.",
         choices={"A":"22 cm","B":"20 cm","C":"16 cm","D":"14 cm","E":"12 cm"}, correct="B"),
    dict(id="kangur-maluch-2021-16", source="kangur-maluch-2021-16", year=2021, number=16,
         difficulty="4pkt", topic="logika", subtopic="powtarzalna czynnosc - stan kubkow",
         statement="Kostek ma 3 kubki. 10 razy powtarza: bierze lewy kubek, odwraca go i stawia po prawej. Jak wygladaly kubki po 10 czynnosciach (na poczatku wszystkie dnem do dolu)?",
         hasImage=True, imageNote="Trzy kubki i 5 wariantow ich stanu po czynnosciach.",
         choices={"A":"uklad A","B":"uklad B","C":"uklad C","D":"uklad D","E":"uklad E"}, correct="C"),
    dict(id="kangur-maluch-2021-17", source="kangur-maluch-2021-17", year=2021, number=17,
         difficulty="5pkt", topic="lamiglowki", subtopic="diagram ze strzalkami mniejsza-wieksza",
         statement="W diagram 3x3 Helenka wpisuje liczby 1-9, po jednej w kratke. Strzalki prowadza od liczby mniejszej do wiekszej. Wpisane sa 5 i 7. Jaka liczbe wpisac w miejscu znaku zapytania?",
         hasImage=True, imageNote="Diagram 3x3 ze strzalkami, wpisane liczby 5 i 7, jedna kratka oznaczona ?.",
         choices={"A":"2","B":"3","C":"4","D":"6","E":"8"}, correct="E"),
    dict(id="kangur-maluch-2021-18", source="kangur-maluch-2021-18", year=2021, number=18,
         difficulty="5pkt", topic="arytmetyka", subtopic="dzielniki i reszta",
         statement="W pudelku jest mniej niz 50 ciastek. Mozna je podzielic rowno miedzy 2, 3 i 4 dzieci. Przy dzieleniu miedzy 7 dzieci brakuje 6 ciastek. Ile ciastek jest w pudelku?",
         hasImage=False, imageNote=None,
         choices={"A":"12","B":"24","C":"30","D":"36","E":"48"}, correct="D"),
    dict(id="kangur-maluch-2021-19", source="kangur-maluch-2021-19", year=2021, number=19,
         difficulty="5pkt", topic="logika", subtopic="ktory balonik na pewno trafiony",
         statement="Stas rzucal lotkami do balonikow z punktami 3, 9, 13, 14, 18. Lacznie zdobyl 30 punktow. W balonik z jaka liczba NA PEWNO trafil?",
         hasImage=True, imageNote="Piec balonikow z liczbami 3, 9, 13, 14, 18.",
         choices={"A":"3","B":"9","C":"13","D":"14","E":"18"}, correct="A"),
    dict(id="kangur-maluch-2021-20", source="kangur-maluch-2021-20", year=2021, number=20,
         difficulty="5pkt", topic="lamiglowki", subtopic="diagram z sumami sasiednich par",
         statement="W kratki diagramu (rzad 9 kratek) wpisujemy liczby 1-9. Nad i pod diagramem podano sumy dwoch sasiednich pol. Jaka liczbe wpisac w kratce ze znakiem zapytania?",
         hasImage=True, imageNote="Rzad 9 kratek z sumami par sasiednich pol nad i pod.",
         choices={"A":"7","B":"6","C":"5","D":"4","E":"3"}, correct="D"),
    dict(id="kangur-maluch-2021-21", source="kangur-maluch-2021-21", year=2021, number=21,
         difficulty="5pkt", topic="logika", subtopic="podzial owocow wedlug wagi",
         statement="W 5 skrzyniach sa jablka lub banany. Wagi: 7, 5, 6, 2, 16 kg. Wszystkie banany waza 3 razy wiecej niz wszystkie jablka. W ktorych skrzyniach sa jablka?",
         hasImage=True, imageNote="Piec skrzyn z wagami 7, 5, 6, 2, 16 kg.",
         choices={"A":"1 i 2","B":"2 i 3","C":"2 i 4","D":"3 i 4","E":"1 i 4"}, correct="E"),
    dict(id="kangur-maluch-2021-22", source="kangur-maluch-2021-22", year=2021, number=22,
         difficulty="5pkt", topic="logika", subtopic="rownowaga wagi - co dolozyc",
         statement="Na wagach leza trzy rodzaje figur (trojkat, kwadrat, kolo - te same waza tyle samo). Co nalezy dolozyc na lewa szalke trzeciej wagi, by byla w rownowadze?",
         hasImage=True, imageNote="Trzy wagi z figurami, trzecia niewyrownana.",
         choices={"A":"kwadrat","B":"dwa kwadraty","C":"kolo","D":"trojkat","E":"dwa trojkaty"}, correct="D"),
    dict(id="kangur-maluch-2021-23", source="kangur-maluch-2021-23", year=2021, number=23,
         difficulty="5pkt", topic="logika", subtopic="pomylka w typowaniu kolejnosci",
         statement="Ela wytypowala kolejnosc na mecie 8 koni. Kon Strzala ukonczyl bieg na pozycji WYZSZEJ niz wytypowala Ela, a pozostale 7 koni na pozycjach NIZSZYCH. O ile miejsc pomylila sie Ela co do Strzaly?",
         hasImage=False, imageNote=None,
         choices={"A":"7","B":"4","C":"2","D":"1","E":"Nie da sie ustalic"}, correct="A"),
    dict(id="kangur-maluch-2021-24", source="kangur-maluch-2021-24", year=2021, number=24,
         difficulty="5pkt", topic="lamiglowki", subtopic="minimalna suma - dodawanie 3-cyfrowych",
         statement="W dzialaniu (trzycyfrowa) + (trzycyfrowa) = (trzycyfrowa) trzeba wpisac 9 roznych cyfr (kazda kratka inna cyfra), tak by wynik byl poprawny. Jaka najmniejsza sume mozna uzyskac?",
         hasImage=True, imageNote="Diagram dodawania pisemnego trzech liczb trzycyfrowych.",
         choices={"A":"249","B":"365","C":"305","D":"345","E":"356"}, correct="E"),
]
os.makedirs("data/parsed", exist_ok=True)
with open("data/parsed/2021.json","w",encoding="utf-8") as f:
    json.dump({"year":2021,"category":"MALUCH","problems":problems}, f, ensure_ascii=False, indent=2)
print("OK 2021:", len(problems))
