"""Bloki E i F - lekcje 27-35, v1+v2, maks oryginalow."""
import json

def orig(year, number):
    with open(f"data/parsed/{year}.json", encoding="utf-8") as f:
        d = json.load(f)
    for p in d["problems"]:
        if p["number"] == number:
            return p
    raise ValueError(f"No {year}#{number}")

def gen(lid, ver, sfx, diff, topic, subtopic, statement, choices, correct):
    return dict(id=f"gen-l{lid}-{ver}-{sfx}", source=f"generated-l{lid}-{ver}-{sfx}",
                year=None, number=None, difficulty=diff, topic=topic, subtopic=subtopic,
                statement=statement, hasImage=False, imageNote=None, choices=choices, correct=correct)

def sol(pid, obs, strat, steps, ans, alt=None):
    return dict(problemId=pid, observation=obs, strategy=strat, steps=steps, answer=ans, alternative=alt)

def lesson(lid, number, block, blockCode, title, topic, minutes, intro, tool, trick, v1, v2, quiz):
    return dict(id=lid, number=number, block=block, blockCode=blockCode,
                title=title, topic=topic, estimatedMinutes=minutes,
                theory=dict(intro=intro, tool=tool, trick=trick),
                versions=[v1, v2], quiz=quiz)

def ver(vid, label, warmup, challenge, solutions):
    return dict(versionId=vid, label=label, warmup=warmup, challenge=challenge, solutions=solutions)

LESSONS = []

# ====================== BLOK E: POMIARY I JEDNOSTKI ======================

# LEKCJA 27: Dlugosc
l27 = lesson("l27", 27, "Pomiary i jednostki", "E", "Dlugosc: mm, cm, dm, m, km", "pomiary_jednostki", 14,
    "Miarka, linijka, taśma w sklepie. Aby zmierzyć wszystko od ołówka po wycieczkę po Polsce, mamy różne jednostki długości: milimetry (mm), centymetry (cm), decymetry (dm), metry (m) i kilometry (km). Każda następna jest 10 (lub 1000) razy większa.",
    "Sztuczka 1: ZAMIANY MIĘDZY JEDNOSTKAMI. 1 cm = 10 mm, 1 dm = 10 cm, 1 m = 10 dm = 100 cm = 1000 mm, 1 km = 1000 m. Mnoż lub dziel przez 10, 100, 1000.\n\nSztuczka 2: NA WIĘKSZA - DZIEL, NA MNIEJSZA - MNOZ. 250 cm na metry: dzielę przez 100 = 2,5 m. 3 m na cm: mnożę przez 100 = 300 cm.\n\nSztuczka 3: ZAOKRAGLIJ DO TEJ SAMEJ JEDNOSTKI. Porównując 250 cm i 3 m, zamień obie na cm: 250 cm i 300 cm - 3 m jest dłuższe.\n\nSztuczka 4: SZACUJ ROZMIARY. Ołówek ~15 cm. Wzrost dziecka ~140 cm = 1,4 m. Tor wyścigowy ~400 m. Wycieczka po mieście ~5 km.",
    "Kangur lubi mieszać jednostki w jednym zadaniu. Zawsze sprowadź wszystko do TEJ SAMEJ jednostki przed liczeniem - bez tego pomylisz się na pewno. Najlepiej do najmniejszej (cm), żeby uniknąć ułamków.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(27,"v1","w1","3pkt","pomiary_jednostki","zamiana cm na mm",
            "Ile milimetrow ma 8 centymetrow?",
            {"A":"8","B":"18","C":"80","D":"800","E":"108"},"C"),
         gen(27,"v1","w2","3pkt","pomiary_jednostki","zamiana m na cm",
            "Ile centymetrow ma 2 metry?",
            {"A":"20","B":"200","C":"2000","D":"2","E":"22"},"B"),
         gen(27,"v1","w3","3pkt","pomiary_jednostki","zamiana m na km",
            "Ile metrow ma pol kilometra?",
            {"A":"50","B":"100","C":"500","D":"1000","E":"5000"},"C"),
         gen(27,"v1","w4","3pkt","pomiary_jednostki","porownanie dlugosci",
            "Co jest dluzsze: 150 cm czy 2 metry?",
            {"A":"150 cm","B":"2 metry","C":"Sa rowne","D":"Nie da sie porownac","E":"Zalezy"},"B"),
         orig(2018,16)],
        [gen(27,"v1","c1","4pkt","pomiary_jednostki","suma dlugosci",
            "Linijka ma 30 cm, lina 2 m, sznur 50 cm. Ile to lacznie w centymetrach?",
            {"A":"82","B":"230","C":"280","D":"320","E":"500"},"C"),
         gen(27,"v1","c2","5pkt","pomiary_jednostki","odleglosc miedzy miastami",
            "Z miasta A do B jest 7 km. Z B do C jest 4500 m. Ile metrow lacznie z A do C przez B?",
            {"A":"7500","B":"11000","C":"11500","D":"45000","E":"75000"},"C")],
        [sol("gen-l27-v1-w1","1 cm = 10 mm.","Mnozenie przez 10.",["8 cm = 8 razy 10 mm = 80 mm"],"C"),
         sol("gen-l27-v1-w2","1 m = 100 cm.","Mnozenie przez 100.",["2 m = 2 razy 100 cm = 200 cm"],"B"),
         sol("gen-l27-v1-w3","1 km = 1000 m, polowa = 500 m.","Polowa 1000.",["1 km = 1000 m","Pol km = 500 m"],"C"),
         sol("gen-l27-v1-w4","Zamiana na te sama jednostke.","Sprowadzanie do cm.",
            ["2 m = 200 cm","200 cm > 150 cm"],"B"),
         sol("kangur-maluch-2018-16","Pasek z 5 dziurkami co 2 cm.",
            "Liczenie roznicy obwodow.",
            ["Roznica miedzy 1. a 5. dziurka to 4 odstepy razy 2 cm = 8 cm","Pasek na 1. dziurke jest dluzszy o 8 cm"],"B"),
         sol("gen-l27-v1-c1","Sprowadz wszystko do cm.","Zamiana jednostek + dodawanie.",
            ["Linijka: 30 cm","Lina: 2 m = 200 cm","Sznur: 50 cm","Razem: 30 + 200 + 50 = 280 cm"],"C"),
         sol("gen-l27-v1-c2","Wszystko do metrow.","Zamiana km + dodawanie.",
            ["7 km = 7000 m","Razem: 7000 + 4500 = 11500 m"],"C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(27,"v2","w1","3pkt","pomiary_jednostki","zamiana mm na cm",
            "Ile centymetrow ma 50 milimetrow?",
            {"A":"5","B":"50","C":"500","D":"0.5","E":"500"},"A"),
         gen(27,"v2","w2","3pkt","pomiary_jednostki","zamiana km na m",
            "Ile metrow ma 3 kilometry?",
            {"A":"30","B":"300","C":"3000","D":"30000","E":"300000"},"C"),
         gen(27,"v2","w3","3pkt","pomiary_jednostki","zamiana dm na cm",
            "Ile centymetrow ma 6 decymetrow?",
            {"A":"6","B":"60","C":"600","D":"16","E":"66"},"B"),
         gen(27,"v2","w4","3pkt","pomiary_jednostki","najwiecej",
            "Ktora dlugosc jest najwieksza?",
            {"A":"100 cm","B":"1 m","C":"1000 mm","D":"10 dm","E":"5 m"},"E"),
         gen(27,"v2","w5","3pkt","pomiary_jednostki","praktyczna miara",
            "Pisak ma najczesciej dlugosc okolo:",
            {"A":"1 cm","B":"15 cm","C":"1 m","D":"50 cm","E":"1 km"},"B")],
        [gen(27,"v2","c1","4pkt","pomiary_jednostki","odejmowanie z jednostkami",
            "Mama ma wstazke 3 m. Odcia 75 cm. Ile cm wstazki zostalo?",
            {"A":"225","B":"250","C":"272","D":"300","E":"325"},"A"),
         gen(27,"v2","c2","5pkt","pomiary_jednostki","skladanie kawalkow",
            "Z czterech kawalkow tasiemki: 50 cm, 60 cm, 75 cm i 1 m zlozono jeden dlugi pasek. Ile metrow ma ten pasek?",
            {"A":"1.85","B":"2.45","C":"2.85","D":"3.00","E":"3.25"},"C")],
        [sol("gen-l27-v2-w1","1 cm = 10 mm, wiec dziel przez 10.","Dzielenie.",["50 mm : 10 = 5 cm"],"A"),
         sol("gen-l27-v2-w2","1 km = 1000 m.","Mnozenie przez 1000.",["3 km = 3 razy 1000 m = 3000 m"],"C"),
         sol("gen-l27-v2-w3","1 dm = 10 cm.","Mnozenie.",["6 dm = 6 razy 10 cm = 60 cm"],"B"),
         sol("gen-l27-v2-w4","Sprowadz do tej samej jednostki.","Porownanie.",
            ["100 cm = 1 m, 1000 mm = 1 m, 10 dm = 1 m, 5 m - najwieksze"],"E"),
         sol("gen-l27-v2-w5","Pisak ~15 cm.","Praktyczne miary.",["Typowy pisak ma 15 cm"],"B"),
         sol("gen-l27-v2-c1","Zamien 3 m na cm.","Zamiana + odejmowanie.",
            ["3 m = 300 cm","300 - 75 = 225 cm"],"A"),
         sol("gen-l27-v2-c2","Sprowadz wszystko do cm, potem na metry.","Sumowanie i zamiana.",
            ["50 + 60 + 75 + 100 = 285 cm","285 cm = 2.85 m"],"C")]),
    [dict(q="1 m to ile cm?", choices={"A":"10","B":"100","C":"1000"}, correct="B",
          explain="1 m = 100 cm."),
     dict(q="1 km to ile m?", choices={"A":"100","B":"1000","C":"10000"}, correct="B",
          explain="1 km = 1000 m."),
     dict(q="Co dluzsze: 250 cm czy 2.5 m?", choices={"A":"250 cm","B":"2.5 m","C":"Rowne"}, correct="C",
          explain="250 cm = 2.5 m - sa rowne.")])
LESSONS.append(l27)

# LEKCJA 28: Masa
l28 = lesson("l28", 28, "Pomiary i jednostki", "E", "Masa: g, dag, kg, t", "pomiary_jednostki", 14,
    "Wagi w sklepie, na poczcie, w aptece. Masa to ile czegos wazy. Jednostki: gram (g), dekagram (dag), kilogram (kg) i tona (t). Tabliczka czekolady ~100 g, jablko ~150 g, dziecko ~30 kg, slon ~5 ton.",
    "Sztuczka 1: ZAMIANY MASY. 1 dag = 10 g, 1 kg = 100 dag = 1000 g, 1 t = 1000 kg.\n\nSztuczka 2: NA WIEKSZA - DZIEL, NA MNIEJSZA - MNOZ. 2500 g na kg: dziel przez 1000 = 2,5 kg. 3 kg na g: mnoż przez 1000 = 3000 g.\n\nSztuczka 3: WAGI W SKLEPIE. Cena czesto za 100 g (dag) lub za kg. Liczac koszt: cena za 100g razy ilosc 100g.\n\nSztuczka 4: SZACUJ MASY. List ~20 g, jablko ~150 g, bochenek chleba ~500 g, mlotek ~1 kg, plecak szkolny ~5 kg.",
    "Pulapka Kangurka: zadania z 'pol kg' albo 'cwierc kg'. 1 kg = 1000 g, wiec pol kg = 500 g, cwierc = 250 g. Często mieszane z dag - pamietaj, ze 1 kg = 100 dag.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(28,"v1","w1","3pkt","pomiary_jednostki","zamiana kg na g",
            "Ile gramow ma 3 kilogramy?",
            {"A":"30","B":"300","C":"3000","D":"30000","E":"300000"},"C"),
         gen(28,"v1","w2","3pkt","pomiary_jednostki","zamiana dag na g",
            "Ile gramow ma 5 dekagramow?",
            {"A":"5","B":"50","C":"500","D":"5000","E":"55"},"B"),
         gen(28,"v1","w3","3pkt","pomiary_jednostki","polowa kg",
            "Pol kilograma to ile gramow?",
            {"A":"50","B":"100","C":"250","D":"500","E":"1000"},"D"),
         gen(28,"v1","w4","3pkt","pomiary_jednostki","porownanie mas",
            "Co waży WIECEJ: 2 kg czy 1500 g?",
            {"A":"2 kg","B":"1500 g","C":"Tyle samo","D":"Nie da sie porownac","E":"Zalezy"},"A"),
         orig(2019,13)],
        [gen(28,"v1","c1","4pkt","pomiary_jednostki","laczna masa zakupow",
            "Ola kupila 2 kg jablek, 500 g masla i 250 g czekolady. Ile gramow razem?",
            {"A":"750","B":"2500","C":"2750","D":"2950","E":"3000"},"C"),
         gen(28,"v1","c2","5pkt","pomiary_jednostki","cena za 100g",
            "Cukierki kosztuja 4 zl za 100 g. Ile zl trzeba zaplacic za pol kilograma cukierkow?",
            {"A":"4","B":"10","C":"20","D":"40","E":"400"},"C")],
        [sol("gen-l28-v1-w1","1 kg = 1000 g.","Mnozenie przez 1000.",["3 kg = 3 razy 1000 g = 3000 g"],"C"),
         sol("gen-l28-v1-w2","1 dag = 10 g.","Mnozenie.",["5 dag = 5 razy 10 g = 50 g"],"B"),
         sol("gen-l28-v1-w3","Pol kg = polowa 1000 g.","Dzielenie przez 2.",["1 kg = 1000 g, pol kg = 500 g"],"D"),
         sol("gen-l28-v1-w4","Zamien na te sama jednostke.","Porownanie.",
            ["2 kg = 2000 g","2000 g > 1500 g, wiec 2 kg ciezsze"],"A"),
         sol("kangur-maluch-2019-13","Szklanka pelna 400g, pusta 100g, do polowy?",
            "Polowa zawartosci wody.",
            ["Woda w pelnej szklance: 400 - 100 = 300 g","Polowa wody: 150 g","Pusta szklanka + 150 g wody = 100 + 150 = 250 g"],"D"),
         sol("gen-l28-v1-c1","Sprowadz wszystko do g.","Zamiana + dodawanie.",
            ["2 kg = 2000 g","2000 + 500 + 250 = 2750 g"],"C"),
         sol("gen-l28-v1-c2","Pol kg to 5 razy 100 g.","Liczenie porcji.",
            ["Pol kg = 500 g = 5 razy 100 g","5 razy 4 zl = 20 zl"],"C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(28,"v2","w1","3pkt","pomiary_jednostki","zamiana g na dag",
            "Ile dekagramow ma 80 gramow?",
            {"A":"8","B":"80","C":"800","D":"0.8","E":"18"},"A"),
         gen(28,"v2","w2","3pkt","pomiary_jednostki","zamiana t na kg",
            "Ile kilogramow ma 2 tony?",
            {"A":"20","B":"200","C":"2000","D":"20000","E":"200000"},"C"),
         gen(28,"v2","w3","3pkt","pomiary_jednostki","cwierc kg",
            "Cwierc kilograma to ile gramow?",
            {"A":"100","B":"200","C":"250","D":"400","E":"500"},"C"),
         gen(28,"v2","w4","3pkt","pomiary_jednostki","najciezsze",
            "Co waży NAJWIECEJ?",
            {"A":"500 g","B":"50 dag","C":"1 kg","D":"100 g","E":"5000 g"},"E"),
         gen(28,"v2","w5","3pkt","pomiary_jednostki","praktyczna masa",
            "Tabliczka czekolady waży zwykle okolo:",
            {"A":"10 g","B":"100 g","C":"1 kg","D":"500 g","E":"10 kg"},"B")],
        [gen(28,"v2","c1","4pkt","pomiary_jednostki","reszta po odjeciu",
            "Worek z ziemniakami waży 5 kg. Mama wzieła 1 kg 200 g. Ile gramow ziemniakow zostalo?",
            {"A":"3800","B":"4000","C":"4200","D":"3500","E":"4800"},"A"),
         gen(28,"v2","c2","5pkt","pomiary_jednostki","masy roznych produktow",
            "Trzy paczki: 1 kg, 1500 g i pol kg. Ile to lacznie kilogramow?",
            {"A":"2","B":"2.5","C":"3","D":"3.5","E":"4"},"C")],
        [sol("gen-l28-v2-w1","1 dag = 10 g, dziel przez 10.","Dzielenie.",["80 g : 10 = 8 dag"],"A"),
         sol("gen-l28-v2-w2","1 t = 1000 kg.","Mnozenie.",["2 t = 2 razy 1000 kg = 2000 kg"],"C"),
         sol("gen-l28-v2-w3","Cwierc = czwarta czesc 1000 g.","Dzielenie przez 4.",["1000 g : 4 = 250 g"],"C"),
         sol("gen-l28-v2-w4","Sprowadz wszystko do g.","Porownanie.",
            ["500 g, 500 g (50 dag), 1000 g (1 kg), 100 g, 5000 g","Najwiecej: 5000 g"],"E"),
         sol("gen-l28-v2-w5","Tabliczka czekolady ~100 g.","Praktyczna masa.",["Standard tabliczki to 100 g"],"B"),
         sol("gen-l28-v2-c1","Sprowadz na gramy.","Zamiana + odejmowanie.",
            ["5 kg = 5000 g","1 kg 200 g = 1200 g","5000 - 1200 = 3800 g"],"A"),
         sol("gen-l28-v2-c2","Sprowadz na kg.","Zamiana + sumowanie.",
            ["1 kg + 1.5 kg + 0.5 kg = 3 kg"],"C")]),
    [dict(q="1 kg to ile g?", choices={"A":"100","B":"1000","C":"10000"}, correct="B",
          explain="1 kg = 1000 g."),
     dict(q="Pol kg to:", choices={"A":"250 g","B":"500 g","C":"5000 g"}, correct="B",
          explain="Pol kg = 500 g."),
     dict(q="Co ciezsze: 1 kg ksiazek czy 1 kg pierza?",
          choices={"A":"Ksiazki","B":"Pierze","C":"Tyle samo"}, correct="C",
          explain="1 kg to zawsze 1 kg, niezaleznie od materialu.")])
LESSONS.append(l28)

# LEKCJA 29: Pojemnosc
l29 = lesson("l29", 29, "Pomiary i jednostki", "E", "Pojemnosc: ml, l", "pomiary_jednostki", 12,
    "Butelka wody, sok, mleko. Pojemnosc to ile plynu miesci sie w naczyniu. Jednostki: mililitr (ml) i litr (l). 1 l = 1000 ml. Szklanka ma okolo 250 ml, butelka wody 500 ml lub 1.5 l, baniak na mleko 5 l.",
    "Sztuczka 1: 1 LITR = 1000 ML. To podstawa. Zamiany jak w innych jednostkach: na wieksza dziel przez 1000, na mniejsza mnoz przez 1000.\n\nSztuczka 2: SZACUJ POJEMNOSCI. Szklanka ~250 ml = cwierc litra. 4 szklanki = 1 litr. Wanna ~150 l. Basen ogrodowy ~2000 l.\n\nSztuczka 3: ZADANIA Z PRZELEWANIEM. Mama nalala soku z duzej butelki 2 l do trzech szklanek po 250 ml. Ile zostalo? 2000 ml - 3 razy 250 ml = 2000 - 750 = 1250 ml.\n\nSztuczka 4: TA SAMA JEDNOSTKA. Porownujac 750 ml i 1 l, zamien oba na ml: 750 ml < 1000 ml.",
    "Pulapka: czesto w zadaniach jest 'butelka' bez podanej pojemnosci - musisz zalozyc standard (np. 1 l) albo informacja jest na obrazku. Czytaj uwaznie - jezeli nie ma jednoznacznej miary, to nie ma rozwiazania.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(29,"v1","w1","3pkt","pomiary_jednostki","zamiana l na ml",
            "Ile mililitrow ma 2 litry?",
            {"A":"20","B":"200","C":"2000","D":"20000","E":"22"},"C"),
         gen(29,"v1","w2","3pkt","pomiary_jednostki","zamiana ml na l",
            "Ile litrow ma 3000 mililitrow?",
            {"A":"3","B":"30","C":"300","D":"0.3","E":"33"},"A"),
         gen(29,"v1","w3","3pkt","pomiary_jednostki","cwierc litra",
            "Szklanka ma pojemnosc 250 ml. Ile to litra?",
            {"A":"Pol litra","B":"Cwierc litra","C":"Caly litr","D":"1/5 litra","E":"2 litry"},"B"),
         gen(29,"v1","w4","3pkt","pomiary_jednostki","ile szklanek na litr",
            "Ile szklanek po 250 ml miesci w sobie 1 litr?",
            {"A":"2","B":"3","C":"4","D":"5","E":"10"},"C"),
         gen(29,"v1","w5","3pkt","pomiary_jednostki","praktyczna pojemnosc",
            "Butelka wody mineralnej ma zwykle pojemnosc okolo:",
            {"A":"50 ml","B":"500 ml","C":"5 l","D":"50 l","E":"500 l"},"B")],
        [gen(29,"v1","c1","4pkt","pomiary_jednostki","odejmowanie pojemnosci",
            "Wiadro ma 8 litrow wody. Mama wziela 750 ml na podlewanie. Ile ml wody zostalo w wiadrze?",
            {"A":"7250","B":"7000","C":"7500","D":"8000","E":"6500"},"A"),
         gen(29,"v1","c2","5pkt","pomiary_jednostki","ile butelek z duzej",
            "Z 5-litrowego baniaka mleka napelniono male butelki po 250 ml. Ile butelek udalo sie napelnic?",
            {"A":"10","B":"15","C":"20","D":"25","E":"50"},"C")],
        [sol("gen-l29-v1-w1","1 l = 1000 ml.","Mnozenie.",["2 l = 2 razy 1000 = 2000 ml"],"C"),
         sol("gen-l29-v1-w2","Dziel przez 1000.","Dzielenie.",["3000 : 1000 = 3 l"],"A"),
         sol("gen-l29-v1-w3","250 ml = 1/4 litra.","Cwierc litra.",["1 l = 1000 ml, 250 = 1000:4 = cwierc litra"],"B"),
         sol("gen-l29-v1-w4","4 razy 250 ml = 1000 ml.","Liczenie szklanek.",["1000 : 250 = 4 szklanki"],"C"),
         sol("gen-l29-v1-w5","Standardowa butelka ~500 ml.","Praktyczna pojemnosc.",["Typowa butelka mineralnej to 500 ml"],"B"),
         sol("gen-l29-v1-c1","Sprowadz wszystko na ml.","Zamiana + odejmowanie.",
            ["8 l = 8000 ml","8000 - 750 = 7250 ml"],"A"),
         sol("gen-l29-v1-c2","Sprowadz na ml i dziel.","Dzielenie ilosci.",
            ["5 l = 5000 ml","5000 : 250 = 20 butelek"],"C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(29,"v2","w1","3pkt","pomiary_jednostki","zamiana l na ml",
            "Ile mililitrow ma 1.5 litra?",
            {"A":"15","B":"150","C":"1500","D":"15000","E":"50"},"C"),
         gen(29,"v2","w2","3pkt","pomiary_jednostki","pol litra",
            "Pol litra to ile mililitrow?",
            {"A":"50","B":"250","C":"500","D":"5000","E":"1000"},"C"),
         gen(29,"v2","w3","3pkt","pomiary_jednostki","wieksze",
            "Co miesci WIECEJ wody: 700 ml czy 1 litr?",
            {"A":"700 ml","B":"1 litr","C":"Sa rowne","D":"Nie da sie ustalic","E":"Zalezy"},"B"),
         gen(29,"v2","w4","3pkt","pomiary_jednostki","szklanki",
            "Dzbanek 1.5 l wody. Ile szklanek po 250 ml mozna nim napelnic?",
            {"A":"4","B":"5","C":"6","D":"7","E":"8"},"C"),
         gen(29,"v2","w5","3pkt","pomiary_jednostki","najwieksza pojemnosc",
            "Co ma NAJWIEKSZA pojemnosc?",
            {"A":"Szklanka","B":"Lyzeczka","C":"Wiadro","D":"Butelka 0.5 l","E":"Filizanka"},"C")],
        [gen(29,"v2","c1","4pkt","pomiary_jednostki","wlewanie wody",
            "Akwarium miesci 50 litrow. Wlano 23 l wody. Ile litrow potrzeba dolac, by je napelnic?",
            {"A":"23","B":"25","C":"27","D":"30","E":"73"},"C"),
         gen(29,"v2","c2","5pkt","pomiary_jednostki","sciezka przelewania",
            "Z butelki 2 l wlano sok do 4 szklanek po 250 ml i 2 kubeczkow po 200 ml. Ile ml soku zostalo w butelce?",
            {"A":"400","B":"500","C":"600","D":"700","E":"800"},"C")],
        [sol("gen-l29-v2-w1","1.5 l to 1500 ml.","Mnozenie.",["1.5 razy 1000 = 1500 ml"],"C"),
         sol("gen-l29-v2-w2","Pol litra = 500 ml.","Polowa 1000.",["1000:2 = 500 ml"],"C"),
         sol("gen-l29-v2-w3","Zamien na ml i porownaj.","Porownanie.",
            ["1 l = 1000 ml > 700 ml"],"B"),
         sol("gen-l29-v2-w4","1.5 l = 1500 ml.","Dzielenie.",["1500 : 250 = 6 szklanek"],"C"),
         sol("gen-l29-v2-w5","Wiadro ma najwieksza pojemnosc.","Praktyczna miara.",
            ["Wiadro ~10 l, reszta mniej"],"C"),
         sol("gen-l29-v2-c1","Akwarium 50 l minus 23 l.","Odejmowanie.",["50 - 23 = 27 l"],"C"),
         sol("gen-l29-v2-c2","Sprowadz na ml.","Zamiana + odejmowanie.",
            ["Butelka: 2 l = 2000 ml","Szklanki: 4 razy 250 = 1000 ml","Kubeczki: 2 razy 200 = 400 ml","Zostalo: 2000 - 1000 - 400 = 600 ml"],"C")]),
    [dict(q="1 l to ile ml?", choices={"A":"10","B":"100","C":"1000"}, correct="C",
          explain="1 l = 1000 ml."),
     dict(q="Pol litra to:", choices={"A":"50 ml","B":"500 ml","C":"5000 ml"}, correct="B",
          explain="Pol litra = 500 ml."),
     dict(q="Cwierc litra to tyle, ile mniej wiecej:",
          choices={"A":"Lyzeczka","B":"Szklanka","C":"Wiadro"}, correct="B",
          explain="Szklanka to standardowo 250 ml = cwierc litra.")])
LESSONS.append(l29)

# LEKCJA 30: Czas (jako pomiar)
l30 = lesson("l30", 30, "Pomiary i jednostki", "E", "Czas: minuty, godziny, doba", "pomiary_jednostki", 14,
    "Ile trwa film? Ile minut do konca lekcji? O ktorej godzinie wstajesz? Czas to specjalna jednostka - dzielimy go na sekundy, minuty, godziny i doby. Najwazniejsze relacje: 60 sekund = 1 minuta, 60 minut = 1 godzina, 24 godziny = 1 doba.",
    "Sztuczka 1: PODSTAWOWE ZAMIANY. 1 min = 60 sek, 1 godz = 60 min = 3600 sek, 1 doba = 24 godz. Mnoż lub dziel przez 60 (na/z min) lub 24 (na/z doby).\n\nSztuczka 2: OBLICZANIE CZASU TRWANIA. Film zaczyna sie o 16:00 i konczy o 17:30. Ile trwa? 17:30 - 16:00 = 1 godz 30 min.\n\nSztuczka 3: PRZEZ POLNOC. Z 22:00 do 6:00 rano: od 22:00 do polnocy = 2 godz, od polnocy do 6:00 = 6 godz. Razem 8 godzin.\n\nSztuczka 4: SZCZEGOLNE LICZBY. 15 min = cwierc godziny, 30 min = pol godziny, 45 min = 3/4 godziny. Te liczby pojawiaja sie czesto.",
    "Pulapka Kangurka: zadania o czasie 'do tylu' albo 'przed'. Spacer 38 min, wrocila o 12:00 - kiedy wyszla? Najlatwiej odejmowac: 12:00 minus 38 min = 11:22. Najpierw od 12:00 odejmij 40 min (=11:20), potem dodaj 2 = 11:22.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(30,"v1","w1","3pkt","pomiary_jednostki","zamiana godz na min",
            "Ile minut ma 2 godziny?",
            {"A":"20","B":"60","C":"100","D":"120","E":"200"},"D"),
         gen(30,"v1","w2","3pkt","pomiary_jednostki","cwierc godziny",
            "Cwierc godziny to ile minut?",
            {"A":"10","B":"15","C":"20","D":"25","E":"30"},"B"),
         gen(30,"v1","w3","3pkt","pomiary_jednostki","doba",
            "Ile godzin ma jedna doba?",
            {"A":"12","B":"20","C":"24","D":"60","E":"100"},"C"),
         gen(30,"v1","w4","3pkt","pomiary_jednostki","czas trwania",
            "Lekcja zaczyna sie o 8:00, konczy o 8:45. Ile trwa?",
            {"A":"35 min","B":"40 min","C":"45 min","D":"50 min","E":"1 godzina"},"C"),
         orig(2019,3)],
        [gen(30,"v1","c1","4pkt","pomiary_jednostki","czas przez polnoc",
            "Pociag wyjechal o 22:00, dojechal o 5:00 rano. Ile godzin trwala podroz?",
            {"A":"3","B":"5","C":"7","D":"8","E":"17"},"C"),
         gen(30,"v1","c2","5pkt","pomiary_jednostki","odlicznie wstecz",
            "Spotkanie konczy sie o 18:30. Trwalo 2 godziny i 45 minut. O ktorej godzinie sie zaczelo?",
            {"A":"15:30","B":"15:45","C":"16:00","D":"16:15","E":"17:00"},"B")],
        [sol("gen-l30-v1-w1","1 godz = 60 min.","Mnozenie.",["2 razy 60 = 120 min"],"D"),
         sol("gen-l30-v1-w2","Cwierc godziny = polowa polowy.","Dzielenie 60:4.",["60:4 = 15 min"],"B"),
         sol("gen-l30-v1-w3","1 doba = 24 godz.","Standard doby.",["Doba ma 24 godziny"],"C"),
         sol("gen-l30-v1-w4","Roznica miedzy 8:45 a 8:00.","Odejmowanie czasu.",["8:45 - 8:00 = 45 min"],"C"),
         sol("kangur-maluch-2019-3","Asia wrocila o 12:05, spacer trwal 38 min.",
            "Odejmowanie czasu wstecz.",
            ["12:05 - 38 min: cofamy o 38 min","12:05 - 35 min = 11:30","11:30 - 3 min = 11:27"],"D"),
         sol("gen-l30-v1-c1","Z 22:00 do polnocy + z polnocy do 5:00.","Czas przez polnoc.",
            ["22:00 do 24:00 = 2 godz","24:00 do 5:00 = 5 godz","Razem 7 godz"],"C"),
         sol("gen-l30-v1-c2","Cofnij sie o 2 godz 45 min od 18:30.","Odejmowanie wstecz.",
            ["18:30 - 2 godz = 16:30","16:30 - 45 min = 15:45"],"B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(30,"v2","w1","3pkt","pomiary_jednostki","zamiana min na sek",
            "Ile sekund ma 3 minuty?",
            {"A":"30","B":"60","C":"90","D":"180","E":"300"},"D"),
         gen(30,"v2","w2","3pkt","pomiary_jednostki","pol godziny",
            "Pol godziny to ile minut?",
            {"A":"15","B":"20","C":"30","D":"45","E":"60"},"C"),
         gen(30,"v2","w3","3pkt","pomiary_jednostki","trzy cwierci godziny",
            "Trzy cwierci godziny to ile minut?",
            {"A":"15","B":"30","C":"45","D":"60","E":"75"},"C"),
         gen(30,"v2","w4","3pkt","pomiary_jednostki","czas trwania",
            "Film zaczyna sie o 16:15, konczy o 18:00. Ile trwa?",
            {"A":"1 godz 15 min","B":"1 godz 30 min","C":"1 godz 45 min","D":"2 godz","E":"2 godz 15 min"},"C"),
         orig(2014,11)],
        [gen(30,"v2","c1","4pkt","pomiary_jednostki","odjecie czasu",
            "Pociag dotarl o 14:20. Podroz trwala 3 godz 35 min. O ktorej wyjechal?",
            {"A":"10:35","B":"10:45","C":"10:55","D":"11:00","E":"11:15"},"B"),
         gen(30,"v2","c2","5pkt","pomiary_jednostki","ilosc minut na dobe",
            "Ile minut ma cala doba?",
            {"A":"360","B":"720","C":"1440","D":"2400","E":"3600"},"C")],
        [sol("gen-l30-v2-w1","1 min = 60 sek.","Mnozenie.",["3 razy 60 = 180 sek"],"D"),
         sol("gen-l30-v2-w2","Pol godziny = polowa 60 min.","Polowa.",["60:2 = 30 min"],"C"),
         sol("gen-l30-v2-w3","Trzy cwierci = 3 razy 15 min.","Mnozenie.",["3 razy 15 = 45 min"],"C"),
         sol("gen-l30-v2-w4","Czas trwania = roznica.","Odejmowanie czasu.",
            ["Od 16:15 do 17:15 = 1 godz","Od 17:15 do 18:00 = 45 min","Razem 1 godz 45 min"],"C"),
         sol("kangur-maluch-2014-11","Spiaca Krolewna spi 150 godzin od piatku 23:00.",
            "Dodawanie wielu godzin.",
            ["150 godz : 24 = 6 dni i 6 godz","Piatek 23:00 + 6 dni = czwartek 23:00","Czwartek 23:00 + 6 godz = piatek 5:00"],"E"),
         sol("gen-l30-v2-c1","Cofnij 3 godz 35 min od 14:20.","Odejmowanie czasu.",
            ["14:20 - 3 godz = 11:20","11:20 - 35 min = 10:45"],"B"),
         sol("gen-l30-v2-c2","Doba = 24 godz razy 60 min.","Mnozenie.",["24 razy 60 = 1440 min"],"C")]),
    [dict(q="1 godzina to ile minut?", choices={"A":"30","B":"60","C":"100"}, correct="B",
          explain="1 godz = 60 min."),
     dict(q="Pol godziny to:", choices={"A":"20 min","B":"30 min","C":"45 min"}, correct="B",
          explain="Pol godziny = 30 min."),
     dict(q="Liczac czas trwania zdarzenia:",
          choices={"A":"Dodajesz konce","B":"Odejmujesz koniec - poczatek","C":"Zgadujesz"}, correct="B",
          explain="Czas trwania = czas koncowy minus poczatkowy.")])
LESSONS.append(l30)

# LEKCJA 31: Pieniadze
l31 = lesson("l31", 31, "Pomiary i jednostki", "E", "Pieniadze, reszta, zakupy", "pieniadze", 15,
    "Idziesz do sklepu z 50 zl. Kupujesz cos za 32 zl. Ile reszty? 50 - 32 = 18 zl. To codzienna matematyka. Pieniadze to liczby z konkretnym sensem - zlotowki (zl) i grosze (gr). 1 zl = 100 gr.",
    "Sztuczka 1: ZL I GROSZE. 1 zl = 100 gr. Cena 4 zl 50 gr = 450 gr. Konce zawsze sumuj do zlotowek (np. 50 + 50 = 100 = 1 zl).\n\nSztuczka 2: RESZTA. Reszta = ile dales minus cena. 50 zl - 32 zl = 18 zl. Jezeli dales za malo, reszty nie ma (musisz doplaty).\n\nSztuczka 3: ILE MOZESZ KUPIC. Masz 20 zl, jablko 2 zl - kupisz 10 jablek. Dzielisz: 20:2 = 10. Jezeli wychodzi z reszta, kupujesz tyle co wynosi calkowita czesc.\n\nSztuczka 4: ZAOKRAGLENIE PRZY ROZWAGANIU. Wybor 3 z 5 produktow - sprawdzaj kombinacje od najwiekszych do najmniejszych cen.",
    "Pulapka: zadania o reszcie i wymianie. 'Dostal 18 zl reszty' - to nie cena, to roznica! Kupil 3 zabawki za X zl, dal banknot 50 zl, dostal 18 reszty. X = 50 - 18 = 32 zl - to suma cen 3 zabawek.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(31,"v1","w1","3pkt","pieniadze","prosta reszta",
            "Mam 50 zl, kupuje cos za 27 zl. Ile dostane reszty?",
            {"A":"13 zl","B":"17 zl","C":"23 zl","D":"27 zl","E":"33 zl"},"C"),
         gen(31,"v1","w2","3pkt","pieniadze","ile mozna kupic",
            "Ola ma 30 zl, czekolada 5 zl. Ile czekolad moze kupic?",
            {"A":"3","B":"5","C":"6","D":"10","E":"15"},"C"),
         gen(31,"v1","w3","3pkt","pieniadze","zl i grosze",
            "Ile groszy jest w 2 zl 50 gr?",
            {"A":"52","B":"205","C":"250","D":"2050","E":"500"},"C"),
         orig(2024,6),
         orig(2012,10)],
        [orig(2014,13),
         orig(2019,15)],
        [sol("gen-l31-v1-w1","Reszta = 50 - 27.","Odejmowanie.",["50 - 27 = 23 zl"],"C"),
         sol("gen-l31-v1-w2","Ile razy 5 miesci sie w 30.","Dzielenie.",["30:5 = 6 czekolad"],"C"),
         sol("gen-l31-v1-w3","1 zl = 100 gr.","Zamiana zl na gr.",["2 zl = 200 gr","200 + 50 = 250 gr"],"C"),
         sol("kangur-maluch-2024-6","3 rozne ciastka, lacznie 7 zl, ceny calkowite.",
            "Rozklad na sume 3 roznych liczb dodatnich.",
            ["7 = 1 + 2 + 4 (jedyny rozklad na 3 rozne dodatnie)","Najdrozsze ciastko: 4 zl"],"C"),
         sol("kangur-maluch-2012-10","5 balonow drozsze od 2 balonow o 1.20 zl.",
            "Roznica cen 3 balonow = 1.20 zl.",
            ["5 balonow - 2 balony = 3 balony","3 balony kosztuja 1.20 zl = 120 gr","1 balon: 120:3 = 40 gr"],"C"),
         sol("kangur-maluch-2014-13","Zabawki, suma 3 kupionych = 200 - 18 = 182.",
            "Suma 3 cen, potem wymiana na 25 zl mniej.",
            ["Pierwsze 3 zabawki: 200 - 18 = 182","Lalka(73) + Mis(52) + Klocki(57) = 182","Po wymianie 200 - 18 - 25 = 157 zl","Mis(52) + Puzzle(48) + Klocki(57) = 157","Ostatecznie: Mis, Puzzle, Klocki"],"D"),
         sol("kangur-maluch-2019-15","3 ceny par owocow: 3.50 + 2.50 + 4.00.",
            "Suma trzech par = 2 razy suma trzech owocow.",
            ["Suma par: 3.50 + 2.50 + 4.00 = 10 zl","Suma trzech owocow: 10:2 = 5 zl"],"D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(31,"v2","w1","3pkt","pieniadze","reszta z banknotu",
            "Tomek ma 100 zl, kupil ksiazke za 47 zl. Ile dostal reszty?",
            {"A":"43 zl","B":"53 zl","C":"57 zl","D":"63 zl","E":"73 zl"},"B"),
         gen(31,"v2","w2","3pkt","pieniadze","sumowanie cen",
            "Lody 8 zl, sok 5 zl, batonik 3 zl. Ile lacznie?",
            {"A":"13 zl","B":"15 zl","C":"16 zl","D":"17 zl","E":"18 zl"},"C"),
         gen(31,"v2","w3","3pkt","pieniadze","cwierc zlotowki",
            "Ile groszy to cwierc zlotowki?",
            {"A":"4 gr","B":"10 gr","C":"25 gr","D":"50 gr","E":"100 gr"},"C"),
         orig(2021,13),
         gen(31,"v2","w5","3pkt","pieniadze","ile bardziej",
            "Lalka kosztuje 35 zl, mis 28 zl. O ile zl drozsza jest lalka?",
            {"A":"3 zl","B":"5 zl","C":"7 zl","D":"63 zl","E":"15 zl"},"C")],
        [gen(31,"v2","c1","4pkt","pieniadze","wymiana banknotow",
            "Mama ma 200 zl w postaci jednego banknotu. Rozmienila go na 4 jednakowe banknoty. Po jakim nominale?",
            {"A":"10 zl","B":"20 zl","C":"40 zl","D":"50 zl","E":"100 zl"},"D"),
         gen(31,"v2","c2","5pkt","pieniadze","zbieranie na cel",
            "Ada chce kupic gre za 80 zl. Ma juz 15 zl, a kazdy tydzien oszczedza 13 zl. Po ilu tygodniach zbierze potrzebna kwote?",
            {"A":"3","B":"4","C":"5","D":"6","E":"7"},"C")],
        [sol("gen-l31-v2-w1","100 - 47.","Odejmowanie.",["100 - 47 = 53 zl"],"B"),
         sol("gen-l31-v2-w2","Sumuj ceny.","Dodawanie.",["8 + 5 + 3 = 16 zl"],"C"),
         sol("gen-l31-v2-w3","100 gr : 4 = 25 gr.","Dzielenie zl na 4.",["1 zl = 100 gr, cwierc = 25 gr"],"C"),
         sol("kangur-maluch-2021-13","Kasa po 6 porcji = 70 zl, po 16 = 120 zl.",
            "Cena porcji + kwota poczatkowa.",
            ["10 dodatkowych porcji = 50 zl","1 porcja = 5 zl","6 porcji = 30 zl","Poczatkowa kwota: 70 - 30 = 40 zl"],"C"),
         sol("gen-l31-v2-w5","Roznica cen.","Odejmowanie.",["35 - 28 = 7 zl"],"C"),
         sol("gen-l31-v2-c1","200 podziel na 4 rowne czesci.","Dzielenie.",["200:4 = 50 zl"],"D"),
         sol("gen-l31-v2-c2","Brakuje 80-15=65 zl, zbiera 13 zl/tydzien.","Dzielenie.",
            ["Brakuje: 80 - 15 = 65 zl","Tygodni: 65 : 13 = 5"],"C")]),
    [dict(q="Dales 50 zl, cena 33 zl - ile reszty?",
          choices={"A":"17 zl","B":"23 zl","C":"27 zl"}, correct="A",
          explain="50 - 33 = 17 zl."),
     dict(q="1 zl to ile groszy?", choices={"A":"10","B":"100","C":"1000"}, correct="B",
          explain="1 zl = 100 gr."),
     dict(q="Masz 30 zl, lody po 4 zl. Ile lodow mozesz kupic?",
          choices={"A":"6","B":"7","C":"8"}, correct="B",
          explain="30:4 = 7 reszta 2 - kupisz 7 lodow.")])
LESSONS.append(l31)

# LEKCJA 32: Mieszane jednostki
l32 = lesson("l32", 32, "Pomiary i jednostki", "E", "Mieszane zadania z jednostkami", "pomiary_jednostki", 14,
    "W jednym zadaniu masz: 3 m dlugiej tasiemki, 200 g masy, 5 zl ceny i 2 godziny czasu. Trzeba czesto laczyc rozne jednostki: dlugosc + cena (cena za metr), masa + cena (zl za kg), czas + odleglosc (km na godzine). Wyzwanie polega na konsekwentnym uzyciu tych samych jednostek.",
    "Sztuczka 1: NAPISZ ZAWSZE JEDNOSTKE. Liczby same w sobie nic nie znacza. '5' to 5 czego? Pisz: 5 cm, 5 kg, 5 zl. To pomaga sprawdzic czy nie pomylisz jednostek.\n\nSztuczka 2: SPROWADZ DO TEJ SAMEJ JEDNOSTKI. Porownujac, dodajac, odejmujac - WSZYSTKO zamien na jedna jednostke. 3 m + 50 cm: zamien na cm, 300+50=350 cm.\n\nSztuczka 3: STAWKA NA JEDNOSTKE. Cena za 1 metr, 1 kg, 1 godzine - to klucz do wielu zadan. Jezeli 5 m kosztuje 25 zl, to 1 m = 5 zl. Wtedy 8 m = 40 zl.\n\nSztuczka 4: CZAS I ODLEGLOSC. Predkosc = ile km na godzine. Idziesz 5 km/h - po 2 godz przejdziesz 10 km. To prosty wzor: odleglosc = predkosc razy czas.",
    "Pulapka Kangurka: ostroznie z 'kilo'. 1 kilogram = 1000 gramow, ale 1 kilometr = 1000 metrow. 'Kilo' to przedrostek oznaczajacy 1000. Nie myl jednostek - cena za kilo (gramow) to cos innego niz cena za kilometr.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(32,"v1","w1","3pkt","pomiary_jednostki","jednostki - rozpoznanie",
            "Czego mierzymy w kilogramach?",
            {"A":"Dlugosci","B":"Czasu","C":"Masy","D":"Pojemnosci","E":"Pieniedzy"},"C"),
         gen(32,"v1","w2","3pkt","pomiary_jednostki","jednostki - rozpoznanie",
            "Czego mierzymy w litrach?",
            {"A":"Dlugosci","B":"Masy","C":"Czasu","D":"Pojemnosci","E":"Powierzchni"},"D"),
         gen(32,"v1","w3","3pkt","pomiary_jednostki","cena za jednostke",
            "5 metrow wstazki kosztuje 25 zl. Ile zl za 1 metr?",
            {"A":"3","B":"4","C":"5","D":"10","E":"20"},"C"),
         gen(32,"v1","w4","3pkt","pomiary_jednostki","predkosc",
            "Idziesz 4 km na godzine. Ile km przejdziesz w 3 godziny?",
            {"A":"7","B":"10","C":"12","D":"15","E":"20"},"C"),
         orig(2016,2)],
        [gen(32,"v1","c1","4pkt","pomiary_jednostki","cena za kg",
            "1 kg jablek kosztuje 4 zl. Ile zl za 2 kg 500 g?",
            {"A":"8","B":"9","C":"10","D":"12","E":"14"},"C"),
         gen(32,"v1","c2","5pkt","pomiary_jednostki","czas i dlugosc",
            "Sciezka ma 1 km 500 m. Ola idzie 100 m na minute. Ile minut bedzie isc cala sciezke?",
            {"A":"10","B":"15","C":"20","D":"25","E":"30"},"B")],
        [sol("gen-l32-v1-w1","Kilogramy mierza mase.","Identyfikacja jednostki.",["kg = masa"],"C"),
         sol("gen-l32-v1-w2","Litry mierza pojemnosc.","Identyfikacja.",["l = pojemnosc"],"D"),
         sol("gen-l32-v1-w3","Cena za 1 m = cena lacznie : ilosc metrow.","Dzielenie.",["25 : 5 = 5 zl/m"],"C"),
         sol("gen-l32-v1-w4","Odleglosc = predkosc razy czas.","Mnozenie.",["4 razy 3 = 12 km"],"C"),
         sol("kangur-maluch-2016-2","Witek 1 rok 3 miesiace, do 3 lat ile miesiecy.",
            "Roznica wieku w miesiacach.",
            ["1 rok 3 mies = 15 mies","3 lata = 36 mies","36 - 15 = 21 mies"],"E"),
         sol("gen-l32-v1-c1","Zamien 2 kg 500 g na pol kg.","Cena za zlozona mase.",
            ["2 kg 500 g = 2.5 kg","2.5 razy 4 = 10 zl"],"C"),
         sol("gen-l32-v1-c2","Sciezka 1500 m, predkosc 100 m/min.","Czas = odleglosc : predkosc.",
            ["1 km 500 m = 1500 m","1500 : 100 = 15 min"],"B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(32,"v2","w1","3pkt","pomiary_jednostki","co czym mierzymy",
            "Czego mierzymy w sekundach?",
            {"A":"Dlugosci","B":"Masy","C":"Czasu","D":"Pojemnosci","E":"Pieniedzy"},"C"),
         gen(32,"v2","w2","3pkt","pomiary_jednostki","predkosc minutowa",
            "Pies biegnie 200 metrow na minute. Ile metrow przebiegnie w 5 minut?",
            {"A":"500","B":"800","C":"1000","D":"1200","E":"2000"},"C"),
         gen(32,"v2","w3","3pkt","pomiary_jednostki","cena za kg",
            "Cukier kosztuje 6 zl za kilogram. Ile za 3 kg?",
            {"A":"9","B":"12","C":"15","D":"18","E":"21"},"D"),
         gen(32,"v2","w4","3pkt","pomiary_jednostki","jednostka cyfra",
            "Stol ma dlugosc 1 metr 50 cm. Ile to centymetrow?",
            {"A":"15","B":"150","C":"1500","D":"105","E":"1050"},"B"),
         gen(32,"v2","w5","3pkt","pomiary_jednostki","cena za 100 g",
            "100 g serow kosztuje 3 zl. Ile za pol kg?",
            {"A":"3 zl","B":"6 zl","C":"10 zl","D":"15 zl","E":"30 zl"},"D")],
        [gen(32,"v2","c1","4pkt","pomiary_jednostki","czas + dlugosc",
            "Maraton ma 42 km. Biegacz biegnie 6 km na godzine. Ile godzin (w przyblizeniu) bedzie biegl?",
            {"A":"5","B":"6","C":"7","D":"8","E":"10"},"C"),
         gen(32,"v2","c2","5pkt","pomiary_jednostki","zlozone zadanie",
            "Mleko kosztuje 4 zl za litr. Mama kupila 2 butelki po 1.5 l. Ile zaplacila?",
            {"A":"6 zl","B":"8 zl","C":"10 zl","D":"12 zl","E":"15 zl"},"D")],
        [sol("gen-l32-v2-w1","Sekundy mierza czas.","Identyfikacja.",["sek = czas"],"C"),
         sol("gen-l32-v2-w2","Odleglosc = predkosc razy czas.","Mnozenie.",["200 razy 5 = 1000 m"],"C"),
         sol("gen-l32-v2-w3","Cena = stawka razy ilosc.","Mnozenie.",["3 razy 6 = 18 zl"],"D"),
         sol("gen-l32-v2-w4","1 m = 100 cm, plus 50 = 150 cm.","Zamiana + dodawanie.",["100 + 50 = 150 cm"],"B"),
         sol("gen-l32-v2-w5","Pol kg = 500 g = 5 razy 100 g.","Mnozenie.",["5 razy 3 zl = 15 zl"],"D"),
         sol("gen-l32-v2-c1","Maraton 42 km, 6 km/h.","Dzielenie.",["42 : 6 = 7 godz"],"C"),
         sol("gen-l32-v2-c2","2 butelki po 1.5 l = 3 l.","Mnozenie i dodawanie.",
            ["2 razy 1.5 = 3 l","3 razy 4 zl = 12 zl"],"D")]),
    [dict(q="Kilogramy mierza:", choices={"A":"Dlugosc","B":"Mase","C":"Czas"}, correct="B",
          explain="kg to jednostka masy."),
     dict(q="1 km na godzine to:",
          choices={"A":"Predkosc","B":"Mase","C":"Czas"}, correct="A",
          explain="km/h to jednostka predkosci."),
     dict(q="Sprowadzenie do jednej jednostki pomaga:",
          choices={"A":"Pomylic sie","B":"Latwiej porownywac i liczyc","C":"Robic blad"}, correct="B",
          explain="Te same jednostki - latwiej porownujemy i liczymy.")])
LESSONS.append(l32)

# ====================== BLOK F: CZAS I KALENDARZ ======================

# LEKCJA 33: Zegar
l33 = lesson("l33", 33, "Czas i kalendarz", "F", "Zegar - godziny i minuty", "czas_kalendarz", 14,
    "Dwie wskazowki taneczne na tarczy zegara. Krotka pokazuje godziny, dluga - minuty. Czesc zegarow ma jeszcze trzecia, bardzo cienka - sekundowa. Odczytywanie zegara analogowego to wazna umiejetnosc, ktora Kangur lubi sprawdzac w roznych formach.",
    "Sztuczka 1: GODZINA Z KROTKIEJ. Krotka wskazowka pokazuje godzine. Jest miedzy 3 a 4 = godzina 3 (zaczela sie ale jeszcze 4 nie). Minutowa pokazuje 30 = 3:30.\n\nSztuczka 2: MINUTOWA - PRZESKAKUJE PO 5. Liczby na zegarze 1-12 dla godzin, ale dla minut kazda to 5 minut. Na 6 = 30 minut, na 9 = 45, na 12 = 0/60.\n\nSztuczka 3: ODBICIE W LUSTRZE. Zegar w lustrze pokazuje 'odwrotny' czas: wskazowki sa odbite poziomo. Aby 'czytac' lustro - wyobraz sobie prawdziwa godzine.\n\nSztuczka 4: KAT MIEDZY WSKAZOWKAMI. O 3:00 wskazowki sa prostopadle (kat prosty). O 6:00 - na linii (kat polpelny). O 12:00 - razem (kat zerowy).",
    "Pulapka Kangurka: zadanie 'spacer trwal X minut, wrocila o godzinie Y'. Najtrudniejsze sa zadania 'cofnij sie o X minut'. Zawsze cofaj najpierw o pelne godziny, potem o minuty. 12:05 - 38 min = 12:05 - 60 + 22 = 11:22? Nie - 11:27 (cofnij 5 min do 12:00, jeszcze 33 do 11:27).",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(33,"v1","w1","3pkt","czas_kalendarz","odczyt zegara",
            "Krotka wskazowka jest na 5, dluga na 12. Ktora godzine pokazuje zegar?",
            {"A":"5:00","B":"5:12","C":"12:05","D":"5:30","E":"12:30"},"A"),
         gen(33,"v1","w2","3pkt","czas_kalendarz","minutowa",
            "Krotka wskazowka jest miedzy 2 a 3, dluga na 6. Ktora godzina?",
            {"A":"2:30","B":"3:30","C":"6:02","D":"6:03","E":"2:06"},"A"),
         gen(33,"v1","w3","3pkt","czas_kalendarz","kat o 3:00",
            "O godzinie 3:00 wskazowki zegara tworza kat:",
            {"A":"Ostry","B":"Prosty","C":"Rozwarty","D":"Polpelny","E":"Zerowy"},"B"),
         orig(2012,21),
         orig(2023,5)],
        [orig(2023,15),
         gen(33,"v1","c1","5pkt","czas_kalendarz","kat 6:00",
            "O godzinie 6:00 wskazowki zegara tworza kat:",
            {"A":"Prosty","B":"Ostry","C":"Rozwarty","D":"Polpelny","E":"Pelny"},"D")],
        [sol("gen-l33-v1-w1","Krotka na 5, dluga na 12 = 5:00.","Odczyt godziny.",["5:00"],"A"),
         sol("gen-l33-v1-w2","Krotka miedzy 2 a 3 = godzina 2. Dluga na 6 = 30 min.","Odczyt.",
            ["Krotka miedzy 2 a 3 = 2 godzina","Dluga na 6 = 30 minut","Razem 2:30"],"A"),
         sol("gen-l33-v1-w3","3:00 wskazowki = jak rog kartki.","Kat na zegarze.",
            ["O 3:00 krotka na 3, dluga na 12, tworza kat prosty"],"B"),
         sol("kangur-maluch-2012-21","Trzy wskazowki o roznej dlugosci, zegar 12:55:30 -> 8:11:00.",
            "Identyfikacja wskazowek i nowego ustawienia.",
            ["Z polozenia o 12:55:30 ustalamy ktora wskazowka jest godzinowa, minutowa i sekundowa","O 8:11:00 wskazowki maja okreslony uklad","Poprawny obraz: C"],"C"),
         sol("kangur-maluch-2023-5","Kolo z 2 otworami obracane na tarczy zegara.",
            "Stala roznica katowa miedzy otworami.",
            ["Otwory pierwotnie pokazuja 1 i 5 - roznica 4 godziny","Dla 2 otworow - musza tez roznic sie o 4","5 i 9 roznia sie o 4 - pasuja"],"C"),
         sol("kangur-maluch-2023-15","5 zegarow: 2 zepsute, 1 dobry, 1 spieszy 3h, 1 spoznia 3h.",
            "Identyfikacja zegara poprawnego.",
            ["3 zegary chodzace pokazuja czasy w odstepach 3h","Srodkowy z tych 3 to zegar poprawny","Poprawny zegar: B"],"B"),
         sol("gen-l33-v1-c1","O 6:00 wskazowki sa naprzeciw siebie.","Kat polpelny.",
            ["O 6:00 krotka na 6, dluga na 12, tworza linie - kat polpelny"],"D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(33,"v2","w1","3pkt","czas_kalendarz","odczyt godziny",
            "Krotka wskazowka pokazuje 9, dluga 12. Ktora godzina?",
            {"A":"9:00","B":"12:09","C":"9:12","D":"9:30","E":"12:30"},"A"),
         gen(33,"v2","w2","3pkt","czas_kalendarz","odczyt z polowa",
            "Krotka miedzy 8 a 9, dluga na 6. Ktora godzina?",
            {"A":"8:30","B":"9:30","C":"6:08","D":"8:06","E":"8:00"},"A"),
         gen(33,"v2","w3","3pkt","czas_kalendarz","kat o 12:00",
            "O godzinie 12:00 wskazowki tworza kat:",
            {"A":"Prosty","B":"Polpelny","C":"Zerowy","D":"Pelny","E":"Rozwarty"},"C"),
         gen(33,"v2","w4","3pkt","czas_kalendarz","minuty z liczby",
            "Dluga wskazowka pokazuje 3. Ile to minut?",
            {"A":"3","B":"15","C":"30","D":"45","E":"60"},"B"),
         gen(33,"v2","w5","3pkt","czas_kalendarz","kat o 9:00",
            "O godzinie 9:00 wskazowki tworza kat:",
            {"A":"Ostry","B":"Prosty","C":"Rozwarty","D":"Polpelny","E":"Pelny"},"B")],
        [gen(33,"v2","c1","4pkt","czas_kalendarz","cofanie wstecz",
            "Jest 14:20. Spacer trwal 1 godzine 15 minut. O ktorej godzinie sie zaczal?",
            {"A":"12:50","B":"13:00","C":"13:05","D":"13:15","E":"13:35"},"C"),
         gen(33,"v2","c2","5pkt","czas_kalendarz","odbicie zegara",
            "Zegar w lustrze pokazuje wskazowki jakby na godzinie 9:00, ale to odbicie. Jaka jest prawdziwa godzina?",
            {"A":"3:00","B":"6:00","C":"9:00","D":"12:00","E":"15:00"},"A")],
        [sol("gen-l33-v2-w1","Krotka na 9, dluga na 12 = 9:00.","Odczyt.",["9:00"],"A"),
         sol("gen-l33-v2-w2","8:30 - krotka miedzy 8 a 9, dluga na 6.","Odczyt.",["8:30"],"A"),
         sol("gen-l33-v2-w3","Wskazowki nakladaja sie - kat zerowy.","Kat o 12:00.",
            ["O 12:00 obie wskazowki sa na 12 - tworza kat zerowy"],"C"),
         sol("gen-l33-v2-w4","Dluga na 3 = 3 razy 5 min = 15 min.","Minutowa z liczby.",["15 minut"],"B"),
         sol("gen-l33-v2-w5","Wskazowki o 9:00 = prostopadle.","Kat prosty.",
            ["O 9:00 krotka na 9, dluga na 12 - tworza kat prosty"],"B"),
         sol("gen-l33-v2-c1","Cofnij od 14:20 o 1 godz 15 min.","Odejmowanie wstecz.",
            ["14:20 - 1 godz = 13:20","13:20 - 15 min = 13:05"],"C"),
         sol("gen-l33-v2-c2","Odbicie lustrzane zamienia 9 z 3.","Odbicie.",
            ["W lustrze pozycje sa odbite","Lustrzane 9:00 to prawdziwe 3:00"],"A")]),
    [dict(q="Krotka wskazowka pokazuje:", choices={"A":"Godziny","B":"Minuty","C":"Sekundy"}, correct="A",
          explain="Krotka to godzinowa."),
     dict(q="Dluga na 6 to ile minut?", choices={"A":"6","B":"30","C":"60"}, correct="B",
          explain="6 razy 5 = 30 minut."),
     dict(q="O 6:00 wskazowki tworza:",
          choices={"A":"Kat prosty","B":"Kat polpelny","C":"Kat zerowy"}, correct="B",
          explain="O 6:00 wskazowki sa naprzeciw - linia prosta = kat polpelny.")])
LESSONS.append(l33)

# LEKCJA 34: Dni tygodnia
l34 = lesson("l34", 34, "Czas i kalendarz", "F", "Dni tygodnia - co bedzie za N dni", "czas_kalendarz", 12,
    "Tydzien ma 7 dni: poniedzialek, wtorek, sroda, czwartek, piatek, sobota, niedziela. Po niedzieli wraca poniedzialek. Zadanie 'jaki dzien bedzie za 30 dni' to wlasnie liczenie po dniach tygodnia z 'zawijaniem'.",
    "Sztuczka 1: TYDZIEN MA 7 DNI. Po 7 dniach jest ZNOW ten sam dzien. Czwartek + 7 dni = czwartek. Czwartek + 14 dni = czwartek (2 tygodnie).\n\nSztuczka 2: RESZTA Z DZIELENIA PRZEZ 7. Co za 30 dni? 30:7 = 4 reszta 2. Czyli 4 pelne tygodnie + 2 dni. Czwartek + 2 dni = sobota.\n\nSztuczka 3: WSTECZ TAK SAMO. 'Co BYLO X dni temu' tez liczysz reszta z 7. Czwartek - 10 dni: 10:7 = 1 reszta 3. Czwartek - 3 dni = poniedzialek.\n\nSztuczka 4: KIERUNEK LICZENIA. 'Dzisiaj sroda, za 3 dni' to sroda + 3 = sobota. 'Wczoraj byla niedziela, jutro' to niedziela + 2 dni = wtorek.",
    "Pulapka: roznica miedzy 'wczoraj' i 'dzisiaj' i 'jutro' to po 1 dniu. 'Pojutrze' = jutro + 1 dzien. 'Wczoraj byla niedziela' znaczy ze dzisiaj poniedzialek, a jutro wtorek. Czytaj uwaznie kierunek czasu.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(34,"v1","w1","3pkt","czas_kalendarz","prosty + 1 dzien",
            "Dzis jest wtorek. Jaki dzien bedzie jutro?",
            {"A":"Poniedzialek","B":"Wtorek","C":"Sroda","D":"Czwartek","E":"Niedziela"},"C"),
         gen(34,"v1","w2","3pkt","czas_kalendarz","+ 7 dni",
            "Dzis jest piatek. Jaki dzien bedzie za tydzien (7 dni)?",
            {"A":"Piatek","B":"Sobota","C":"Czwartek","D":"Niedziela","E":"Poniedzialek"},"A"),
         gen(34,"v1","w3","3pkt","czas_kalendarz","+ kilka dni",
            "Dzis poniedzialek. Jaki dzien za 5 dni?",
            {"A":"Sroda","B":"Czwartek","C":"Piatek","D":"Sobota","E":"Niedziela"},"D"),
         orig(2019,1),
         orig(2015,8)],
        [orig(2018,9),
         gen(34,"v1","c1","5pkt","czas_kalendarz","duza liczba dni",
            "Dzis sroda. Jaki dzien bedzie za 100 dni?",
            {"A":"Wtorek","B":"Sroda","C":"Czwartek","D":"Piatek","E":"Sobota"},"D")],
        [sol("gen-l34-v1-w1","Wtorek + 1 dzien = sroda.","Kolejny dzien.",["Po wtorku jest sroda"],"C"),
         sol("gen-l34-v1-w2","+ 7 dni = ten sam dzien.","Tydzien = 7 dni.",["Piatek + 7 = piatek"],"A"),
         sol("gen-l34-v1-w3","Poniedzialek + 5 dni = sobota.","Liczenie po kolei.",
            ["Pon+1=wt, +2=sr, +3=czw, +4=pt, +5=sob"],"D"),
         sol("kangur-maluch-2019-1","Wczoraj niedziela = dzis poniedzialek = jutro wtorek.",
            "Liczenie dni od niedzieli.",
            ["Wczoraj niedziela","Dzis poniedzialek","Jutro wtorek"],"A"),
         sol("kangur-maluch-2015-8","19 marca = czwartek, za 30 dni jaki dzien?",
            "Reszta z 30:7.",
            ["30 : 7 = 4 reszta 2","Czwartek + 2 dni = sobota"],"D"),
         sol("kangur-maluch-2018-9","Krolik 20 marchewek, codziennie 2, w srode 12. dzien.",
            "Liczenie wstecz dni zjadania.",
            ["12 marchewka = 6 dzien zjadania (12:2=6)","Srodaa to 6 dzien, zaczal 5 dni wczesniej = piatek"],"E"),
         sol("gen-l34-v1-c1","100:7 = 14 reszta 2.","Reszta z dzielenia.",
            ["100 : 7 = 14 reszta 2","Sroda + 2 = piatek"],"D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(34,"v2","w1","3pkt","czas_kalendarz","co bylo wczoraj",
            "Dzis jest wtorek. Jaki dzien byl wczoraj?",
            {"A":"Poniedzialek","B":"Wtorek","C":"Sroda","D":"Niedziela","E":"Sobota"},"A"),
         gen(34,"v2","w2","3pkt","czas_kalendarz","+ 14 dni",
            "Dzis sobota. Jaki dzien bedzie za 2 tygodnie?",
            {"A":"Piatek","B":"Sobota","C":"Niedziela","D":"Poniedzialek","E":"Wtorek"},"B"),
         gen(34,"v2","w3","3pkt","czas_kalendarz","duza liczba",
            "Dzis niedziela. Jaki dzien bedzie za 50 dni?",
            {"A":"Poniedzialek","B":"Wtorek","C":"Sroda","D":"Czwartek","E":"Piatek"},"A"),
         gen(34,"v2","w4","3pkt","czas_kalendarz","- 10 dni",
            "Dzis czwartek. Jaki dzien byl 10 dni temu?",
            {"A":"Niedziela","B":"Poniedzialek","C":"Wtorek","D":"Sroda","E":"Czwartek"},"B"),
         gen(34,"v2","w5","3pkt","czas_kalendarz","jutro i pojutrze",
            "Dzis piatek. Jaki dzien jest pojutrze?",
            {"A":"Sobota","B":"Niedziela","C":"Poniedzialek","D":"Wtorek","E":"Czwartek"},"B")],
        [gen(34,"v2","c1","4pkt","czas_kalendarz","specjalna data",
            "Dzis czwartek 1 marca. Jaki dzien bedzie 1 kwietnia (marzec ma 31 dni)?",
            {"A":"Sobota","B":"Niedziela","C":"Poniedzialek","D":"Wtorek","E":"Sroda"},"B"),
         gen(34,"v2","c2","5pkt","czas_kalendarz","liczenie ujemnie",
            "Za 12 dni bedzie poniedzialek. Jaki dzien jest dzisiaj?",
            {"A":"Niedziela","B":"Poniedzialek","C":"Wtorek","D":"Sroda","E":"Czwartek"},"D")],
        [sol("gen-l34-v2-w1","Wtorek - 1 dzien = poniedzialek.","Dzien wczoraj.",["Pon przed wt"],"A"),
         sol("gen-l34-v2-w2","Sobota + 14 = sobota.","2 tygodnie.",["14 dzieli sie przez 7"],"B"),
         sol("gen-l34-v2-w3","50:7 = 7 reszta 1.","Reszta z dzielenia.",
            ["50 : 7 = 7 reszta 1","7 pelnych tygodni + 1 dzien","Niedziela + 1 = poniedzialek"],"A"),
         sol("gen-l34-v2-w4","10:7 = 1 reszta 3.","Wstecz.",
            ["10 : 7 = 1 reszta 3","Czwartek - 3 = poniedzialek"],"B"),
         sol("gen-l34-v2-w5","Pojutrze = jutro + 1.","2 dni do przodu.",
            ["Piatek + 2 = niedziela"],"B"),
         sol("gen-l34-v2-c1","31 dni do 1 kwietnia.","Liczenie z resztą.",
            ["1 marca + 31 dni = 1 kwietnia","31 : 7 = 4 reszta 3","Czwartek + 3 = niedziela"],"B"),
         sol("gen-l34-v2-c2","Cofnij 12 dni od poniedzialku.","Liczenie wstecz.",
            ["12 : 7 = 1 reszta 5","Poniedzialek - 5 = sroda"],"D")]),
    [dict(q="Tydzien ma:", choices={"A":"5 dni","B":"7 dni","C":"10 dni"}, correct="B",
          explain="Tydzien = 7 dni."),
     dict(q="Co za 14 dni?", choices={"A":"Ten sam dzien","B":"Nastepny dzien","C":"Inny"}, correct="A",
          explain="14 = 2 razy 7, czyli dwa pelne tygodnie."),
     dict(q="Sroda + 30 dni:",
          choices={"A":"Sroda","B":"Piatek","C":"Niedziela"}, correct="B",
          explain="30:7=4 reszta 2. Sroda + 2 = piatek.")])
LESSONS.append(l34)

# LEKCJA 35: Daty, miesiace, odstepy
l35 = lesson("l35", 35, "Czas i kalendarz", "F", "Daty, miesiace, odstepy", "czas_kalendarz", 16,
    "Kalendarz ma 12 miesiecy. Kazdy ma 28, 29, 30 lub 31 dni. Luty jest specjalny - zwykle 28, ale w roku przestepnym 29. Liczenie dat, odstepow miedzy nimi, dni do urodzin - to czesta tresc zadan Kangurka.",
    "Sztuczka 1: DLUGOSCI MIESIACOW. 31 dni: I, III, V, VII, VIII, X, XII (styczen, marzec, maj, lipiec, sierpien, pazdziernik, grudzien). 30 dni: IV, VI, IX, XI (kwiecien, czerwiec, wrzesien, listopad). 28-29 dni: II (luty).\n\nSztuczka 2: ROK PRZESTEPNY. Co 4 lata (2012, 2016, 2020, 2024). Wtedy luty ma 29 dni. Sprawdz: rok dzieli sie przez 4? Tak = przestepny (z drobnym wyjatkiem co 100 lat).\n\nSztuczka 3: ODSTEPY DAT W TYM SAMYM MIESIACU. Od 5 marca do 19 marca: 19-5 = 14 dni.\n\nSztuczka 4: ODSTEPY MIEDZY MIESIACAMI. Od 25 kwietnia do 3 maja: 30-25 = 5 dni (do konca kwietnia) + 3 dni (maj) = 8 dni.",
    "Pulapka Kangurka: zadania z konkursem 'trzeci czwartek marca'. Liczysz tylko czwartki: 1., 2., 3. czwartek. Marzec ma 4 lub 5 czwartkow zaleznie od roku. 'Trzeci czwartek' nie zawsze jest 21. dnia.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(35,"v1","w1","3pkt","czas_kalendarz","dlugosc lutego",
            "Ile dni ma luty w zwyklym (nieprzestepnym) roku?",
            {"A":"28","B":"29","C":"30","D":"31","E":"32"},"A"),
         gen(35,"v1","w2","3pkt","czas_kalendarz","ile miesiecy",
            "Ile miesiecy ma rok?",
            {"A":"4","B":"7","C":"10","D":"12","E":"24"},"D"),
         gen(35,"v1","w3","3pkt","czas_kalendarz","ile tygodni rok",
            "Ile pelnych tygodni ma 365 dni (zwykly rok)?",
            {"A":"50","B":"52","C":"54","D":"60","E":"100"},"B"),
         orig(2012,8),
         orig(2013,16)],
        [orig(2013,18),
         gen(35,"v1","c1","5pkt","czas_kalendarz","ile dni od daty",
            "Od 15 marca do 1 kwietnia ile dni (marzec ma 31)?",
            {"A":"15","B":"16","C":"17","D":"31","E":"32"},"C")],
        [sol("gen-l35-v1-w1","Luty w zwyklym roku = 28 dni.","Dlugosc lutego.",["28 dni"],"A"),
         sol("gen-l35-v1-w2","Rok = 12 miesiecy.","Standard.",["12 miesiecy w roku"],"D"),
         sol("gen-l35-v1-w3","365:7 = 52 reszta 1.","Dzielenie.",["365:7 = 52 r.1, 52 pelne tygodnie"],"B"),
         sol("kangur-maluch-2012-8","15 marca 2012 (przestepny), kurczeta 20 dni temu.",
            "Liczenie wstecz w lutym (29 dni).",
            ["Od 15 marca - 14 dni = 1 marca","- 6 dni = 23 lutego","Hmm liczmy: 15 marca minus 20 dni. 15 - 15 dni = polowa lutego. 15 marca - 15 = 29 lutego (przestepny). - 5 wiecej = 24 lutego"],"D"),
         sol("kangur-maluch-2013-16","Daty: 20 lutego, 12 kwietnia, 12 maja, 25 maja. Najstarsza.",
            "Najwczesniejsza data = najstarsza.",
            ["Basia i Asia w tym samym miesiacu = maj (12 i 25 maja)","Asia i Cesia rozne miesiace, ten sam dzien = 12. Asia=12 maja, Cesia=12 kwietnia","Basia=25 maja, Dorotka=20 lutego","Najstarsza (najwczesniejsza data): Dorotka"],"D"),
         sol("kangur-maluch-2013-18","Niedzwiedz spal 3 tygodnie w grudniu (31 dni).",
            "Wyrazenie z odejmowaniem.",
            ["Grudzien ma 31 dni","Spal 3 tygodnie = 7*3 dni","Nie spal: 31 - 7*3 dni, w godzinach: (31 - 7*3) razy 24"],"B"),
         sol("gen-l35-v1-c1","Od 15 marca do 31 marca = 16 dni, plus 1 kwietnia = 17.",
            "Liczenie odstepu.",
            ["31 - 15 = 16 dni do konca marca","+ 1 dzien (1 kwietnia) = 17 dni"],"C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(35,"v2","w1","3pkt","czas_kalendarz","luty przestepny",
            "Ile dni ma luty w roku przestepnym?",
            {"A":"27","B":"28","C":"29","D":"30","E":"31"},"C"),
         gen(35,"v2","w2","3pkt","czas_kalendarz","najdluzsze miesiace",
            "Ktory miesiac NIE ma 31 dni?",
            {"A":"Styczen","B":"Marzec","C":"Maj","D":"Czerwiec","E":"Lipiec"},"D"),
         gen(35,"v2","w3","3pkt","czas_kalendarz","odstep w miesiacu",
            "Od 3 maja do 17 maja jest ile dni?",
            {"A":"13","B":"14","C":"15","D":"16","E":"17"},"B"),
         orig(2020,18),
         orig(2025,22)],
        [orig(2023,18),
         gen(35,"v2","c1","5pkt","czas_kalendarz","odstep przez miesiac",
            "Od 25 kwietnia do 10 maja ile dni (kwiecien ma 30)?",
            {"A":"14","B":"15","C":"16","D":"20","E":"30"},"B")],
        [sol("gen-l35-v2-w1","Luty w przestepnym = 29 dni.","Rok przestepny.",["29 dni w lutym co 4 lata"],"C"),
         sol("gen-l35-v2-w2","Czerwiec ma 30 dni.","Dlugosci miesiecy.",
            ["31 dni: I, III, V, VII, VIII, X, XII","30 dni: IV, VI, IX, XI","Czerwiec (VI) - 30 dni"],"D"),
         sol("gen-l35-v2-w3","Odstep w tym samym miesiacu = roznica.","Odejmowanie dat.",
            ["17 - 3 = 14 dni"],"B"),
         sol("kangur-maluch-2020-18","6 dzieci, urodziny w marcu, konkurs trzeci czwartek.",
            "Wszystkie urodziny w marcu - przed lub w dzien konkursu lub po.",
            ["Konkurs to dzien w marcu","Urodziny 14, 15, 20, 21, 22, 27 marca","Wszystkie 6 obchodzilo lub bedzie obchodzic"],"E"),
         sol("kangur-maluch-2025-22","Suma 4 dat na prostej kalendarza = 29.",
            "Analiza ukladu dat.",
            ["Suma 4 dat na pewnej prostej = 29","Po analizie roznych konfiguracji w kalendarzu","1. dzien tego miesiaca to czwartek"],"A"),
         sol("kangur-maluch-2023-18","Metro 6 stacji, ruch wahadlowy, 96. przystanek.",
            "Cykliczny ruch.",
            ["Z B przez C... do F i z powrotem","Cykl ma dlugosc 10 przystankow","96 mod 10 = 6, przystanek 6 = D"],"D"),
         sol("gen-l35-v2-c1","Od 25 kwietnia do konca + maj.","Odstep przez miesiac.",
            ["30 - 25 = 5 dni do konca kwietnia","+ 10 dni (do 10 maja) = 15 dni"],"B")]),
    [dict(q="Ile miesiecy ma rok?", choices={"A":"10","B":"12","C":"24"}, correct="B",
          explain="Rok = 12 miesiecy."),
     dict(q="Luty zwykle ma:", choices={"A":"28 dni","B":"30 dni","C":"31 dni"}, correct="A",
          explain="Luty 28 dni (29 w roku przestepnym)."),
     dict(q="Rok przestepny jest:",
          choices={"A":"Co rok","B":"Co 4 lata","C":"Co 10 lat"}, correct="B",
          explain="Rok przestepny co 4 lata.")])
LESSONS.append(l35)

# ====================== ZAPIS ======================
for les in LESSONS:
    with open(f"data/lessons/{les['id']}.json", "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
    print(f"{les['id']}: OK ({les['title']})")
print(f"DONE - {len(LESSONS)} lekcji")
