"""Blok C - lekcje 14-21 (Geometria plaska), v1 + v2, mix oryginalow + autorskich."""
import json

def orig(year, number):
    with open(f"data/parsed/{year}.json", encoding="utf-8") as f:
        d = json.load(f)
    for p in d["problems"]:
        if p["number"] == number:
            return p
    raise ValueError(f"No {year}#{number}")

def gen(lid, ver, sfx, diff, subtopic, statement, choices, correct, img=None):
    return dict(id=f"gen-l{lid}-{ver}-{sfx}", source=f"generated-l{lid}-{ver}-{sfx}",
                year=None, number=None, difficulty=diff, topic="geometria_plaska", subtopic=subtopic,
                statement=statement, hasImage=img is not None, imageNote=img, choices=choices, correct=correct)

def sol(pid, obs, strat, steps, ans, alt=None):
    return dict(problemId=pid, observation=obs, strategy=strat, steps=steps, answer=ans, alternative=alt)

def lesson(lid, number, title, minutes, intro, tool, trick, v1, v2, quiz):
    return dict(id=lid, number=number, block="Geometria plaska", blockCode="C",
                title=title, topic="geometria_plaska", estimatedMinutes=minutes,
                theory=dict(intro=intro, tool=tool, trick=trick),
                versions=[v1, v2], quiz=quiz)

def ver(vid, label, warmup, challenge, solutions):
    return dict(versionId=vid, label=label, warmup=warmup, challenge=challenge, solutions=solutions)

LESSONS = []

# ================= LEKCJA 14: Punkty, odcinki, proste =================
l14 = lesson("l14", 14, "Punkty, odcinki, proste, polproste", 14,
    "Bawiac sie patyczkami i kropkami, budujesz caly swiat geometrii. Punkt to malutkie miejsce. Odcinek to kawalek prostej z dwoma koncami. Prosta nie ma konca - ciagnie sie w obie strony bez konca. Polprosta ma jeden koniec, a druga strona biegnie w nieskonczonosc.",
    "Sztuczka 1: ODCINEK MA DWA KONCE. Liczac odcinki w figurze, szukaj par punktow polaczonych linia. Patrz uwaznie - jeden dlugi odcinek moze sie skladac z kilku krotszych.\n\nSztuczka 2: PUNKTY PRZECIECIA. Gdy dwie proste sie przecinaja, powstaje jeden punkt. Trzy proste moga dac do 3 punktow przeciec. Licz ostroznie.\n\nSztuczka 3: LICZ SYSTEMATYCZNIE. Liczac odcinki albo trojkaty na rysunku, idz po kolei: najpierw najmniejsze, potem zlozone z dwoch, potem z trzech. Nie skacz losowo.",
    "Kangur uwielbia zadania 'ile odcinkow' albo 'ile trojkatow'. Pulapka: uczniowie licza tylko najmniejsze figury i zapominaja o tych zlozonych z kilku czesci. Zawsze sprawdz: czy z dwoch malych odcinkow nie powstaje jeden wiekszy?",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(14,"v1","w1","3pkt","liczenie odcinkow",
            "Na prostej zaznaczono 4 punkty: A, B, C, D (w tej kolejnosci). Ile roznych odcinkow lacza pary tych punktow?",
            {"A":"3","B":"4","C":"5","D":"6","E":"8"},"D"),
         gen(14,"v1","w2","3pkt","punkty przeciecia",
            "Dwie proste przecinaja sie. Ile punktow przeciecia powstaje?",
            {"A":"0","B":"1","C":"2","D":"3","E":"4"},"B"),
         gen(14,"v1","w3","3pkt","odcinki w figurze",
            "Trojkat ma 3 wierzcholki. Ile odcinkow (bokow) lacza te wierzcholki?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         orig(2013,4),
         orig(2015,5)],
        [orig(2013,8),
         gen(14,"v1","c1","5pkt","liczenie odcinkow zlozonych",
            "Na prostej zaznaczono 5 punktow w rzedzie. Ile roznych odcinkow mozna wyznaczyc, biorac kazda pare punktow?",
            {"A":"5","B":"8","C":"10","D":"12","E":"15"},"C")],
        [sol("gen-l14-v1-w1","4 punkty, kazda para tworzy odcinek.","Liczenie par.",
            ["Pary: AB, AC, AD, BC, BD, CD","Razem 6 odcinkow"],"D"),
         sol("gen-l14-v1-w2","Dwie proste przecinaja sie w jednym miejscu.","Punkt przeciecia.",
            ["Dwie rozne proste przecinaja sie w jednym punkcie"],"B"),
         sol("gen-l14-v1-w3","Trojkat ma 3 boki.","Liczenie bokow.",
            ["Trojkat ma 3 wierzcholki i 3 boki"],"B"),
         sol("kangur-maluch-2013-4","Liczymy trojkaty systematycznie - male i zlozone.",
            "Systematyczne liczenie.",
            ["Najpierw najmniejsze trojkaty","Potem trojkaty zlozone z kilku malych","Razem wychodzi 10"],"C"),
         sol("kangur-maluch-2015-5","Laczymy co druga liczbe na okregu od 1.",
            "Sledzenie rysowanych odcinkow.",
            ["1, 3, 5, 7, 9, 2, 4, 6, 8 i powrot do 1","Powstaje gwiazda dziewiecioramienna"],"D"),
         sol("kangur-maluch-2013-8","Dopasowujemy odlamany kawalek do reszty lustra.",
            "Dopasowanie ksztaltu.",
            ["Krawedz pekniecia odlamanego kawalka pasuje do reszty","Wlasciwy kawalek to czesc C"],"C"),
         sol("gen-l14-v1-c1","5 punktow, kazda para to odcinek.","Liczenie par.",
            ["Pary z 5 punktow: 4+3+2+1 = 10","Razem 10 odcinkow"],"C")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(14,"v2","w1","3pkt","liczenie odcinkow",
            "Na prostej sa 3 punkty. Ile roznych odcinkow lacza pary tych punktow?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         gen(14,"v2","w2","3pkt","rodzaje linii",
            "Ktora linia ma DWA konce?",
            {"A":"Prosta","B":"Polprosta","C":"Odcinek","D":"Promien","E":"Zadna"},"C"),
         gen(14,"v2","w3","3pkt","punkty na polprostej",
            "Polprosta ma:",
            {"A":"Dwa konce","B":"Jeden koniec","C":"Zero koncow","D":"Trzy konce","E":"Cztery konce"},"B"),
         orig(2014,1),
         orig(2021,4)],
        [orig(2016,4),
         orig(2024,1)],
        [sol("gen-l14-v2-w1","3 punkty, kazda para tworzy odcinek.","Liczenie par.",
            ["Pary: AB, AC, BC","Razem 3 odcinki"],"B"),
         sol("gen-l14-v2-w2","Odcinek ma poczatek i koniec.","Definicje linii.",
            ["Prosta nie ma koncow","Polprosta ma jeden koniec","Odcinek ma dwa konce"],"C"),
         sol("gen-l14-v2-w3","Polprosta zaczyna sie w punkcie i biegnie bez konca.","Definicja polprostej.",
            ["Polprosta ma jeden koniec, druga strona biegnie w nieskonczonosc"],"B"),
         sol("kangur-maluch-2014-1","Szukamy fragmentu pasujacego do gwiazdy.","Dopasowanie fragmentu.",
            ["Fragment musi miec ramiona zgodne z gwiazda","Pasuje fragment B"],"B"),
         sol("kangur-maluch-2021-4","Szukamy fragmentu, ktory NIE pasuje do sloneczka.",
            "Eliminacja niepasujacych.",
            ["Cztery fragmenty pasuja do rysunku sloneczka","Fragment D nie pasuje"],"D"),
         sol("kangur-maluch-2016-4","Porownujemy karte wzorcowa z 5 wariantami.","Dopasowanie obrazu.",
            ["Karta wzorcowa ma okreslony uklad zamalowania","Taka sama jest karta E"],"E"),
         sol("kangur-maluch-2024-1","Szukamy kwadratu rozcietego na dwie ROZNE czesci.",
            "Sprawdzanie symetrii ciecia.",
            ["Ciecie po przekatnej daje dwie jednakowe czesci","Ciecie lamane daje dwie rozne czesci - kwadrat A"],"A")]),
    [dict(q="Ile koncow ma prosta?", choices={"A":"Zero","B":"Jeden","C":"Dwa"}, correct="A",
          explain="Prosta biegnie bez konca w obie strony - nie ma koncow."),
     dict(q="Ile odcinkow wyznaczaja 4 punkty na prostej?",
          choices={"A":"4","B":"6","C":"8"}, correct="B",
          explain="Kazda para punktow to odcinek: 6 par z 4 punktow."),
     dict(q="Liczac trojkaty w figurze najczesciej zapominamy o:",
          choices={"A":"Najmniejszych","B":"Zlozonych z kilku malych","C":"Kolorach"}, correct="B",
          explain="Trojkaty zlozone z 2-3 malych latwo przeoczyc.")])
LESSONS.append(l14)

# ================= LEKCJA 15: Katy =================
l15 = lesson("l15", 15, "Katy i ich rodzaje", 14,
    "Otwierasz drzwi - powstaje kat. Wskazowki zegara tworza kat. Kat to dwie polproste wychodzace z jednego punktu. Im szerzej je rozsuniesz, tym wiekszy kat. Geometria katow zaczyna sie od rozpoznawania, czy kat jest maly, prosty czy szeroki.",
    "Sztuczka 1: KAT PROSTY TO ROG KARTKI. Kazdy rog kartki to kat prosty. Kat mniejszy od prostego nazywamy ostrym, a wiekszy - rozwartym. Kat polpelny to prosta linia.\n\nSztuczka 2: PORÓWNUJ Z ROGIEM. Nie znasz miary kata? Przyloz w mysli rog kartki. Jezeli kat jest 'ciasniejszy' - ostry. Szerszy - rozwarty.\n\nSztuczka 3: KATY NA ZEGARZE. Wskazowki zegara tworza katy. Co godzine duza wskazowka przesuwa sie o pelne kolo. Miedzy sasiednimi cyframi jest zawsze taki sam kat.",
    "Kangur lubi katy w odbiciach i obrotach. Gdy figura sie obraca albo odbija w lustrze, katy NIE zmieniaja swojej miary - zmienia sie tylko ich polozenie. To klucz do zadan z lustrami i obracaniem.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(15,"v1","w1","3pkt","rozpoznanie kata prostego",
            "Kat prosty to taki, jaki tworzy:",
            {"A":"Rozwarte nozyczki","B":"Rog kartki","C":"Prosta linia","D":"Pelne kolo","E":"Czubek igly"},"B"),
         gen(15,"v1","w2","3pkt","kat ostry i rozwarty",
            "Kat mniejszy od kata prostego nazywamy:",
            {"A":"Ostrym","B":"Rozwartym","C":"Polpelnym","D":"Pelnym","E":"Prostym"},"A"),
         gen(15,"v1","w3","3pkt","katy na zegarze",
            "O godzinie 3:00 wskazowki zegara tworza kat:",
            {"A":"Ostry","B":"Prosty","C":"Rozwarty","D":"Polpelny","E":"Pelny"},"B"),
         orig(2022,8),
         orig(2013,3)],
        [orig(2016,10),
         gen(15,"v1","c1","5pkt","kat miedzy wskazowkami",
            "O godzinie 6:00 wskazowki zegara (godzinowa i minutowa) tworza kat:",
            {"A":"Ostry","B":"Prosty","C":"Rozwarty","D":"Polpelny","E":"Pelny"},"D")],
        [sol("gen-l15-v1-w1","Rog kartki to wzorzec kata prostego.","Porownanie z rogiem.",
            ["Kazdy rog prostokatnej kartki to kat prosty"],"B"),
         sol("gen-l15-v1-w2","Mniejszy od prostego = ostry.","Klasyfikacja katow.",
            ["Kat ostry jest mniejszy niz kat prosty"],"A"),
         sol("gen-l15-v1-w3","O 3:00 wskazowki sa pod katem rogu kartki.","Katy na zegarze.",
            ["Wskazowka godzinowa na 3, minutowa na 12","Tworza kat prosty"],"B"),
         sol("kangur-maluch-2022-8","Promien lasera odbija sie od luster.",
            "Sledzenie toru odbic.",
            ["Przy kazdym lustrze promien zmienia kierunek","Po przejsciu wszystkich luster trafia w punkt C"],"C"),
         sol("kangur-maluch-2013-3","Odbicie lustrzane zegara 15:00.",
            "Odbicie w pionowym lustrze.",
            ["Zegar 15:00 odbity w lustrze","Wskazowki odbijaja sie - obraz D"],"D"),
         sol("kangur-maluch-2016-10","Odbicie lustrzane pajacyka.",
            "Lustrzane odwrocenie obrazu.",
            ["Pajacyk w lustrze ma odbita prawa i lewa strone","Poprawne odbicie to E"],"E"),
         sol("gen-l15-v1-c1","O 6:00 wskazowki sa naprzeciw siebie.","Katy na zegarze.",
            ["Godzinowa na 6, minutowa na 12","Wskazowki tworza linie prosta - kat polpelny"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(15,"v2","w1","3pkt","kat rozwarty",
            "Kat wiekszy od kata prostego, ale mniejszy od polpelnego nazywamy:",
            {"A":"Ostrym","B":"Prostym","C":"Rozwartym","D":"Pelnym","E":"Zerowym"},"C"),
         gen(15,"v2","w2","3pkt","kat polpelny",
            "Kat polpelny wyglada jak:",
            {"A":"Rog kartki","B":"Prosta linia","C":"Czubek olowka","D":"Pelne kolo","E":"Kropka"},"B"),
         gen(15,"v2","w3","3pkt","katy w kwadracie",
            "Ile katow prostych ma kwadrat?",
            {"A":"1","B":"2","C":"3","D":"4","E":"0"},"D"),
         orig(2015,9),
         orig(2025,2)],
        [orig(2014,8),
         orig(2018,15)],
        [sol("gen-l15-v2-w1","Wiekszy od prostego, mniejszy od polpelnego = rozwarty.","Klasyfikacja.",
            ["Kat rozwarty jest miedzy prostym a polpelnym"],"C"),
         sol("gen-l15-v2-w2","Kat polpelny to wyprostowana linia.","Definicja kata polpelnego.",
            ["Dwie polproste tworza linie prosta"],"B"),
         sol("gen-l15-v2-w3","Kwadrat ma 4 rogi proste.","Katy w kwadracie.",
            ["Kazdy z 4 rogow kwadratu to kat prosty"],"D"),
         sol("kangur-maluch-2015-9","Parasol z napisem KANGAROO obrocony.",
            "Sledzenie obrotu napisu.",
            ["Napis dookola parasola zachowuje kolejnosc liter","Po obrocie poprawny obraz to E"],"E"),
         sol("kangur-maluch-2025-2","Wiatraczek obrocony - katy zachowane.",
            "Obrot tarczy.",
            ["Przy obrocie uklad trojkatow zachowuje swoje katy","Mozliwy obraz to B"],"B"),
         sol("kangur-maluch-2014-8","Bukiet kwiatow z drugiej strony okna - odbicie.",
            "Odbicie lustrzane.",
            ["Z drugiej strony szyby bukiet jest odbity lustrzanie","Poprawne odbicie to B"],"B"),
         sol("kangur-maluch-2018-15","Inwersja kolorow i obrot figury.",
            "Zamiana kolorow + obrot.",
            ["Bialy zamieniony na czarny i odwrotnie","Po obrocie poprawny obraz to D"],"D")]),
    [dict(q="Kat prosty jest jak:", choices={"A":"Rog kartki","B":"Prosta linia","C":"Czubek igly"},
          correct="A", explain="Rog prostokatnej kartki to wzorcowy kat prosty."),
     dict(q="O 6:00 wskazowki zegara tworza kat:",
          choices={"A":"Prosty","B":"Polpelny","C":"Ostry"}, correct="B",
          explain="Wskazowki sa naprzeciw siebie - tworza linie prosta, kat polpelny."),
     dict(q="Gdy figura sie obraca, jej katy:",
          choices={"A":"Zmieniaja miare","B":"Zostaja takie same","C":"Znikaja"}, correct="B",
          explain="Obrot zmienia tylko polozenie, nie miare katow.")])
LESSONS.append(l15)

# ================= LEKCJA 16: Trojkaty =================
l16 = lesson("l16", 16, "Trojkaty i ich rodzaje", 15,
    "Trojkat to najprostsza figura z bokami - tylko trzy. A jednak kryje mnostwo tajemnic. Trojkat rownoboczny ma wszystkie boki rowne. Rownoramienny ma dwa boki rowne. Prostokatny ma jeden kat prosty. Rozpoznawanie rodzajow trojkatow to podstawa geometrii Kangurka.",
    "Sztuczka 1: PATRZ NA BOKI I KATY. Rownoboczny - 3 rowne boki. Rownoramienny - 2 rowne boki. Prostokatny - jeden kat prosty (rog kartki).\n\nSztuczka 2: LICZ TROJKATY SYSTEMATYCZNIE. Na rysunku z liniami szukaj: najpierw male trojkaty, potem zlozone z 2, z 3, z 4 malych. Nie pomijaj duzych.\n\nSztuczka 3: TROJKAT W FIGURZE ZLOZONEJ. Duza figura czesto sklada sie z trojkatow. Podziel ja w mysli na trojkaty - latwiej policzyc pole albo elementy.",
    "Pulapka Kangurka: zadanie 'ile trojkatow' wyglada na 4 albo 5, ale poprawna odpowiedz to czesto 10 lub wiecej. Powod: trojkaty zlozone z kilku mniejszych. Zawsze sprawdzaj kombinacje - to one robia roznice.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(16,"v1","w1","3pkt","trojkat rownoboczny",
            "Trojkat, ktory ma wszystkie trzy boki rownej dlugosci, nazywamy:",
            {"A":"Prostokatnym","B":"Rownoramiennym","C":"Rownobocznym","D":"Roznobocznym","E":"Plaskim"},"C"),
         gen(16,"v1","w2","3pkt","trojkat prostokatny",
            "Trojkat prostokatny ma jeden kat:",
            {"A":"Ostry","B":"Prosty","C":"Rozwarty","D":"Polpelny","E":"Pelny"},"B"),
         gen(16,"v1","w3","3pkt","liczba bokow",
            "Ile bokow ma kazdy trojkat?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         orig(2015,10),
         orig(2014,3)],
        [orig(2012,9),
         orig(2019,10)],
        [sol("gen-l16-v1-w1","Wszystkie boki rowne = rownoboczny.","Klasyfikacja trojkatow.",
            ["Trojkat z 3 rownymi bokami to rownoboczny"],"C"),
         sol("gen-l16-v1-w2","Prostokatny ma kat prosty.","Definicja.",
            ["Trojkat prostokatny ma jeden kat prosty"],"B"),
         sol("gen-l16-v1-w3","Trojkat - trzy boki.","Liczba bokow.",
            ["Kazdy trojkat ma 3 boki"],"B"),
         sol("kangur-maluch-2015-10","Figure dzielimy na jednakowe trojkaty.",
            "Liczenie identycznych czesci.",
            ["Figura pocieta na jednakowe trojkaty","Wychodzi 16 trojkatow"],"E"),
         sol("kangur-maluch-2014-3","Porownujemy zestawy klockow domkow.",
            "Porownanie zestawow.",
            ["Domki o tym samym zestawie klockow trojkatnych i prostokatnych","Pasuja domki 1 i 4"],"D"),
         sol("kangur-maluch-2012-9","Ukladamy figury z kartonikow L.",
            "Sprawdzanie ulozenia.",
            ["Z kartonikow w ksztalcie L mozna ulozyc 3 z podanych figur"],"D"),
         sol("kangur-maluch-2019-10","Usuwamy jeden kartonik z figury z 5 kwadratow.",
            "Liczenie roznych figur.",
            ["Usuniecie roznych kartonikow daje rozne figury 4-kwadratowe","Mozna otrzymac 3 rozne figury"],"C")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(16,"v2","w1","3pkt","trojkat rownoramienny",
            "Trojkat, ktory ma dokladnie dwa boki rownej dlugosci, nazywamy:",
            {"A":"Rownobocznym","B":"Rownoramiennym","C":"Prostokatnym","D":"Pelnym","E":"Plaskim"},"B"),
         gen(16,"v2","w2","3pkt","liczba katow",
            "Ile katow ma trojkat?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         gen(16,"v2","w3","3pkt","liczenie trojkatow prostych",
            "Kwadrat przeciety jedna przekatna dzieli sie na ile trojkatow?",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"B"),
         orig(2014,17),
         orig(2025,8)],
        [orig(2013,17),
         gen(16,"v2","c1","5pkt","liczenie trojkatow w siatce",
            "Duzy trojkat podzielono liniami na 4 male jednakowe trojkaty. Ile wszystkich trojkatow (malych i zlozonych) widac na rysunku?",
            {"A":"4","B":"5","C":"6","D":"8","E":"10"},"B")],
        [sol("gen-l16-v2-w1","Dwa rowne boki = rownoramienny.","Klasyfikacja.",
            ["Trojkat z 2 rownymi bokami to rownoramienny"],"B"),
         sol("gen-l16-v2-w2","Trojkat ma 3 katy.","Liczba katow.",
            ["Kazdy trojkat ma 3 wierzcholki i 3 katy"],"B"),
         sol("gen-l16-v2-w3","Przekatna dzieli kwadrat na 2 trojkaty.","Podzial przekatna.",
            ["Jedna przekatna kwadratu tworzy 2 trojkaty prostokatne"],"B"),
         sol("kangur-maluch-2014-17","Szukamy polozenia konkretnego klocka w figurze.",
            "Dopasowanie klocka.",
            ["Figura ulozona z 4 klockow","Szukany klocek lezy w polozeniu C"],"C"),
         sol("kangur-maluch-2025-8","Ukladamy wiatraczek z 3 figur.",
            "Sprawdzanie ulozenia z trojkata, kwadratu i prostokata.",
            ["Trzy figury skladaja sie w jeden wzor","Poprawne ulozenie to C"],"C"),
         sol("kangur-maluch-2013-17","Ukladamy najmniejszy kwadrat z jednakowych figur.",
            "Liczenie potrzebnych figur.",
            ["Figura L z 4 kratek","Najmniejszy kwadrat wymaga 4 takich figur"],"C"),
         sol("gen-l16-v2-c1","Liczymy male trojkaty i duzy zlozony.","Systematyczne liczenie.",
            ["4 male trojkaty","1 duzy trojkat zlozony ze wszystkich","Razem 5 trojkatow"],"B")]),
    [dict(q="Trojkat z 3 rownymi bokami to:",
          choices={"A":"Rownoboczny","B":"Prostokatny","C":"Rownoramienny"}, correct="A",
          explain="Trzy rowne boki - trojkat rownoboczny."),
     dict(q="Ile katow prostych ma trojkat prostokatny?",
          choices={"A":"Zero","B":"Jeden","C":"Trzy"}, correct="B",
          explain="Trojkat prostokatny ma dokladnie jeden kat prosty."),
     dict(q="W zadaniu 'ile trojkatow' najczesciej zapominamy o:",
          choices={"A":"Malych","B":"Zlozonych z kilku","C":"Kolorach"}, correct="B",
          explain="Trojkaty zlozone z 2-3 malych latwo przeoczyc.")])
LESSONS.append(l16)

# ================= LEKCJA 17: Czworokaty =================
l17 = lesson("l17", 17, "Czworokaty: kwadrat, prostokat, trapez", 15,
    "Cztery boki - i juz mamy czworokat. Kwadrat ma wszystkie boki rowne i wszystkie katy proste. Prostokat ma katy proste, ale boki parami rowne. Trapez ma jedna pare bokow rownoleglych. Czworokaty sa wszedzie: kartka, okno, stol, ekran.",
    "Sztuczka 1: KWADRAT TO SZCZEGOLNY PROSTOKAT. Kwadrat ma wszystko co prostokat (4 katy proste) plus wszystkie boki rowne. Kazdy kwadrat jest prostokatem, ale nie odwrotnie.\n\nSztuczka 2: SKLADANIE FIGUR. Dwa jednakowe trojkaty prostokatne moga utworzyc kwadrat lub prostokat. Dwa kwadraty obok siebie - prostokat. Cwicz rozkladanie i skladanie.\n\nSztuczka 3: PRZECIWLEGLE BOKI. W prostokacie i kwadracie przeciwlegle boki sa rowne. Znajac dwa sasiednie boki, znasz wszystkie cztery.",
    "Kangur czesto pyta o skladanie kwadratu z czesci. Pamietaj: pole sie nie zmienia przy ukladaniu. Jezeli kawalki maja lacznie 16 kratek, zlozony kwadrat ma bok 4 (bo 4 razy 4 = 16). Liczba kratek zdradza bok.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(17,"v1","w1","3pkt","wlasnosci kwadratu",
            "Kwadrat ma wszystkie boki rowne i wszystkie katy:",
            {"A":"Ostre","B":"Proste","C":"Rozwarte","D":"Polpelne","E":"Rozne"},"B"),
         gen(17,"v1","w2","3pkt","prostokat - boki",
            "W prostokacie przeciwlegle boki sa:",
            {"A":"Rozne","B":"Rowne","C":"Zawsze dluzsze","D":"Zakrzywione","E":"Krotsze"},"B"),
         gen(17,"v1","w3","3pkt","liczba bokow czworokata",
            "Ile bokow ma kazdy czworokat?",
            {"A":"3","B":"4","C":"5","D":"6","E":"8"},"B"),
         orig(2023,4),
         orig(2025,14)],
        [orig(2018,12),
         orig(2013,15)],
        [sol("gen-l17-v1-w1","Kwadrat - rowne boki, kat prosty.","Wlasnosci kwadratu.",
            ["Kwadrat ma 4 katy proste"],"B"),
         sol("gen-l17-v1-w2","Przeciwlegle boki prostokata sa rowne.","Wlasnosci prostokata.",
            ["W prostokacie przeciwlegle boki maja te sama dlugosc"],"B"),
         sol("gen-l17-v1-w3","Czworokat - cztery boki.","Liczba bokow.",
            ["Kazdy czworokat ma 4 boki"],"B"),
         sol("kangur-maluch-2023-4","Skladamy kwadrat z dwoch kartonikow.",
            "Dopasowanie ksztaltow.",
            ["Dwa kartoniki musza sie uzupelnic w kwadrat bez nakladania","Pasuja kartoniki 2 i 4"],"D"),
         sol("kangur-maluch-2025-14","Czwarty kartonik kwadratu.",
            "Uzupelnienie kwadratu.",
            ["Trzy prostokatne kartoniki czesc kwadratu","Czwarta czesc to kartonik C"],"C"),
         sol("kangur-maluch-2018-12","Liczymy kawalki potrzebne do ulozenia figury.",
            "Liczenie kawalkow.",
            ["Figura lodki z dwoch rodzajow kawalkow","Potrzeba 7 kawalkow"],"C"),
         sol("kangur-maluch-2013-15","Dopasowujemy kawalek ukladanki do prostokata.",
            "Dopasowanie ksztaltu.",
            ["Kawalek musi uzupelnic figure do prostokata","Pasuje kawalek B"],"B")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(17,"v2","w1","3pkt","kwadrat a prostokat",
            "Ktore zdanie jest prawdziwe?",
            {"A":"Kazdy prostokat jest kwadratem","B":"Kazdy kwadrat jest prostokatem","C":"Kwadrat nie ma katow prostych","D":"Prostokat ma 3 boki","E":"Kwadrat ma 5 bokow"},"B"),
         gen(17,"v2","w2","3pkt","trapez",
            "Trapez to czworokat, ktory ma:",
            {"A":"Wszystkie boki rowne","B":"Jedna pare bokow rownoleglych","C":"Trzy boki","D":"Same katy ostre","E":"Piec wierzcholkow"},"B"),
         gen(17,"v2","w3","3pkt","skladanie kwadratu z kratek",
            "Z ilu kratek sklada sie kwadrat o boku 3 kratki?",
            {"A":"3","B":"6","C":"9","D":"12","E":"16"},"C"),
         orig(2020,4),
         orig(2020,15)],
        [orig(2012,2),
         gen(17,"v2","c1","5pkt","bok kwadratu z liczby kratek",
            "Z czesci o lacznie 36 kratkach ulozono kwadrat. Jaki bok ma ten kwadrat?",
            {"A":"4","B":"5","C":"6","D":"8","E":"9"},"C")],
        [sol("gen-l17-v2-w1","Kwadrat ma wszystko co prostokat i wiecej.","Zaleznosci figur.",
            ["Kwadrat ma 4 katy proste - jak prostokat","Kazdy kwadrat jest prostokatem"],"B"),
         sol("gen-l17-v2-w2","Trapez - jedna para bokow rownoleglych.","Definicja trapezu.",
            ["Trapez ma dokladnie jedna pare bokow rownoleglych"],"B"),
         sol("gen-l17-v2-w3","Kwadrat 3x3 kratki.","Liczenie kratek.",
            ["3 rzedy po 3 kratki = 9 kratek"],"C"),
         sol("kangur-maluch-2020-4","Ukladamy figure z 6 kartonikow.",
            "Sprawdzanie ulozenia.",
            ["Szesc kartonikow tworzy jedna figure","Poprawna figura to D"],"D"),
         sol("kangur-maluch-2020-15","Ukladamy wzor korony z pieciokatow.",
            "Sledzenie liczb na trojkatach.",
            ["Kartoniki stykaja sie trojkatami o tych samych liczbach","W szarym trojkacie wychodzi 2"],"B"),
         sol("kangur-maluch-2012-2","Szukamy rysunku z nierownymi polami.",
            "Porownanie pol zamalowanych.",
            ["Na czterech rysunkach pola zamalowane i niezamalowane sa rowne","Na rysunku E nie sa rowne"],"E"),
         sol("gen-l17-v2-c1","36 kratek tworzy kwadrat - szukamy boku.","Bok kwadratu z pola.",
            ["Bok razy bok = 36","6 razy 6 = 36, czyli bok 6"],"C")]),
    [dict(q="Czy kazdy kwadrat jest prostokatem?",
          choices={"A":"Tak","B":"Nie","C":"Tylko duzy"}, correct="A",
          explain="Kwadrat ma 4 katy proste - spelnia warunek prostokata."),
     dict(q="Trapez ma rownoleglych:",
          choices={"A":"Jedna pare bokow","B":"Wszystkie boki","C":"Zero bokow"}, correct="A",
          explain="Trapez ma dokladnie jedna pare bokow rownoleglych."),
     dict(q="Kwadrat z 25 kratek ma bok:",
          choices={"A":"4","B":"5","C":"6"}, correct="B",
          explain="5 razy 5 = 25, wiec bok ma 5 kratek.")])
LESSONS.append(l17)

# ================= LEKCJA 18: Obwod =================
l18 = lesson("l18", 18, "Obwod figur", 15,
    "Mrowka idzie dookola kartki i wraca do startu. Droga, ktora przeszla, to obwod. Obwod to suma dlugosci wszystkich bokow figury. Plot wokol ogrodu, ramka obrazka, listwa wokol stolu - to wszystko obwody.",
    "Sztuczka 1: OBWOD TO SUMA BOKOW. Po prostu dodaj dlugosci wszystkich bokow. Prostokat o bokach 5 i 3: obwod = 5 + 3 + 5 + 3 = 16.\n\nSztuczka 2: PROSTOKAT - SZYBKI WZOR. Obwod prostokata = 2 razy (dlugosc + szerokosc). Bo masz dwa dlugie boki i dwa krotkie.\n\nSztuczka 3: FIGURA ZLOZONA - PRZESUWAJ BOKI. W figurze schodkowej mozesz w mysli przesunac boki tak, by utworzyly prostokat. Obwod czesto wychodzi taki sam jak prostokata, ktory ja otacza.\n\nSztuczka 4: OBWOD NA KRATCE. Licz boczki kratek wzdluz brzegu figury. Kazdy bok kratki to jedna jednostka.",
    "Pulapka Kangurka: figura wycieta z prostokata moze miec TAKI SAM obwod jak caly prostokat. Wciecie 'do srodka' nie zmienia obwodu, jezeli brzeg idzie tymi samymi liniami. Zawsze przesuwaj boki w mysli, zanim zaczniesz dodawac.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(18,"v1","w1","3pkt","obwod prostokata",
            "Prostokat ma boki 6 cm i 4 cm. Ile wynosi jego obwod?",
            {"A":"10 cm","B":"20 cm","C":"24 cm","D":"14 cm","E":"16 cm"},"B"),
         gen(18,"v1","w2","3pkt","obwod kwadratu",
            "Kwadrat ma bok 7 cm. Ile wynosi jego obwod?",
            {"A":"14 cm","B":"21 cm","C":"28 cm","D":"49 cm","E":"35 cm"},"C"),
         gen(18,"v1","w3","3pkt","obwod trojkata",
            "Trojkat rownoboczny ma bok 5 cm. Ile wynosi jego obwod?",
            {"A":"10 cm","B":"15 cm","C":"20 cm","D":"25 cm","E":"5 cm"},"B"),
         orig(2019,16),
         orig(2021,15)],
        [orig(2019,20),
         orig(2018,23)],
        [sol("gen-l18-v1-w1","Obwod = suma bokow prostokata.","Wzor na obwod prostokata.",
            ["Obwod = 2 razy (6 + 4) = 2 razy 10 = 20 cm"],"B"),
         sol("gen-l18-v1-w2","Kwadrat - 4 rowne boki.","Obwod kwadratu.",
            ["Obwod = 4 razy 7 = 28 cm"],"C"),
         sol("gen-l18-v1-w3","Trojkat rownoboczny - 3 rowne boki.","Obwod trojkata.",
            ["Obwod = 3 razy 5 = 15 cm"],"B"),
         sol("kangur-maluch-2019-16","Ramka wokol kwadratowego obrazka.",
            "Wzor na liczbe plytek ramki.",
            ["Ramka wokol 10x10: 4 razy 10 + 4 = 44 plytki"],"C"),
         sol("kangur-maluch-2021-15","Szukamy dlugosci z wymiarow prostokatow.",
            "Roznice wymiarow.",
            ["Z ukladu prostokatow 32, 36, 48 cm","Szukana dlugosc to 20 cm"],"B"),
         sol("kangur-maluch-2019-20","Linia srodkiem zakrzywionego korytarza.",
            "Sumowanie dlugosci wzdluz linii.",
            ["Linia srodkowa biegnie przez zakrety korytarza","Jej dlugosc to 69 metrow"],"C"),
         sol("kangur-maluch-2018-23","Prostokat podzielony na kwadraty - skalowanie.",
            "Stosunki bokow kwadratow.",
            ["Prostokat z 7 kwadratow, 3 najmniejsze zacieniowane","Caly prostokat to 198 malych kwadratow"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(18,"v2","w1","3pkt","obwod prostokata",
            "Prostokat ma boki 8 cm i 5 cm. Ile wynosi jego obwod?",
            {"A":"13 cm","B":"26 cm","C":"40 cm","D":"18 cm","E":"21 cm"},"B"),
         gen(18,"v2","w2","3pkt","obwod kwadratu z obwodu",
            "Kwadrat ma obwod 24 cm. Jaki bok ma ten kwadrat?",
            {"A":"4 cm","B":"5 cm","C":"6 cm","D":"8 cm","E":"12 cm"},"C"),
         gen(18,"v2","w3","3pkt","obwod figury z kratek",
            "Prostokat na kratce ma 5 kratek dlugosci i 2 kratki szerokosci. Ile boczkow kratek ma jego obwod?",
            {"A":"10","B":"12","C":"14","D":"16","E":"20"},"C"),
         orig(2024,11),
         gen(18,"v2","w5","3pkt","obwod kwadratu",
            "Kwadrat ma bok 9 cm. Ile wynosi jego obwod?",
            {"A":"18 cm","B":"27 cm","C":"36 cm","D":"45 cm","E":"81 cm"},"C")],
        [orig(2025,17),
         orig(2025,24)],
        [sol("gen-l18-v2-w1","Obwod prostokata = 2 razy (dlugosc + szerokosc).","Wzor na obwod.",
            ["Obwod = 2 razy (8 + 5) = 2 razy 13 = 26 cm"],"B"),
         sol("gen-l18-v2-w2","Obwod kwadratu = 4 razy bok.","Odwrocenie wzoru.",
            ["Bok = obwod : 4 = 24 : 4 = 6 cm"],"C"),
         sol("gen-l18-v2-w3","Obwod = suma bokow prostokata.","Liczenie boczkow kratek.",
            ["Obwod = 2 razy (5 + 2) = 2 razy 7 = 14 boczkow"],"C"),
         sol("kangur-maluch-2024-11","Bok plytki kwadratowej z wymiarow plytki prostokatnej.",
            "Zaleznosc miedzy plytkami.",
            ["Plytka jasna 23 cm na 11 cm","Z ukladu plytek bok kwadratowej to 6 cm"],"D"),
         sol("gen-l18-v2-w5","Kwadrat - 4 rowne boki.","Obwod kwadratu.",
            ["Obwod = 4 razy 9 = 36 cm"],"C"),
         sol("kangur-maluch-2025-17","Wymiary 11 identycznych prostokatow.",
            "Podzial prostokata 100 na 60.",
            ["11 identycznych prostokatow w prostokacie 100 cm na 60 cm","Kazdy ma wymiary 12 cm na 40 cm"],"C"),
         sol("kangur-maluch-2025-24","Prostokat ciety na kwadrat.",
            "Roznica bokow prostokata i kwadratu.",
            ["Prostokat z dluzszym bokiem 27 cm pociety i zlozony w kwadrat","Krotszy bok prostokata jest o 6 cm krotszy od boku kwadratu"],"B")]),
    [dict(q="Obwod prostokata o bokach 3 i 7 to:",
          choices={"A":"10","B":"20","C":"21"}, correct="B",
          explain="Obwod = 2 razy (3 + 7) = 20."),
     dict(q="Obwod to:", choices={"A":"Suma bokow","B":"Liczba kratek w srodku","C":"Najdluzszy bok"},
          correct="A", explain="Obwod to suma dlugosci wszystkich bokow figury."),
     dict(q="Kwadrat o obwodzie 20 cm ma bok:",
          choices={"A":"4 cm","B":"5 cm","C":"10 cm"}, correct="B",
          explain="Bok = 20 : 4 = 5 cm.")])
LESSONS.append(l18)

# ================= LEKCJA 19: Pole =================
l19 = lesson("l19", 19, "Pole figur - liczenie kratek", 15,
    "Ile plytek pokrywa podloge? Ile kratek miesci sie w figurze? To pytania o pole. Pole mowi, jak duzo miejsca zajmuje figura w srodku. Obwod to droga dookola, a pole to powierzchnia wewnatrz.",
    "Sztuczka 1: POLE PROSTOKATA = DLUGOSC RAZY SZEROKOSC. Prostokat 5 na 3: pole = 5 razy 3 = 15 kratek.\n\nSztuczka 2: POLE KWADRATU = BOK RAZY BOK. Kwadrat o boku 4: pole = 4 razy 4 = 16.\n\nSztuczka 3: LICZ KRATKI - CALE I POLOWKI. W figurze na kratce policz cale kratki, potem polowki. Dwie polowki to jedna cala kratka.\n\nSztuczka 4: ROZKLADAJ FIGURE. Skomplikowana figura? Podziel ja na prostokaty, policz pole kazdego i dodaj. Albo: domysl prostokat i odejmij to, czego brakuje.",
    "Kangur lubi mieszac pole z obwodem. Zapamietaj roznice: obwod liczysz w jednostkach dlugosci (cm), pole w kratkach lub cm kwadratowych. Dwie figury moga miec ten sam obwod, ale rozne pola - i odwrotnie.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(19,"v1","w1","3pkt","pole prostokata",
            "Prostokat ma boki 6 kratek i 4 kratki. Ile kratek miesci jego pole?",
            {"A":"10","B":"20","C":"24","D":"12","E":"36"},"C"),
         gen(19,"v1","w2","3pkt","pole kwadratu",
            "Kwadrat ma bok 5 kratek. Ile wynosi jego pole?",
            {"A":"10","B":"15","C":"20","D":"25","E":"30"},"D"),
         gen(19,"v1","w3","3pkt","pole z polowek",
            "Figura sklada sie z 6 calych kratek i 4 polowek kratki. Ile wynosi jej pole?",
            {"A":"6","B":"7","C":"8","D":"10","E":"4"},"C"),
         orig(2020,5),
         orig(2024,3)],
        [orig(2014,12),
         orig(2014,23)],
        [sol("gen-l19-v1-w1","Pole prostokata = dlugosc razy szerokosc.","Wzor na pole.",
            ["Pole = 6 razy 4 = 24 kratki"],"C"),
         sol("gen-l19-v1-w2","Pole kwadratu = bok razy bok.","Wzor na pole kwadratu.",
            ["Pole = 5 razy 5 = 25 kratek"],"D"),
         sol("gen-l19-v1-w3","Dwie polowki to jedna cala kratka.","Liczenie calych i polowek.",
            ["6 calych kratek","4 polowki = 2 cale kratki","Razem 6 + 2 = 8"],"C"),
         sol("kangur-maluch-2020-5","Porownujemy pola zamalowane na 5 rysunkach.",
            "Liczenie zamalowanych kratek.",
            ["Na kazdym rysunku liczymy zamalowane kratki","Najwiekszy obszar ma rysunek E"],"E"),
         sol("kangur-maluch-2024-3","Liczymy pola niezamalowane po pokolorowaniu.",
            "Inkluzja-ekskluzja.",
            ["28 pol, pokolorowane 2 wiersze i 1 kolumna","Pokolorowane: 14 + 4 - 2 = 16","Niezamalowane: 28 - 16 = 12"],"C"),
         sol("kangur-maluch-2014-12","Uzupelniamy figure do rownego podzialu pola.",
            "Rownosc pol zamalowanego i niezamalowanego.",
            ["Kwadracik musi wyrownac pole zamalowane i niezamalowane","Pasuje kwadracik D"],"D"),
         sol("kangur-maluch-2014-23","Maksymalne zamalowanie bez calego kwadratu 2x2.",
            "Unikanie pelnego kwadratu 2x2.",
            ["Zamalowujemy jak najwiecej kratek","Nie moze powstac caly kwadrat 2x2","Maksymalnie 20 kratek"],"C")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(19,"v2","w1","3pkt","pole prostokata",
            "Prostokat ma boki 7 kratek i 3 kratki. Ile wynosi jego pole?",
            {"A":"10","B":"14","C":"21","D":"24","E":"30"},"C"),
         gen(19,"v2","w2","3pkt","pole kwadratu",
            "Kwadrat ma bok 6 kratek. Ile wynosi jego pole?",
            {"A":"12","B":"24","C":"30","D":"36","E":"42"},"D"),
         gen(19,"v2","w3","3pkt","pole figury zlozonej",
            "Figura sklada sie z dwoch prostokatow: jeden 3 na 2 kratki, drugi 4 na 2 kratki. Ile wynosi jej pole razem?",
            {"A":"10","B":"12","C":"14","D":"16","E":"20"},"C"),
         orig(2024,4),
         orig(2012,7)],
        [orig(2022,13),
         orig(2013,22)],
        [sol("gen-l19-v2-w1","Pole = dlugosc razy szerokosc.","Wzor na pole prostokata.",
            ["Pole = 7 razy 3 = 21 kratek"],"C"),
         sol("gen-l19-v2-w2","Pole kwadratu = bok razy bok.","Wzor na pole.",
            ["Pole = 6 razy 6 = 36 kratek"],"D"),
         sol("gen-l19-v2-w3","Dwa prostokaty - liczymy pole kazdego.","Rozkladanie figury.",
            ["Pierwszy: 3 razy 2 = 6","Drugi: 4 razy 2 = 8","Razem 6 + 8 = 14"],"C"),
         sol("kangur-maluch-2024-4","Liczymy szare plytki pod plakatem.",
            "Liczenie zakrytych plytek.",
            ["Plakat zakrywa fragment szachownicy plytek","Pod plakatem jest 21 szarych plytek"],"B"),
         sol("kangur-maluch-2012-7","Liczymy czarne plytki, ktore odpadly.",
            "Liczenie elementow wzoru.",
            ["Z regularnego wzoru szachownicy odpadlo kilka plytek","Czarnych plytek odpadlo 9"],"A"),
         sol("kangur-maluch-2022-13","Liczymy kropki na zagietym dywanie.",
            "Liczenie elementow przy zagieciu.",
            ["Dywan kwadratowy z kropkami w 2 rzedach przy kazdym boku","Wszystkich kropek jest 44"],"D"),
         sol("kangur-maluch-2013-22","Liczymy ksiezyce na zwinietym dywanie.",
            "Liczenie elementow naprzemiennego wzoru.",
            ["Dywan z naprzemiennymi kwadratami ksiezyc i slonce","Ksiezycow jest 63"],"D")]),
    [dict(q="Pole prostokata 4 na 5 to:",
          choices={"A":"9","B":"18","C":"20"}, correct="C",
          explain="Pole = 4 razy 5 = 20."),
     dict(q="Pole mierzy:", choices={"A":"Droge dookola","B":"Powierzchnie w srodku","C":"Najdluzszy bok"},
          correct="B", explain="Pole to powierzchnia wewnatrz figury."),
     dict(q="Cztery polowki kratki to:",
          choices={"A":"1 cala kratka","B":"2 cale kratki","C":"4 cale kratki"}, correct="B",
          explain="Dwie polowki = 1 cala, cztery polowki = 2 cale kratki.")])
LESSONS.append(l19)

# ================= LEKCJA 20: Symetria =================
l20 = lesson("l20", 20, "Symetria osiowa", 14,
    "Zloz kartke na pol i wytnij ksztalt - po rozlozeniu obie polowy sa takie same. To symetria osiowa. Linia zgiecia to os symetrii. Motyl, litera A, serce - wszystkie maja os symetrii. Jedna polowa jest lustrzanym odbiciem drugiej.",
    "Sztuczka 1: OS SYMETRII TO LINIA ZGIECIA. Jezeli po zgieciu wzdluz linii obie czesci sie pokrywaja - to os symetrii. Kwadrat ma 4 osie, prostokat 2, kolo nieskonczenie wiele.\n\nSztuczka 2: ODBICIE ZAMIENIA PRAWO I LEWO. W lustrze (i przy odbiciu wzgledem osi) prawa strona staje sie lewa. Litera 'b' odbita to 'd'. Patrz na to, co bylo z prawej - bedzie z lewej.\n\nSztuczka 3: WYCINANKA Z ZLOZONEJ KARTKI. Gdy tniesz zlozona kartke, otwor pojawi sie symetrycznie po obu stronach osi. Zloz dwa razy - dziura powtorzy sie 4 razy.",
    "Kangur uwielbia zadania z lustrem i skladaniem kartki. Klucz: odbicie NIE obraca figury - ono ja przerzuca jak strone w ksiazce. Litery i cyfry niesymetryczne (jak 3, 7, F) zmieniaja sie nie do poznania. Zawsze wyobraz sobie prawdziwe lustro.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(20,"v1","w1","3pkt","os symetrii kwadratu",
            "Ile osi symetrii ma kwadrat?",
            {"A":"1","B":"2","C":"3","D":"4","E":"8"},"D"),
         gen(20,"v1","w2","3pkt","os symetrii prostokata",
            "Ile osi symetrii ma prostokat (nie bedacy kwadratem)?",
            {"A":"0","B":"1","C":"2","D":"3","E":"4"},"C"),
         gen(20,"v1","w3","3pkt","litera symetryczna",
            "Ktora z liter ma pionowa os symetrii?",
            {"A":"F","B":"A","C":"R","D":"L","E":"G"},"B"),
         orig(2018,5),
         orig(2019,4)],
        [orig(2019,14),
         orig(2015,23)],
        [sol("gen-l20-v1-w1","Kwadrat - 4 osie symetrii.","Liczenie osi.",
            ["2 osie przez srodki bokow, 2 osie przez przekatne","Razem 4 osie"],"D"),
         sol("gen-l20-v1-w2","Prostokat - 2 osie symetrii.","Liczenie osi.",
            ["Osie przez srodki przeciwleglych bokow","Razem 2 osie (przekatne nie sa osiami)"],"C"),
         sol("gen-l20-v1-w3","Litera A ma pionowa os symetrii.","Sprawdzanie symetrii liter.",
            ["Litera A zlozona w pionie - obie polowy sie pokrywaja"],"B"),
         sol("kangur-maluch-2018-5","Kartka zlozona na pol, wyciety ksztalt.",
            "Symetria osiowa wycinanki.",
            ["Po rozlozeniu wyciety ksztalt jest symetryczny","Poprawny obraz to B"],"B"),
         sol("kangur-maluch-2019-4","Ksiazeczka z okienkami zlozona na pol.",
            "Sledzenie pojazdow widocznych w okienkach.",
            ["Po zlozeniu okienka pokrywaja okreslone pojazdy","Widac samochod, ciezarowke i traktor"],"E"),
         sol("kangur-maluch-2019-14","Plecionka odwrocona na druga strone.",
            "Odbicie wzoru.",
            ["Po odwroceniu wzor plecionki sie odbija","Poprawny obraz to B"],"B"),
         sol("kangur-maluch-2015-23","Nakladanie przezroczystych arkuszy.",
            "Obroty i nakladanie.",
            ["Arkusze mozna obracac, ale nie odwracac","Maksymalnie widac 7 czarnych kwadracikow"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(20,"v2","w1","3pkt","os symetrii kola",
            "Ile osi symetrii ma kolo?",
            {"A":"1","B":"2","C":"4","D":"8","E":"Nieskonczenie wiele"},"E"),
         gen(20,"v2","w2","3pkt","figura bez osi symetrii",
            "Ktora figura zwykle NIE ma osi symetrii?",
            {"A":"Kwadrat","B":"Kolo","C":"Rownolegloboik pochylony","D":"Trojkat rownoboczny","E":"Prostokat"},"C"),
         gen(20,"v2","w3","3pkt","odbicie cyfry",
            "Cyfra odbita w pionowym lustrze - ktora wyglada tak samo?",
            {"A":"2","B":"3","C":"8","D":"7","E":"5"},"C"),
         orig(2023,6),
         orig(2023,8)],
        [orig(2022,22),
         orig(2020,9)],
        [sol("gen-l20-v2-w1","Kolo ma nieskonczenie wiele osi symetrii.","Osie symetrii kola.",
            ["Kazda srednica kola jest osia symetrii","Jest ich nieskonczenie wiele"],"E"),
         sol("gen-l20-v2-w2","Pochylony rownolegloboik nie ma osi symetrii.","Sprawdzanie symetrii.",
            ["Kwadrat, kolo, trojkat rownoboczny i prostokat maja osie","Pochylony rownolegloboik - nie ma"],"C"),
         sol("gen-l20-v2-w3","Cyfra 8 jest symetryczna w pionie.","Sprawdzanie symetrii cyfr.",
            ["Cyfra 8 po odbiciu w pionowym lustrze wyglada tak samo"],"C"),
         sol("kangur-maluch-2023-6","Folia zlozona na pol - widok cyfr.",
            "Nakladanie polowek folii.",
            ["Po zlozeniu gornej czesci na dolna cyfry sie nakladaja","Poprawny widok to D"],"D"),
         sol("kangur-maluch-2023-8","Nakladanie polkola i cwiartki na czarne kolo.",
            "Eliminacja niemozliwego widoku.",
            ["Szare polkole i biala cwiartka na czarnym kole","Niemozliwy jest widok E"],"E"),
         sol("kangur-maluch-2022-22","Zwijanie gasienicy Hulajkula.",
            "Sledzenie sasiedztwa kulek.",
            ["Kulki sasiednie w rozwinietej musza sasiadowac w zwinietej","Poprawny obraz to A"],"A"),
         sol("kangur-maluch-2020-9","Kolorowanie obszarow trzema kolorami.",
            "Liczenie obszarow jednego koloru.",
            ["Sasiednie obszary musza miec rozne kolory","Zewnetrzny pierscien czerwony","Czerwonych obszarow jest 3"],"C")]),
    [dict(q="Ile osi symetrii ma kwadrat?",
          choices={"A":"2","B":"4","C":"8"}, correct="B",
          explain="Kwadrat ma 4 osie: 2 przez boki, 2 przez przekatne."),
     dict(q="Odbicie w lustrze zamienia:",
          choices={"A":"Gore z dolem","B":"Prawo z lewem","C":"Nic"}, correct="B",
          explain="Odbicie wzgledem pionowej osi zamienia prawa strone z lewa."),
     dict(q="Prostokat (nie kwadrat) ma osi symetrii:",
          choices={"A":"2","B":"4","C":"0"}, correct="A",
          explain="Prostokat ma 2 osie - przez srodki przeciwleglych bokow.")])
LESSONS.append(l20)

# ================= LEKCJA 21: Tangram =================
l21 = lesson("l21", 21, "Tangram i ukladanie figur", 16,
    "Tangram to starochinska ukladanka - z kilku prostych ksztaltow ukladasz zwierzeta, ludzi, domy. Geometria ukladanek uczy najwazniejszej rzeczy: jak rozkladac i skladac figury. To umiejetnosc, ktora rozwiazuje setki zadan Kangurka.",
    "Sztuczka 1: POLE SIE NIE ZMIENIA. Gdy ukladasz figure z kawalkow, ich laczne pole jest zawsze takie samo. Jezeli kawalki maja 12 kratek, gotowa figura tez ma 12 kratek.\n\nSztuczka 2: OBRACAJ I ODBIJAJ W MYSLI. Kawalek mozna obrocic albo odbic, by pasowal. Wyobraz sobie, jak wyglada po obroceniu, zanim go 'polozysz'.\n\nSztuczka 3: ZACZNIJ OD NAJWIEKSZEGO KAWALKA. Ukladajac, najpierw umiesc najwiekszy element - on najbardziej ogranicza mozliwosci. Mniejsze dopasujesz wokol niego.\n\nSztuczka 4: LICZ KRATKI BRZEGOWE. Sprawdzajac, czy kawalek pasuje, policz kratki wzdluz krawedzi - musza sie zgadzac z luka, ktora wypelniasz.",
    "Kangur stawia pulapki w zadaniach 'czy da sie ulozyc'. Sprawdz najpierw POLE - jezeli kawalki maja inne laczne pole niz figura docelowa, odpowiedz brzmi 'nie da sie' bez zadnego ukladania. Pole to pierwszy i najszybszy test.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(21,"v1","w1","3pkt","pole przy ukladaniu",
            "Z kawalkow o lacznym polu 16 kratek ulozono kwadrat. Jakie pole ma ten kwadrat?",
            {"A":"4","B":"8","C":"12","D":"16","E":"32"},"D"),
         gen(21,"v1","w2","3pkt","skladanie kwadratu z trojkatow",
            "Ile jednakowych trojkatow prostokatnych potrzeba, by zlozyc jeden kwadrat (najprosciej)?",
            {"A":"1","B":"2","C":"3","D":"5","E":"6"},"B"),
         gen(21,"v1","w3","3pkt","obracanie kawalka",
            "Kawalek ukladanki, ktory nie pasuje, czesto wystarczy:",
            {"A":"Rozciac","B":"Obrocic lub odbic","C":"Wyrzucic","D":"Pomalowac","E":"Zgubic"},"B"),
         orig(2019,9),
         orig(2020,13)],
        [orig(2015,17),
         orig(2020,22)],
        [sol("gen-l21-v1-w1","Pole nie zmienia sie przy ukladaniu.","Zachowanie pola.",
            ["Kawalki maja 16 kratek","Zlozony kwadrat tez ma pole 16"],"D"),
         sol("gen-l21-v1-w2","Dwa trojkaty prostokatne tworza kwadrat.","Skladanie figur.",
            ["Dwa jednakowe trojkaty prostokatne zlozone wzdluz przeciwprostokatnej daja kwadrat"],"B"),
         sol("gen-l21-v1-w3","Obrot lub odbicie czesto dopasowuje kawalek.","Obracanie kawalkow.",
            ["Kawalek mozna obrocic albo odbic, by pasowal"],"B"),
         sol("kangur-maluch-2019-9","Rozpoznajemy wycinek z planszy 4x4.",
            "Dopasowanie wycinka.",
            ["Prostokat 1x2 wyciety z planszy z symbolami","Pasuje wycinek karo-gwiazda"],"D"),
         sol("kangur-maluch-2020-13","Maksymalne pokrycie paska kartonikami.",
            "Liczenie kartonikow.",
            ["Kartoniki ukladane bez nakladania i wystawania","Najwiecej mozna uzyc 4 kartonikow"],"B"),
         sol("kangur-maluch-2015-17","Podzial figury na 3 identyczne czesci.",
            "Szukanie ksztaltu czesci.",
            ["Figura dzieli sie na 3 jednakowe czesci","Poprawny ksztalt to D"],"D"),
         sol("kangur-maluch-2020-22","Figura, ktorej nie da sie pociac na 3 rozne czesci.",
            "Sprawdzanie mozliwosci podzialu.",
            ["Cztery figury da sie pociac na 3 rozne czesci po 5 kratek","Figury D nie da sie tak pociac"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(21,"v2","w1","3pkt","test pola",
            "Kawalki maja laczne pole 10 kratek. Czy da sie z nich ulozyc kwadrat 3x3 (9 kratek)?",
            {"A":"Tak","B":"Nie - pola sie nie zgadzaja","C":"Tylko po obroceniu","D":"Tylko po odbiciu","E":"Zawsze"},"B"),
         gen(21,"v2","w2","3pkt","skladanie prostokata",
            "Dwa jednakowe kwadraty polozone obok siebie tworza:",
            {"A":"Trojkat","B":"Prostokat","C":"Kolo","D":"Wieksze kwadrat","E":"Pieciokat"},"B"),
         gen(21,"v2","w3","3pkt","kolejnosc ukladania",
            "Ukladajac figure z kawalkow, najlepiej zaczac od:",
            {"A":"Najmniejszego kawalka","B":"Najwiekszego kawalka","C":"Srodka","D":"Kolorowych","E":"Brzegow"},"B"),
         orig(2023,9),
         orig(2018,10)],
        [orig(2013,12),
         orig(2015,15)],
        [sol("gen-l21-v2-w1","Najpierw sprawdz pole.","Test pola.",
            ["Kawalki maja 10 kratek, kwadrat 3x3 ma 9","Pola sie nie zgadzaja - nie da sie"],"B"),
         sol("gen-l21-v2-w2","Dwa kwadraty obok siebie = prostokat.","Skladanie figur.",
            ["Dwa jednakowe kwadraty obok siebie tworza prostokat"],"B"),
         sol("gen-l21-v2-w3","Najwiekszy kawalek najbardziej ogranicza.","Strategia ukladania.",
            ["Najwiekszy kawalek umieszczamy pierwszy - reszte dopasowujemy wokol"],"B"),
         sol("kangur-maluch-2023-9","Ktory kartonik przykryje czarne kolko.",
            "Sledzenie polozenia kartonikow.",
            ["Figure przykrywamy 5 kartonikami","Czarne kolko przykryje kartonik E"],"E"),
         sol("kangur-maluch-2018-10","Ukladanie wzorow z kartonikow.",
            "Sprawdzanie ulozen.",
            ["Wzory ukladane z jednakowych kartonikow bez nakladania","Da sie ulozyc 3 z 5 wzorow"],"C"),
         sol("kangur-maluch-2013-12","Ruch po siatce ze skretami.",
            "Sledzenie trasy Ani.",
            ["Ania skreca: prawo, lewo, lewo, prawo, lewo, lewo","Konczy wedrowke przy obrazku B"],"B"),
         sol("kangur-maluch-2015-15","Ruch po alejkach parku ze skretami.",
            "Sledzenie trasy roweru.",
            ["Pawel skreca na przemian prawo, lewo...","Nie przejedzie kolo znaku C"],"C")]),
    [dict(q="Kawalki maja 20 kratek. Zlozona figura ma pole:",
          choices={"A":"10","B":"20","C":"40"}, correct="B",
          explain="Pole sie nie zmienia - zlozona figura ma 20 kratek."),
     dict(q="Pierwszy test 'czy da sie ulozyc' to:",
          choices={"A":"Sprawdzic pole","B":"Sprawdzic kolory","C":"Zgadnac"}, correct="A",
          explain="Jezeli pola sie nie zgadzaja, nie da sie - bez ukladania."),
     dict(q="Ukladanie zaczynamy od:",
          choices={"A":"Najwiekszego kawalka","B":"Najmniejszego","C":"Srodka"}, correct="A",
          explain="Najwiekszy kawalek najbardziej ogranicza - umieszczamy go pierwszy.")])
LESSONS.append(l21)

# ================= ZAPIS =================
for les in LESSONS:
    with open(f"data/lessons/{les['id']}.json", "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
    print(f"{les['id']}: OK ({les['title']})")
print("DONE - Blok C")
