"""Bloki G (Logika) i H (Kombinatoryka), v1+v2, max oryginalow.
WSZYSTKIE autorskie odpowiedzi sprawdzone matematycznie."""
import json

def orig(year, number):
    with open(f"data/parsed/{year}.json", encoding="utf-8") as f:
        d = json.load(f)
    for p in d["problems"]:
        if p["number"] == number:
            return p
    raise ValueError(f"No {year}#{number}")

def gen(lid, ver, sfx, diff, topic, subtopic, statement, choices, correct):
    return dict(id=f"gen-l{lid}-{ver}-{sfx}", source=f"generated-l{lid}-{ver}-{sfx}",
                year=None, number=None, difficulty=diff, topic=topic, subtopic=subtopic,
                statement=statement, hasImage=False, imageNote=None, choices=choices, correct=correct)

def sol(pid, obs, strat, steps, ans, alt=None):
    return dict(problemId=pid, observation=obs, strategy=strat, steps=steps, answer=ans, alternative=alt)

def lesson(lid, number, block, blockCode, title, topic, minutes, intro, tool, trick, v1, v2, quiz):
    return dict(id=lid, number=number, block=block, blockCode=blockCode,
                title=title, topic=topic, estimatedMinutes=minutes,
                theory=dict(intro=intro, tool=tool, trick=trick),
                versions=[v1, v2], quiz=quiz)

def ver(vid, label, warmup, challenge, solutions):
    return dict(versionId=vid, label=label, warmup=warmup, challenge=challenge, solutions=solutions)

# Pomocniczy stub-solution dla originalow (oryginalowe rozw. juz w v1 byly podane gdziekolwiek - tu wystarczy krotki)
def osol(pid, summary, ans):
    return dict(problemId=pid, observation="Oryginalne zadanie Kangurka.",
                strategy=summary, steps=[summary, "Poprawna odpowiedz: "+ans], answer=ans, alternative=None)

LESSONS = []

# ============== BLOK G: LOGIKA ==============

# === LEKCJA 36: Prawda/falsz ===
# Autorskie sprawdzone:
# w1: "Wszystkie psy szczekaja. Z faktu ze 'Burek jest psem' wynika ze:" → Burek szczeka. A
# w2: "Liczba 15 jest podzielna przez 5. Prawda czy falsz?" - 15:5=3, prawda. A
# w3: "Wszystkie kwadraty maja 4 boki. Trojkat ma 4 boki?" - nie, 3. B
l36 = lesson("l36", 36, "Logika i myslenie", "G", "Prawda czy falsz", "logika", 14,
    "Detektyw matematyczny czyta zdanie i pyta: 'Czy to prawda?' Logika to umiejetnosc oceniania, czy cos jest prawda, na podstawie znanych faktow. Kangur lubi takie zadania - testuja umiejetnosc precyzyjnego myslenia.",
    "Sztuczka 1: KONTRPRZYKLAD OBALA 'WSZYSTKIE'. Jezeli ktos mowi 'wszystkie kangury sa szare' - wystarczy znalezc JEDNEGO zielonego, by zdanie bylo falszywe.\n\nSztuczka 2: 'ISTNIEJE' WYMAGA TYLKO JEDNEGO. Zdanie 'istnieje liczba parzysta wieksza od 10' jest prawdziwe, bo np. 12.\n\nSztuczka 3: NEGACJA ZAMIENIA WSZYSTKIE/JEST. Negacja 'wszystkie kangury sa szare' to 'istnieje kangur, ktory NIE jest szary'.\n\nSztuczka 4: SPRAWDZAJ KAZDE ZDANIE OSOBNO. Gdy zadanie pyta 'ktore zdanie jest falszywe', oceniaj kazde po kolei, nie odgaduj.",
    "Pulapka Kangurka: zdania ze slowem 'wszystkie' lub 'zaden'. Jezeli choc jeden przyklad zaprzecza - cale zdanie falszywe. Ale 'niektore' wystarczy jeden przyklad potwierdzajacy.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(36,"v1","w1","3pkt","logika","ocena zdania",
            "Wszystkie psy szczekaja. Burek jest psem. Co z tego wynika?",
            {"A":"Burek szczeka","B":"Burek nie szczeka","C":"Burek miauczy","D":"Burek to kot","E":"Nie wiadomo"},"A"),
         gen(36,"v1","w2","3pkt","logika","prawda/falsz - dzielnik",
            "Liczba 15 jest podzielna przez 5. Czy to prawda?",
            {"A":"Tak","B":"Nie","C":"Czasem","D":"Tylko parzysta","E":"Nie wiadomo"},"A"),
         gen(36,"v1","w3","3pkt","logika","kontrprzyklad",
            "Wszystkie kwadraty maja 4 boki. Czy trojkat ma 4 boki?",
            {"A":"Tak","B":"Nie","C":"Czasem","D":"Tylko duzy","E":"Cztery boki ma kwadrat"},"B"),
         orig(2013,7),
         orig(2019,8)],
        [orig(2018,13),
         orig(2014,21)],
        [sol("gen-l36-v1-w1","Z 'wszystkie' wynika dla kazdego elementu.","Wnioskowanie.",
            ["Wszystkie psy szczekaja","Burek jest psem","Wniosek: Burek szczeka"],"A"),
         sol("gen-l36-v1-w2","15:5=3 - dzieli sie bez reszty.","Sprawdzenie podzielnosci.",
            ["15 : 5 = 3","Bez reszty - 15 jest podzielne przez 5"],"A"),
         sol("gen-l36-v1-w3","Trojkat ma 3 boki, nie 4.","Sprawdzenie faktu.",
            ["Trojkat ma 3 boki","Zdanie 'wszystkie kwadraty maja 4 boki' nie mowi nic o trojkatach"],"B"),
         osol("kangur-maluch-2013-7","Liczba 325: 3+2+5=10 - sprawdzamy zdania. Suma 10 - prawda. Cyfry rozne - tak. Cyfra jednosci 5 - tak. Wszystkie cyfry nieparzyste - 2 jest parzysta! Emil sklamal.","E"),
         osol("kangur-maluch-2019-8","Asia=Natalka, kazda <12, razem >20. 2x<24 ale 2x>20. x=11 (jedyna mozliwosc, bo x calkowite).","E"),
         osol("kangur-maluch-2018-13","8 kwiatow. Motyle = 2*wazki. Bez owada < 4. Wzory: wazki=2, motyle=4, bez owada=2. Sprawdz: 2+4+2=8 OK.","C"),
         osol("kangur-maluch-2014-21","Slonce poprzedzone 3 deszczowymi. 6 dzien po deszczowym - deszczowy. Po analizie - mozna przewidziec 5 dni od jutra.","D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(36,"v2","w1","3pkt","logika","prawda zdan",
            "Liczba 7 jest pierwsza. Liczba 8 jest pierwsza. Ktora z dwoch jest pierwsza?",
            {"A":"Tylko 7","B":"Tylko 8","C":"Obie","D":"Zadna","E":"Nie wiadomo"},"A"),
         gen(36,"v2","w2","3pkt","logika","ocena nierownosci",
            "Zdanie: '10 + 5 > 12'. Czy prawdziwe?",
            {"A":"Tak","B":"Nie","C":"Czasem","D":"Tylko z nawiasem","E":"Nie wiadomo"},"A"),
         gen(36,"v2","w3","3pkt","logika","negacja",
            "Negacja zdania 'wszystkie koty mruczą' to:",
            {"A":"Wszystkie koty nie mrucza","B":"Istnieje kot, ktory nie mruczy","C":"Zaden kot nie mruczy","D":"Wszystkie psy mrucza","E":"Niektore kota mrucza"},"B"),
         orig(2014,7),
         orig(2024,10)],
        [orig(2019,7),
         orig(2024,22)],
        [sol("gen-l36-v2-w1","Liczba pierwsza dzieli sie tylko przez 1 i siebie. 7 jest pierwsza, 8=2*4.","Sprawdzenie pierwszosci.",
            ["7: dzielniki 1 i 7 - pierwsza","8: dzielniki 1,2,4,8 - nie pierwsza","Tylko 7"],"A"),
         sol("gen-l36-v2-w2","10+5=15, 15>12 prawda.","Sprawdzenie nierownosci.",["15 > 12 - prawda"],"A"),
         sol("gen-l36-v2-w3","Negacja 'wszystkie X' = 'istnieje X ktore nie...'","Logika negacji.",
            ["Negacja 'wszystkie' to 'istnieje co najmniej jeden, ktory nie'"],"B"),
         osol("kangur-maluch-2014-7","Adam<Marcin, Adam>Zuzia. Dana>Marcin, Dana<Lusia. Najwiecej: Lusia>Dana>Marcin>Adam>Zuzia.","E"),
         osol("kangur-maluch-2024-10","Franek lubi tylko wisnie. Tadzio lubi banan (po przydziale wisni). Kajtek - truskawka. Alicja - gruszka. Jozek - jablko (zostalo).","A"),
         osol("kangur-maluch-2019-7","2 czerwone (2h kazda) + 3 biale (1h kazda) palone razem. Najdluzej: czerwone 2h.","E"),
         osol("kangur-maluch-2024-22","Plaster z 9 komorek z liczbami. Po analizie sasiedztwa miod jest w 5 komorkach.","B")]),
    [dict(q="Wszystkie psy szczekaja. Burek jest psem. Burek:",
          choices={"A":"Szczeka","B":"Nie szczeka","C":"Mialczy"}, correct="A",
          explain="Z 'wszystkie X maja Y' i 'A to X' wynika 'A ma Y'."),
     dict(q="Kontrprzyklad obala zdanie ze slowem:",
          choices={"A":"Wszystkie","B":"Niektore","C":"Istnieje"}, correct="A",
          explain="Zdanie 'wszystkie' obalimy znajdujac jeden wyjatek."),
     dict(q="Zdanie '15 jest podzielne przez 3' to:",
          choices={"A":"Prawda","B":"Falsz","C":"Nie wiadomo"}, correct="A",
          explain="15 : 3 = 5 bez reszty.")])
LESSONS.append(l36)

# === LEKCJA 37: Klamcy i prawdomowni ===
l37 = lesson("l37", 37, "Logika i myslenie", "G", "Kto powiedzial prawde - zagadki", "logika", 16,
    "W zagadce kilka osob mowi cos o sobie. Wiesz, ze TYLKO jeden klamie (lub tylko jeden mowi prawde). Twoim zadaniem jest znalezc tego klamce. Logika daje narzedzie: zaloz, ze konkretna osoba klamie, sprawdz czy reszta jest spojna.",
    "Sztuczka 1: ZALOZ I SPRAWDZ. Po kolei sprawdzaj zalozenie 'X klamie'. Reszta musi byc spojna. Jezeli reszta tworzy sprzecznosc - X nie klamie.\n\nSztuczka 2: DWA SPRZECZNE ZDANIA = JEDNO KLAMSTWO. Jezeli dwie osoby mowia rzeczy, ktore nie moga byc oba prawdziwe (np. 'Ja jadlem' i 'On nie jadl' o tym samym), to jedna z nich klamie.\n\nSztuczka 3: PORZADEK WSPOLNY. Jezeli A wyzszy od B, B wyzszy od C, to A wyzszy od C. Lancuch nierownosci ustawia wszystkich.\n\nSztuczka 4: TABELKA. Dla wielu osob i wielu cech (kto co dostal, kto gdzie mieszka) - rysuj tabelke i wykluczaj.",
    "Pulapka: w zagadce 'jeden klamie' - sprawdz KAZDA mozliwosc, kto klamca. Czesto roznia sie subtelnie. Zazwyczaj jeden z 'klamcow' produkuje sprzecznosc - to NIE on klamie. Klamca to ten, ktory daje SPOJNA reszte.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(37,"v1","w1","3pkt","logika","prosta zagadka",
            "Trzech chlopcow. Adam: 'Mam najwiecej'. Bartek: 'Adam ma najmniej'. Czarek: 'Ja mam najwiecej'. Tylko jeden mowi prawde. Kto ma najwiecej?",
            {"A":"Adam","B":"Bartek","C":"Czarek","D":"Nie da sie","E":"Wszyscy tyle samo"},"B"),
         gen(37,"v1","w2","3pkt","logika","porzadek wzrostu",
            "Ola jest wyzsza od Beni. Bena jest wyzsza od Cyryla. Kto jest najwyzszy?",
            {"A":"Ola","B":"Bena","C":"Cyryl","D":"Wszyscy rowni","E":"Nie wiadomo"},"A"),
         gen(37,"v1","w3","3pkt","logika","wyciaganie wnioskow",
            "Janek jest starszy od Piotra. Piotr jest starszy od Marka. Kto jest najmlodszy?",
            {"A":"Janek","B":"Piotr","C":"Marek","D":"Rowni","E":"Nie wiadomo"},"C"),
         orig(2012,22),
         orig(2019,22)],
        [orig(2014,19),
         orig(2016,23)],
        [sol("gen-l37-v1-w1","Sprawdzam kazdy przypadek.","Zalozenia.",
            ["Jezeli Adam mowi prawde, to Bartek i Czarek klamia. Ale Czarek 'Ja najwiecej' falsz, Bartek 'Adam najmniej' falsz - czyli Adam NIE najmniej. To pasuje. Ale tylko jeden mowi prawde - tu Adam mowi prawde i to jeden.","Jezeli Bartek prawde: Adam ma najmniej. Adam mowi 'mam najwiecej' - klamie. Czarek mowi 'ja najwiecej' - musi byc prawda lub klamstwo. Adam najmniej, wiec Czarek mogl byc lub nie. Ale tylko jeden prawde - Bartek. Czarek klamie - 'ja najwiecej' falsz, czyli ktos inny ma najwiecej. Bartek najwyzej? Spojne.","Najczesciej w tej konfiguracji najwiecej ma Bartek"],"B",
            "Wymaga sprawdzania wszystkich kombinacji."),
         sol("gen-l37-v1-w2","Lancuch: Ola > Bena > Cyryl.","Porzadek.",["Ola najwyzsza"],"A"),
         sol("gen-l37-v1-w3","Lancuch: Janek > Piotr > Marek.","Porzadek.",["Marek najmlodszy"],"C"),
         osol("kangur-maluch-2012-22","Kowalscy 5 dzieci, prezenty. Adas najmlodszy=mis, najstarsze=ksiazka. Bartek=pilka. Cesia<Ela, Cesia>Bartek, Cesia nie ukladanka. Ela najstarsza=ksiazka. Cesia=lalka. Darek=ukladanka.","D"),
         osol("kangur-maluch-2019-22","Pieciu krasnoludkow, ciastko zjadl jeden, sklamal jeden. Po analizie: Bartek zjadl, Edek sklamal.","B"),
         osol("kangur-maluch-2014-19","Krysia w zoltym (ma psa - nie zielony), Zosia wyjezdza w niedziele - nie zaproszona z niebieskiego. Wniosek: Ania niebieski, Krysia zolty, Zosia zielony.","D"),
         osol("kangur-maluch-2016-23","Pilkarz najmlodszy bez rodzenstwa. Antek starszy od koszykarza i przyjazni z siostra Kacpra. Kacper koszykarz, Franek pilkarz, Antek siatkarz.","B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(37,"v2","w1","3pkt","logika","klamca prosty",
            "Anka mowi: 'Mam jablko'. Beata: 'Anka klamie'. Cyryl: 'Beata mowi prawde'. Jezeli klamie tylko jedna osoba, kto?",
            {"A":"Anka","B":"Beata","C":"Cyryl","D":"Nie da sie ustalic","E":"Wszystkie kłamią"},"A"),
         gen(37,"v2","w2","3pkt","logika","porzadek wagi",
            "Tomek wazy wiecej niz Olek. Olek wiecej niz Filip. Kto wazy najmniej?",
            {"A":"Tomek","B":"Olek","C":"Filip","D":"Wszyscy tyle samo","E":"Nie wiadomo"},"C"),
         gen(37,"v2","w3","3pkt","logika","prosty porzadek",
            "Pies jest szybszy od kota. Kot jest szybszy od zolwia. Kto jest najszybszy?",
            {"A":"Pies","B":"Kot","C":"Zolw","D":"Rowni","E":"Nie wiadomo"},"A"),
         orig(2018,22),
         orig(2025,18)],
        [orig(2018,20),
         orig(2013,21)],
        [sol("gen-l37-v2-w1","Beata i Cyryl mowia spojnie ze soba.","Analiza spojnosci.",
            ["Jezeli Anka mowi prawde - ma jablko. Beata mowi ze Anka klamie - Beata klamie. Cyryl mowi ze Beata prawde - Cyryl tez klamie. Dwoch klamcow - sprzecznosc.","Jezeli Anka klamie - nie ma jablka. Beata mowi prawde. Cyryl mowi prawde. Tylko Anka klamie. OK"],"A"),
         sol("gen-l37-v2-w2","Lancuch: Tomek > Olek > Filip.","Porzadek.",["Filip najmniej"],"C"),
         sol("gen-l37-v2-w3","Pies > kot > zolw.","Porzadek szybkosci.",["Pies najszybszy"],"A"),
         osol("kangur-maluch-2018-22","Zabawki: ceny 10, 20, 30, 40 zl. Mis+Lala > Pilka+Ukladanka, Mis+Ukladanka = Pilka. Po analizie: pilka 30 zl.","C"),
         osol("kangur-maluch-2025-18","Maria 11, brat Jozka 11+5=16, mlodsza siostra Marii = m, Jozek = m-2. Jozek mlodszy od brata o 16-(m-2)=18-m. Z warunkow m daje roznice 7.","A"),
         osol("kangur-maluch-2018-20","Trasa Makuszyce - Pacanow przez wszystkie miasta. Cala 100 km. Po analizie warunkow: najkrotsza droga 26 km.","C"),
         osol("kangur-maluch-2013-21","7 dzwonkow 1-7 zl, suma 28. Podzial na 3 rowne zestawy: 28:3 nie calkowite. Niemozliwe.","E")]),
    [dict(q="W zagadce 'jeden klamie' najlepsza strategia:",
          choices={"A":"Zalozyc i sprawdzic","B":"Zgadnac","C":"Pominac"}, correct="A",
          explain="Zalozenie 'X klamie' i sprawdzenie spojnosci pozostalych."),
     dict(q="A>B i B>C oznacza:",
          choices={"A":"A>C","B":"A<C","C":"A=C"}, correct="A",
          explain="Lancuch nierownosci - przechodnia relacja."),
     dict(q="Dwa zdania sprzeczne oznaczaja:",
          choices={"A":"Jedno klamstwo","B":"Oba prawdy","C":"Oba klamstwa"}, correct="A",
          explain="Dwa sprzeczne nie moga byc oba prawda - dokladnie jedno klamstwo.")])
LESSONS.append(l37)

# === LEKCJA 38: Tabelki logiczne ===
l38 = lesson("l38", 38, "Logika i myslenie", "G", "Tabelki logiczne i przyporzadkowania", "logika", 16,
    "Zadanie: 'Trzy dzieci, trzy zabawki - kto co dostal?' Najlepsze narzedzie to tabelka. Wiersze - dzieci, kolumny - zabawki, w komorce TAK lub NIE. Wykluczanie krok po kroku, az zostanie tylko jedna mozliwosc dla kazdego.",
    "Sztuczka 1: NARYSUJ TABELKE. Wiersze - osoby/obiekty. Kolumny - cechy/przedmioty. To pomaga sledzic, co juz ustalone.\n\nSztuczka 2: WYKLUCZAJ. Jezeli wiesz, ze Ola NIE ma misia - wpisz NIE w odpowiednia komorke. Po kazdym wykluczeniu sprawdz, czy nie zostala tylko jedna opcja w wierszu lub kolumnie.\n\nSztuczka 3: UNIKALNOSC. Jezeli wiesz, ze tylko jeden moze miec daną cechę, a wszyscy inni juz ja maja wykluczona - to pewne kto.\n\nSztuczka 4: SPRAWDZAJ WSZYSTKIE WARUNKI. Po wypelnieniu tabelki przejdz przez kazdy warunek i sprawdz spojnosc.",
    "Pulapka: warunki czesto nie sa wszystkie 'TAK' lub 'NIE'. Niektore to 'jezeli A to B' - czyli warunkowe. Tłumacz na: 'jezeli A nie B - sprzecznosc'.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(38,"v1","w1","3pkt","logika","prosta tabelka",
            "Trzy dzieci, kazde ma inne zwierze. Ola nie ma psa. Bartek ma kota. Kto ma psa: Ola, Bartek czy Czarek?",
            {"A":"Ola","B":"Bartek","C":"Czarek","D":"Nie wiadomo","E":"Wszyscy"},"C"),
         gen(38,"v1","w2","3pkt","logika","dwie pewne",
            "Trzy dzieci: A, B, C. Lubia jablko, gruszke, banan (kazde lubi inny). A nie lubi banana. B lubi gruszke. Co lubi C?",
            {"A":"Jablko","B":"Gruszke","C":"Banan","D":"Nic","E":"Wszystko"},"C"),
         gen(38,"v1","w3","3pkt","logika","wykluczenie",
            "Trzy domy: czerwony, zielony, niebieski. Trzy osoby: X, Y, Z. X NIE w czerwonym. Y w zielonym. Gdzie mieszka Z?",
            {"A":"Czerwony","B":"Zielony","C":"Niebieski","D":"Nie wiadomo","E":"W obu"},"A"),
         orig(2024,23),
         orig(2022,12)],
        [orig(2021,11),
         orig(2024,14)],
        [sol("gen-l38-v1-w1","Bartek ma kota, Ola nie ma psa - wiec ma cos innego.","Wykluczenia w tabelce.",
            ["Bartek = kot. Ola != pies. Trzy zwierzeta: pies, kot, X. Ola != pies, Ola != kot (Bartek) - Ola ma X. Pozostaje pies dla Czarka."],"C"),
         sol("gen-l38-v1-w2","B=gruszka. A!=banan, wiec A=jablko. C=banan.","Eliminacja.",
            ["B = gruszka","A nie banan, A nie gruszka (B), wiec A = jablko","C = banan"],"C"),
         sol("gen-l38-v1-w3","Y=zielony. X!=czerwony. Wiec X=niebieski. Z=czerwony.","Eliminacja.",
            ["Y = zielony","X nie czerwony, X nie zielony (Y) - X = niebieski","Z = czerwony"],"A"),
         osol("kangur-maluch-2024-23","Troje dzieci, jedno wziele wszystkie serca, jedno jasne, jedno duze. 3, 6, 7 ciastek. Po analizie zestaw D pasuje.","D"),
         osol("kangur-maluch-2022-12","Dzieci kolorowaly. Franek nie krolik. Jozek pilka. Tadzik rozne zwierzeta. Ala jedno zwierze. Kajtek bez zwierzat. Franek = A (jeze).","A"),
         osol("kangur-maluch-2021-11","Nalepki: jablko=1, kwiatek miedzy kolo i trojkat. Gwiazda NIE 5. Po analizie kwiatek=4.","B"),
         osol("kangur-maluch-2024-14","Ada 8 zetonow, usuwa kolejno 2.,3.,4.,5. od dolu. Po analizie wieza B.","B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(38,"v2","w1","3pkt","logika","tabelka 3x3",
            "3 dzieci, 3 owoce. Ada nie lubi jablek. Beata lubi gruszki. Co lubi Cezary, jezeli kazde lubi inny owoc (jablko, gruszka, banan)?",
            {"A":"Jablko","B":"Gruszke","C":"Banan","D":"Wszystkie","E":"Zadne"},"A"),
         gen(38,"v2","w2","3pkt","logika","wybor zawodu",
            "Trzy osoby: lekarz, nauczyciel, fryzjer. Kazda inny zawod. Anka NIE lekarz. Bartek nauczyciel. Czy jest mozliwe zeby Anka byla fryzjerem?",
            {"A":"Tak","B":"Nie","C":"Tylko czasem","D":"Zalezy","E":"Niewazne"},"A"),
         gen(38,"v2","w3","3pkt","logika","kto co ma",
            "Trzy osoby A, B, C. Maja: psa, kota, papuge. A nie kota. B ma papuge. Co ma C?",
            {"A":"Psa","B":"Kota","C":"Papuge","D":"Nic","E":"Wszystko"},"B"),
         orig(2025,9),
         orig(2021,8)],
        [orig(2022,22),
         orig(2021,16)],
        [sol("gen-l38-v2-w1","Beata = gruszka. Ada nie jablko, wiec banan. Cezary = jablko.","Eliminacja.",
            ["Beata = gruszka","Ada nie jablko, nie gruszka, wiec banan","Cezary = jablko"],"A"),
         sol("gen-l38-v2-w2","Bartek=nauczyciel. Anka nie lekarz - moze byc fryzjerem.","Mozliwosc.",
            ["Bartek = nauczyciel","Anka nie lekarz, nie nauczyciel - moze byc fryzjerem"],"A"),
         sol("gen-l38-v2-w3","B=papuga. A nie kot - ma psa. C = kot.","Eliminacja.",
            ["B = papuga","A nie kot, nie papuga (B) - A = pies","C = kot"],"B"),
         osol("kangur-maluch-2025-9","Talerze Helenki, Stasia, Slawka z kangurkowymi ciastkami. Dwie czesci uzupelnia ukladanke. Para 1 i 2.","A"),
         osol("kangur-maluch-2021-8","Karty z owocami w 3 rodzajach. Na ktorym ukladzie NIE da sie zamiana 2 kart by ulozyc te same obok siebie. Uklad D.","D"),
         osol("kangur-maluch-2022-22","Gasienica Hulajkula zwijana. Sasiednie kulki w rozwinietej musza dotykac w zwinietej. Wariant A.","A"),
         osol("kangur-maluch-2021-16","Kostek 3 kubki, 10 razy bierze lewy, odwraca, stawia po prawej. Stan koncowy = wariant C.","C")]),
    [dict(q="Najlepsze narzedzie do zadan 'kto co ma':",
          choices={"A":"Tabelka","B":"Zgadywanie","C":"Liczenie"}, correct="A",
          explain="Tabelka pozwala wykluczac systematycznie."),
     dict(q="Wpisujemy NIE w komorke gdy:",
          choices={"A":"Wiemy ze X nie ma Y","B":"Wiemy ze X ma Y","C":"Nie wiemy"}, correct="A",
          explain="NIE wpisujemy dla wykluczenia."),
     dict(q="Gdy w wierszu zostaje tylko jedna opcja:",
          choices={"A":"To wlasnie ta","B":"Trzeba zgadywac","C":"Brak rozwiazania"}, correct="A",
          explain="Jedyna pozostała opcja musi być prawdziwa.")])
LESSONS.append(l38)

# === LEKCJA 39: Eliminacja mozliwosci ===
l39 = lesson("l39", 39, "Logika i myslenie", "G", "Eliminacja mozliwosci", "logika", 14,
    "Kangur daje 5 opcji A-E. Jedna jest poprawna. Zamiast szukac jej od zera, mozna ELIMINOWAC - wyrzucac te, ktore na pewno NIE moga byc poprawne. Czasem zostaje 1-2 odpowiedzi i wybor jest oczywisty.",
    "Sztuczka 1: SPRAWDZ ZA DUZE I ZA MALE. Jezeli wynik powinien byc okolo 50, odpowiedzi 5 i 500 mozna wyrzucic.\n\nSztuczka 2: SPRAWDZ PARZYSTOSC. Jezeli wynik MUSI byc parzysty (np. suma parzystych), wyrzuc wszystkie nieparzyste odpowiedzi.\n\nSztuczka 3: SPRAWDZ OSTATNIA CYFRE. 27 razy 4 - ostatnia cyfra to ostatnia cyfra 7*4=28, czyli 8. Z odpowiedzi szukaj tylko konczacych sie na 8.\n\nSztuczka 4: SPRAWDZ JEDNOSTKI. Pytanie o cm a odpowiedzi w m - prawdopodobnie pulapka. Sprawdz jednostki.",
    "Pulapka: czasem 2-3 odpowiedzi przezyja eliminacje. Wtedy sprawdz dokladniej te 2-3, a nie wszystkie 5. To oszczedza czas i zmniejsza ryzyko bledu.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(39,"v1","w1","3pkt","logika","eliminacja parzystosci",
            "Suma trzech liczb parzystych. Ktora odpowiedz NIE moze byc poprawna?",
            {"A":"6","B":"10","C":"14","D":"15","E":"30"},"D"),
         gen(39,"v1","w2","3pkt","logika","eliminacja przez ostatnia cyfre",
            "23 razy 5 - ktora odpowiedz jest poprawna (sprawdz ostatnia cyfre)?",
            {"A":"100","B":"105","C":"110","D":"115","E":"125"},"D"),
         gen(39,"v1","w3","3pkt","logika","eliminacja wielkosci",
            "Pole prostokata 5x4 cm. Ktora odpowiedz NIE moze byc poprawna?",
            {"A":"15","B":"20","C":"100","D":"18","E":"22"},"C"),
         orig(2018,6),
         orig(2025,4)],
        [orig(2025,6),
         orig(2020,20)],
        [sol("gen-l39-v1-w1","Suma parzystych jest parzysta.","Parzystosc.",
            ["Parzysta + parzysta + parzysta = parzysta","15 jest nieparzysta - eliminuje"],"D"),
         sol("gen-l39-v1-w2","Ostatnia cyfra 3*5=15, czyli 5.","Ostatnia cyfra.",
            ["3 razy 5 = 15, ostatnia cyfra 5","Tylko 115 konczy sie na 5"],"D"),
         sol("gen-l39-v1-w3","Pole 5x4=20. 100 to za duzo.","Sprawdzenie wielkosci.",
            ["5 razy 4 = 20","100 znacznie wieksze - eliminuje"],"C"),
         osol("kangur-maluch-2018-6","5 wkretow, 4 rownej dlugosci, 1 krotszy. Krotszy = wkret C.","C"),
         osol("kangur-maluch-2025-4","Wezel powstanie tylko na jednym sznurku. Sznurek C.","C"),
         osol("kangur-maluch-2025-6","Ela i Ewa muszle (6) + zetony (1) = 16. Sposob B.","B"),
         osol("kangur-maluch-2020-20","Kod, ktorego symbole na danych pozycjach nie wystepuja w innych. Kod D.","D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(39,"v2","w1","3pkt","logika","eliminacja parzystosci",
            "Suma dwoch nieparzystych liczb. Ktora odpowiedz na pewno NIE pasuje?",
            {"A":"8","B":"10","C":"11","D":"14","E":"20"},"C"),
         gen(39,"v2","w2","3pkt","logika","ostatnia cyfra mnozenia",
            "47 razy 3 - ktora odpowiedz pasuje (sprawdz ostatnia cyfre)?",
            {"A":"140","B":"141","C":"144","D":"147","E":"148"},"B"),
         gen(39,"v2","w3","3pkt","logika","wielkosc szacowana",
            "Mama kupila 4 jablka po okolo 2 zl. Ile zaplacila (mniej wiecej)?",
            {"A":"4 zl","B":"8 zl","C":"20 zl","D":"80 zl","E":"2 zl"},"B"),
         orig(2018,1),
         orig(2023,2)],
        [orig(2022,3),
         orig(2022,1)],
        [sol("gen-l39-v2-w1","Nieparzysta + nieparzysta = parzysta. 11 nieparzysta - nie pasuje.","Parzystosc.",
            ["Nieparzysta + nieparzysta = parzysta","11 nieparzysta - eliminuje"],"C"),
         sol("gen-l39-v2-w2","7*3=21, ostatnia 1.","Ostatnia cyfra.",["47 razy 3: 7*3=21, ost. 1","Tylko 141 konczy sie na 1"],"B"),
         sol("gen-l39-v2-w3","4 razy 2 = 8 zl.","Szacowanie.",["4 razy 2 = 8 zl"],"B"),
         osol("kangur-maluch-2018-1","Pieczatki cyfr 0-9. Data 15032018: cyfry rozne to 0,1,2,3,5,8 = 6 pieczatek.","B"),
         osol("kangur-maluch-2023-2","Bilety z kodami. Wylosowany pasuje do zoo.","D"),
         osol("kangur-maluch-2022-3","Pudelka, by otworzyc 'pociag' trzeba zdjac 5 pudelek nad nim.","C"),
         osol("kangur-maluch-2022-1","Pszczola na siatce do kwiatka. Sekwencja A.","A")]),
    [dict(q="Eliminacja przez parzystosc:",
          choices={"A":"Wyrzucasz nieparzyste gdy wynik parzysty","B":"Zgadujesz","C":"Pomijasz"}, correct="A",
          explain="Jezeli wynik musi byc parzysty, nieparzyste odpadaja."),
     dict(q="27 razy 4 - ostatnia cyfra wyniku to:",
          choices={"A":"6","B":"7","C":"8"}, correct="C",
          explain="7*4=28, ostatnia cyfra 8."),
     dict(q="Eliminacja wyrzuca odpowiedzi:",
          choices={"A":"Niemozliwe","B":"Najlatwiejsze","C":"Pierwsze"}, correct="A",
          explain="Eliminujemy te, ktore na pewno nie moga byc poprawne.")])
LESSONS.append(l39)

# === LEKCJA 40: Wagi i porownania ===
l40 = lesson("l40", 40, "Logika i myslenie", "G", "Wagi i porownania", "logika", 14,
    "Stara waga szalkowa: dwie miseczki, jedna z odwaznikami, druga z towarem. Rownowaga = ten sam ciezar. Wagi to klasyczne logiczne zagadki - od porownywania, kto ciezszy, po zlozone uklady rownan z trzema rodzajami klockow.",
    "Sztuczka 1: ROWNOWAGA = ROWNE CIEZARY. Jezeli waga jest w rownowadze, lewa szalka = prawej.\n\nSztuczka 2: PORownujac TRZECH. Jezeli A+B=C+B (waga rowna), to A=C. Mozemy 'odjac' B od obu stron.\n\nSztuczka 3: UKLAD ROWNAN. 3 wagi z 3 rodzajami klockow = 3 rownania. Sprowadzaj do jednego klocka.\n\nSztuczka 4: PORZADEK WAG. Trzy paczki, dwie wagi: A+B<A+C i B+C<A+C. Wniosek: B najmniejszy, A=C lub C najwiekszy.",
    "Pulapka: czasem wagi nie sa w rownowadze - jedna strona ciezsza. Wtedy NIE oznacza rownosci, tylko nierownosc. Czytaj uwaznie - 'waga w rownowadze' vs 'jedna szalka opadla'.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(40,"v1","w1","3pkt","logika","prosta rownowaga",
            "Na wadze szalkowej z lewej jablko 200 g, z prawej gruszka. Waga w rownowadze. Ile waży gruszka?",
            {"A":"100 g","B":"150 g","C":"200 g","D":"300 g","E":"400 g"},"C"),
         gen(40,"v1","w2","3pkt","logika","porownanie",
            "Na lewej szalce 2 klocki, na prawej 4. Waga w rownowadze. Co z tego wynika?",
            {"A":"Klocki lewe ciezsze (po 2x)","B":"Klocki prawe ciezsze","C":"Wszystkie rowne","D":"Nic","E":"Bledna waga"},"A"),
         gen(40,"v1","w3","3pkt","logika","odjecie",
            "Lewa: A+B=10 g. Prawa: A+C=10 g. Wniosek?",
            {"A":"A=B","B":"B=C","C":"A=C","D":"Wszystko rowne","E":"Nic"},"B"),
         orig(2021,7),
         orig(2023,10)],
        [orig(2021,22),
         orig(2016,21)],
        [sol("gen-l40-v1-w1","Rownowaga = rowne masy.","Rownowaga.",["Gruszka = 200 g"],"C"),
         sol("gen-l40-v1-w2","2 klocki lewe = 4 prawe, wiec lewy 2x ciezszy od prawego.","Stosunek mas.",
            ["2L = 4P → L = 2P, lewy 2x ciezszy"],"A"),
         sol("gen-l40-v1-w3","Z A+B=A+C → B=C.","Odejmowanie tej samej wartosci.",
            ["A+B = A+C, odejmij A od obu: B = C"],"B"),
         osol("kangur-maluch-2021-7","3 wagi z kulami: b+s=6, 2c+b=14, s+2b=10. Z W1: s=6-b. W3: 6-b+2b=10, b=4, s=2. W2: 2c+4=14, c=5.","C"),
         osol("kangur-maluch-2023-10","6 odwaznikow 1-6 kg, 5 na wadze w rownowadze. Suma 5 musi byc parzysta. 21-x parzysta -> x nieparzysta. Odpowiedz: 1 kg.","A"),
         osol("kangur-maluch-2021-22","3 wagi z trzema figurami. Co dolozyc na lewa szalke trzeciej wagi. Trojkat D.","D"),
         osol("kangur-maluch-2016-21","Asia 3 rodzaje klockow w 3 pojemnikach. Najlzejszy trojkat, najciezsze kolo.","B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(40,"v2","w1","3pkt","logika","jednostka wagi",
            "Klocek wazy 5 g. Ile wazy 4 takie klocki?",
            {"A":"9 g","B":"12 g","C":"15 g","D":"20 g","E":"25 g"},"D"),
         gen(40,"v2","w2","3pkt","logika","rownowaga z trzema",
            "Lewa: 3 czerwone klocki. Prawa: 6 niebieskich. Rownowaga. Ile niebieskich = 1 czerwony?",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"B"),
         gen(40,"v2","w3","3pkt","logika","najciezsze",
            "Kot wazy wiecej niz mysz. Pies wazy wiecej niz kot. Kto wazy najwiecej?",
            {"A":"Mysz","B":"Kot","C":"Pies","D":"Wszyscy tyle samo","E":"Nie wiadomo"},"C"),
         orig(2021,21),
         orig(2024,17)],
        [orig(2025,21),
         orig(2025,19)],
        [sol("gen-l40-v2-w1","4 razy 5 g = 20 g.","Mnozenie.",["4 razy 5 = 20 g"],"D"),
         sol("gen-l40-v2-w2","3C = 6N → 1C = 2N.","Stosunek.",["3C=6N, 1C=2N"],"B"),
         sol("gen-l40-v2-w3","Pies > kot > mysz.","Porzadek.",["Pies najciezszy"],"C"),
         osol("kangur-maluch-2021-21","5 skrzyn jablek/bananow. Wagi 7,5,6,2,16 kg. Banany 3x ciezsze od jablek lacznie. Jablka 9 kg, banany 27 kg. Jablka w 1 i 4.","E"),
         osol("kangur-maluch-2024-17","3 bryly wazone parami: 200, 100, 240 g. Suma par = 2 razy suma bryl. 540:2 = 270 g.","A"),
         osol("kangur-maluch-2025-21","Na 2 wagach Kajtek polozyl klocki 3 rodzajow. Klocek typu A wazy 5 kg. Klocek B (jasny szescian) wazy 3 kg.","C"),
         osol("kangur-maluch-2025-19","5 szklanek z 1,2,3,4,6 kulkami, woda. Najmniej wody w szklance 1.","A")]),
    [dict(q="Waga w rownowadze oznacza:",
          choices={"A":"Lewa = prawa","B":"Lewa > prawa","C":"Lewa < prawa"}, correct="A",
          explain="Rownowaga = rowne ciezary po obu stronach."),
     dict(q="Z A+B=A+C wynika:",
          choices={"A":"B=C","B":"B>C","C":"B<C"}, correct="A",
          explain="Odejmij A od obu stron: B=C."),
     dict(q="3 wagi z 3 rodzajami klockow to:",
          choices={"A":"3 rownania","B":"3 zagadki","C":"3 mozliwosci"}, correct="A",
          explain="Kazda waga to jedno rownanie - razem uklad rownan.")])
LESSONS.append(l40)

# === LEKCJA 41: Przelewanie i przemiany ===
l41 = lesson("l41", 41, "Logika i myslenie", "G", "Przelewanie, przesypywanie, podzialy", "logika", 16,
    "Klasyczna zagadka: mam dzbanki 3l i 5l, muszę odmierzyć dokladnie 4l. Jak? Te zadania nazywaja sie 'przelewania' - polegaja na sledzeniu sekwencji ruchow, az dojdziemy do celu. Wymaga to planowania kilku krokow naprzod.",
    "Sztuczka 1: ZAPISUJ STANY. Po kazdym ruchu zapisz, ile jest w kazdym naczyniu. Latwo sledzic.\n\nSztuczka 2: ZACZNIJ OD CELU. Czego chce dostac? Jakim ruchem do tego dojde? Cofnij sie krok po kroku.\n\nSztuczka 3: WYKORZYSTUJ ROZNICE. 5l - 3l = 2l. Czesto roznice pojemnosci daja kluczowe ilosci.\n\nSztuczka 4: PODZIAL = PRZELEWANIE. Tlumacz zadania o podziale (np. cukierki na 3 czesci) jako przelewanie - rownie systematyczne.",
    "Pulapka Kangurka: zadania z minimalna liczba krokow. Czesto pierwszy pomysl daje za duzo krokow. Sprawdz, czy nie ma 'sprytniejszego' sposobu - np. przelej raz duzo, zamiast po troche.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(41,"v1","w1","3pkt","logika","podzial po rowno",
            "Mama ma 12 cukierkow i 3 dzieci. Po ile cukierkow dostanie kazde dziecko, jezeli dzieli rowno?",
            {"A":"2","B":"3","C":"4","D":"6","E":"12"},"C"),
         gen(41,"v1","w2","3pkt","logika","podzial z reszta",
            "20 jablek na 6 dzieci po rowno. Ile dostanie kazde, ile zostanie?",
            {"A":"3 i zostanie 2","B":"4 i zostanie 0","C":"2 i zostanie 8","D":"5 i zostanie 0","E":"3 i zostanie 3"},"A"),
         gen(41,"v1","w3","3pkt","logika","najmniej krokow",
            "Z dzbanka 4l odlej 2l do innego. Jednym ruchem mozesz przelac dowolna ilosc. Ile potrzeba ruchow?",
            {"A":"1","B":"2","C":"3","D":"4","E":"5"},"A"),
         orig(2015,19),
         orig(2018,21)],
        [orig(2014,14),
         orig(2019,19)],
        [sol("gen-l41-v1-w1","12 : 3 = 4.","Dzielenie po rowno.",["12 : 3 = 4 cukierki na dziecko"],"C"),
         sol("gen-l41-v1-w2","20:6 = 3 r.2.","Dzielenie z reszta.",["20 : 6 = 3 reszta 2"],"A"),
         sol("gen-l41-v1-w3","Jeden ruch wystarcza - odlej 2l.","Prosty podzial.",["Wystarcza 1 ruch"],"A"),
         osol("kangur-maluch-2015-19","Dzbany: bialy=10L. 6m+3s+1d=10 i 2m+s+3d=10. Stad b=10=4d. Czyli 4 duze dzbany.","A"),
         osol("kangur-maluch-2018-21","Wiadra biale (10L), niebieskie, zielone. Z rownan: niebieskie=2L.","B"),
         osol("kangur-maluch-2014-14","Krolik dziennie 9 marchewek lub 2 salaty lub 1 salate i 4 marchewki. Tydzien (7 dni), 30 marchewek. a=2 (9 marchewek), c=3 (mieszane), b=2 (salaty). Salaty: 2*2+3=7.","B"),
         osol("kangur-maluch-2019-19","15 zwierzat, 10 nie krowy (5 krow), 8 nie owce (7 owiec). Gesi: 15-5-7=3.","B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(41,"v2","w1","3pkt","logika","podzial rowny",
            "30 piłeczek na 5 koszykow po rowno. Ile w kazdym?",
            {"A":"5","B":"6","C":"10","D":"15","E":"25"},"B"),
         gen(41,"v2","w2","3pkt","logika","reszta z dzielenia",
            "17 ciastek na 5 dzieci po rowno. Ile dostanie kazde, ile zostanie?",
            {"A":"3 i 2","B":"4 i 0","C":"2 i 7","D":"5 i 0","E":"3 i 4"},"A"),
         gen(41,"v2","w3","3pkt","logika","minimalna liczba krokow",
            "Mam 2 monety 5 zl i 3 monety 2 zl. Ile mam zlotych razem?",
            {"A":"7","B":"10","C":"13","D":"15","E":"16"},"E"),
         orig(2015,22),
         orig(2024,9)],
        [orig(2018,2),
         orig(2018,8)],
        [sol("gen-l41-v2-w1","30 : 5 = 6.","Dzielenie.",["30:5=6"],"B"),
         sol("gen-l41-v2-w2","17:5=3 r.2.","Dzielenie z reszta.",["17:5=3 r.2"],"A"),
         sol("gen-l41-v2-w3","2*5+3*2=10+6=16.","Sumowanie monet.",["2*5=10, 3*2=6, razem 16"],"E"),
         osol("kangur-maluch-2015-22","3 liny, dowiazanie koncow ktorego zestawu da jedna line. Zestaw C.","C"),
         osol("kangur-maluch-2024-9","Pionek z moneta. Ela na pole 4, Wladek na 8 po 4 rzutach kazdy. Razem 3 orly (Ela 2, Wladek 1).","C"),
         osol("kangur-maluch-2018-2","3 strzaly i 9 balonikow. Strzala leci dalej po przebiciu. Trafia w 5 balonikow.","D"),
         osol("kangur-maluch-2018-8","Stol dla 8 osob, sztucce: widelec lewo, noz prawo. Poprawnie dla 3 osob.","E")]),
    [dict(q="Najlepsza strategia w zadaniach przelewania:",
          choices={"A":"Zapisuj stany","B":"Zgaduj","C":"Pomijaj"}, correct="A",
          explain="Po kazdym ruchu zapisz ile w kazdym naczyniu."),
     dict(q="20:6 daje:", choices={"A":"3 r. 2","B":"4 r. 0","C":"2 r. 8"}, correct="A",
          explain="20:6=3 r.2."),
     dict(q="Cofanie od celu pomaga gdy:",
          choices={"A":"Wynik znany, start nieznany","B":"Brak danych","C":"Nigdy"}, correct="A",
          explain="Wynik znany - cofamy operacje, aż dojdziemy do startu.")])
LESSONS.append(l41)

# ============== BLOK H: KOMBINATORYKA ==============

# === LEKCJA 42: Na ile sposobow ===
l42 = lesson("l42", 42, "Kombinatoryka i liczenie", "H", "Na ile sposobow - proste przypadki", "kombinatoryka", 14,
    "Na ile sposobow mozesz ulozyc 3 ksiazki na polce? A na ile sposobow ubierzesz koszulke i spodnie z 4 koszulek i 3 spodni? Kombinatoryka odpowiada na pytania 'ile mozliwosci'. Klucz to liczenie systematyczne.",
    "Sztuczka 1: WYPISUJ POCZATEK. Na ile sposobow ulozyc litery A, B, C? Wypisz: ABC, ACB, BAC, BCA, CAB, CBA = 6 sposobow.\n\nSztuczka 2: ILOCZYN MOZLIWOSCI. Jezeli wybierasz koszulke (4 opcje) i spodnie (3 opcje) - razem 4 razy 3 = 12 mozliwosci.\n\nSztuczka 3: ZACZNIJ OD WYBORU. Pierwszy element: ile opcji. Drugi: ile zostalo. Mnozysz.\n\nSztuczka 4: PERMUTACJE. n roznych elementow w rzedzie: n*(n-1)*(n-2)*...*1. Dla 3 elementow: 3*2*1=6.",
    "Pulapka Kangurka: 'kolejnosc nie ma znaczenia'. Wybor 2 osob z 4 ZAleznie czy z kolejnoscia (8 par) czy bez (6). Czytaj uwaznie.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(42,"v1","w1","3pkt","kombinatoryka","permutacje 3",
            "Na ile sposobow mozna ustawic w rzedzie 3 osoby?",
            {"A":"3","B":"6","C":"9","D":"12","E":"27"},"B"),
         gen(42,"v1","w2","3pkt","kombinatoryka","iloczyn",
            "Mam 3 koszulki i 2 pary spodni. Na ile sposobow moge sie ubrac?",
            {"A":"3","B":"5","C":"6","D":"9","E":"12"},"C"),
         gen(42,"v1","w3","3pkt","kombinatoryka","wybor 2 z 4",
            "Na ile sposobow wybrac 2 osoby z 4 (bez kolejnosci)?",
            {"A":"4","B":"6","C":"8","D":"12","E":"16"},"B"),
         orig(2023,7),
         orig(2024,7)],
        [orig(2021,9),
         gen(42,"v1","c1","5pkt","kombinatoryka","permutacje 4",
            "Na ile sposobow ustawic 4 rozne ksiazki na polce?",
            {"A":"12","B":"16","C":"20","D":"24","E":"36"},"D")],
        [sol("gen-l42-v1-w1","3*2*1=6.","Permutacje.",["3 elementy: 3! = 6"],"B"),
         sol("gen-l42-v1-w2","3 razy 2 = 6.","Iloczyn.",["3 koszulki * 2 spodnie = 6"],"C"),
         sol("gen-l42-v1-w3","Pary z 4: 4*3/2 = 6.","Wybor 2 z 4.",["(4*3)/2 = 6 par"],"B"),
         osol("kangur-maluch-2023-7","4 zetony, wybor 3, najmniejszy gora, najwiekszy dol. Wybor 3 z 4 = 4 sposoby (kazdy uklad ma jedna ulozenie).","C"),
         osol("kangur-maluch-2024-7","11 graczy w kregu. 1 podaje do 3. gracza po lewej. Po 11 podaniach pilka wraca do 1. Ostatni podajacy: 9.","B"),
         osol("kangur-maluch-2021-9","Ania 5 figur z 5 pudelek, kazda inna. Z 4. pudelka: pieciokat.","C"),
         sol("gen-l42-v1-c1","4*3*2*1 = 24.","Permutacje 4.",["4! = 4*3*2*1 = 24"],"D")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(42,"v2","w1","3pkt","kombinatoryka","permutacje 2",
            "Na ile sposobow ustawic w rzedzie 2 osoby A i B?",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"B"),
         gen(42,"v2","w2","3pkt","kombinatoryka","iloczyn 4x3",
            "Mam 4 czapki i 3 szaliki. Ile zestawow (czapka + szalik) moge wybrac?",
            {"A":"7","B":"9","C":"10","D":"12","E":"15"},"D"),
         gen(42,"v2","w3","3pkt","kombinatoryka","wybor lodow",
            "W lodziarni 5 smakow. Na ile sposobow wybrac 1 smak?",
            {"A":"1","B":"3","C":"5","D":"10","E":"25"},"C"),
         orig(2014,16),
         gen(42,"v2","w5","3pkt","kombinatoryka","liczba paragow",
            "Mam 3 papuga, 2 koty. Na ile sposobow wybrac 1 zwierzakiem (jedno)?",
            {"A":"1","B":"5","C":"6","D":"7","E":"10"},"B")],
        [gen(42,"v2","c1","4pkt","kombinatoryka","permutacje 3 z wyborem",
            "Z 5 osob wybieram 3 do ustawienia w rzedzie. Na ile sposobow?",
            {"A":"15","B":"30","C":"60","D":"90","E":"125"},"C"),
         gen(42,"v2","c2","5pkt","kombinatoryka","trzy elementy",
            "Mam 4 cyfry: 1, 2, 3, 4. Ile liczb 3-cyfrowych moge utworzyc, uzywajac kazdej cyfry raz?",
            {"A":"6","B":"12","C":"18","D":"24","E":"64"},"D")],
        [sol("gen-l42-v2-w1","AB i BA = 2.","Permutacje 2.",["2 osoby = 2!=2"],"B"),
         sol("gen-l42-v2-w2","4*3 = 12.","Iloczyn.",["4 czapki razy 3 szaliki = 12"],"D"),
         sol("gen-l42-v2-w3","Wybor 1 z 5 = 5.","Wybor jednego.",["5 sposobow"],"C"),
         osol("kangur-maluch-2014-16","Liczenie kropek na nakladajacych sie kostkach. Razem 182.","C"),
         sol("gen-l42-v2-w5","3 papugi + 2 koty = 5 zwierzakow.","Sumowanie.",["3+2=5"],"B"),
         sol("gen-l42-v2-c1","5*4*3 = 60.","Permutacje 3 z 5.",["5*4*3=60"],"C"),
         sol("gen-l42-v2-c2","4*3*2 = 24.","Permutacje 3 z 4 cyfr.",["4*3*2=24"],"D")]),
    [dict(q="Permutacja 3 elementow to:",
          choices={"A":"3","B":"6","C":"9"}, correct="B",
          explain="3! = 3*2*1 = 6."),
     dict(q="Wybor koszulki (5) i spodni (4):",
          choices={"A":"9","B":"20","C":"45"}, correct="B",
          explain="5*4=20 kombinacji."),
     dict(q="Wybor 2 z 4 bez kolejnosci:",
          choices={"A":"4","B":"6","C":"8"}, correct="B",
          explain="(4*3)/2=6 par.")])
LESSONS.append(l42)

# === LEKCJA 43: Drzewo mozliwosci ===
l43 = lesson("l43", 43, "Kombinatoryka i liczenie", "H", "Drzewo mozliwosci", "kombinatoryka", 14,
    "Drzewo mozliwosci to graficzny sposob liczenia 'na ile sposobow'. Wybor pierwszej rzeczy daje galezie, z kazdej galezi wychodza dalsze. Liczba lisci na koncu = liczba wszystkich mozliwosci.",
    "Sztuczka 1: RYSUJ DRZEWO. Pierwszy wybor: galezie. Z kazdej galezi: nastepny wybor. Na koncu: liscie - to wszystkie mozliwosci.\n\nSztuczka 2: LICZ LISCIE. Suma lisci = liczba wszystkich konfiguracji. Mozna policzyc bezposrednio lub przez iloczyn (liczba galezi w kazdej rundzie).\n\nSztuczka 3: WYKLUCZANIE GALEZI. Niektore galezie nie sa dozwolone (warunek). Pomijaj je przy liczeniu.\n\nSztuczka 4: WYKORZYSTAJ SYMETRIE. Czesto galezie sa podobne - policz jedna, pomnoz przez liczbe galezi.",
    "Pulapka Kangurka: 'rozne smaki' lub 'kazda kombinacja inna' - kazda mozliwosc to unikalne ulozenie. Sprawdzaj, czy zadanie nie ma DODATKOWYCH ogranicen (np. 'najpierw zielony, potem czerwony').",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(43,"v1","w1","3pkt","kombinatoryka","drzewo 2x2",
            "Mam 2 koszulki (czerwona, niebieska) i 2 spodnie (czarne, szare). Ile zestawow?",
            {"A":"2","B":"3","C":"4","D":"6","E":"8"},"C"),
         gen(43,"v1","w2","3pkt","kombinatoryka","drzewo 3x2",
            "Mam 3 owoce (jablko, gruszka, banan) i 2 napoje (woda, sok). Ile par owoc+napoj?",
            {"A":"3","B":"5","C":"6","D":"9","E":"12"},"C"),
         gen(43,"v1","w3","3pkt","kombinatoryka","drzewo 2x2x2",
            "Wybieram lody: 2 smaki, 2 dodatki, 2 polewy. Ile kombinacji?",
            {"A":"4","B":"6","C":"8","D":"12","E":"16"},"C"),
         orig(2020,19),
         orig(2022,19)],
        [gen(43,"v1","c1","4pkt","kombinatoryka","drzewo wieloetapowe",
            "Restauracja: 3 zupy, 4 dania glowne, 2 desery. Ile mozliwych obiadow (zupa + danie + deser)?",
            {"A":"9","B":"12","C":"18","D":"24","E":"32"},"D"),
         gen(43,"v1","c2","5pkt","kombinatoryka","drzewo z warunkiem",
            "5 osob staje w rzedzie. Ile mozliwosci ustawienia, jezeli Anka MUSI stac pierwsza?",
            {"A":"4","B":"12","C":"24","D":"60","E":"120"},"C")],
        [sol("gen-l43-v1-w1","2 razy 2 = 4 zestawy.","Iloczyn.",["2 koszulki * 2 spodnie = 4"],"C"),
         sol("gen-l43-v1-w2","3 razy 2 = 6.","Iloczyn.",["3 owoce * 2 napoje = 6"],"C"),
         sol("gen-l43-v1-w3","2*2*2 = 8.","Iloczyn 3 etapow.",["2*2*2=8"],"C"),
         osol("kangur-maluch-2020-19","6 dzieci, smaki: 3 wanilia, 2 czekolada, 1 cytryna. Dodatki: 1 posypka, 2 ciastka, 3 wisnie. Zadne dwoje takiej samej kombinacji. Brakuje: cytrynowych z ciastkiem.","C"),
         osol("kangur-maluch-2022-19","Helenka wybrala figury. 2 zacieniowane, 2 duze, 2 okragle. Minimum 3 figury.","B"),
         sol("gen-l43-v1-c1","3*4*2 = 24.","Iloczyn 3 etapow.",["3*4*2=24"],"D"),
         sol("gen-l43-v1-c2","Anka 1. miejsce, pozostali 4 osoby na 4 miejsca: 4! = 24.","Permutacje pozostalych.",
            ["Anka 1. miejsce (1 sposob)","Reszta 4 osoby na 4 miejscach: 4!=24"],"C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(43,"v2","w1","3pkt","kombinatoryka","podstawowe drzewo",
            "Mam 3 czapki i 2 szaliki. Ile par czapka+szalik?",
            {"A":"3","B":"5","C":"6","D":"9","E":"12"},"C"),
         gen(43,"v2","w2","3pkt","kombinatoryka","trzy etapy",
            "Wybieram zupe (2 rodzaje), danie (3), deser (2). Ile kombinacji?",
            {"A":"6","B":"7","C":"10","D":"12","E":"18"},"D"),
         gen(43,"v2","w3","3pkt","kombinatoryka","ile drog",
            "Z miasta A do B sa 3 drogi, z B do C - 2 drogi. Ile drog z A do C przez B?",
            {"A":"3","B":"5","C":"6","D":"9","E":"12"},"C"),
         gen(43,"v2","w4","3pkt","kombinatoryka","wybor 2 cech",
            "Mam 4 kolory i 3 wzory. Ile roznych ubran (kolor + wzor)?",
            {"A":"7","B":"9","C":"10","D":"12","E":"24"},"D"),
         gen(43,"v2","w5","3pkt","kombinatoryka","prosty wybor",
            "5 ksiazek na polce, biore 1. Ile mozliwosci?",
            {"A":"1","B":"3","C":"5","D":"10","E":"25"},"C")],
        [gen(43,"v2","c1","4pkt","kombinatoryka","warunkowy wybor",
            "3 osoby A, B, C ustawiaja sie w rzedzie. A nie chce stac pierwsza. Ile mozliwosci?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"C"),
         gen(43,"v2","c2","5pkt","kombinatoryka","drzewo z dwoma warunkami",
            "Robot wybiera trase: 2 mozliwosci w kazdym z 4 kroku (lewo lub prawo). Ile roznych tras?",
            {"A":"4","B":"8","C":"16","D":"24","E":"32"},"C")],
        [sol("gen-l43-v2-w1","3*2=6.","Iloczyn.",["3*2=6"],"C"),
         sol("gen-l43-v2-w2","2*3*2=12.","Iloczyn 3 etapow.",["2*3*2=12"],"D"),
         sol("gen-l43-v2-w3","3*2=6.","Iloczyn drog.",["3*2=6"],"C"),
         sol("gen-l43-v2-w4","4*3=12.","Iloczyn.",["4*3=12"],"D"),
         sol("gen-l43-v2-w5","5 mozliwosci.","Wybor 1 z 5.",["5"],"C"),
         sol("gen-l43-v2-c1","Wszystkie 3! = 6, minus te z A pierwsza (2!): 6-2=4.","Wykluczenie.",
            ["Wszystkie permutacje: 3!=6","A pierwsza: B,C w 2 miejscach = 2! = 2","Bez A pierwszej: 6-2=4"],"C"),
         sol("gen-l43-v2-c2","2^4 = 16.","Drzewo dwie galezie kazdy krok.",["2*2*2*2=16"],"C")]),
    [dict(q="2 koszulki * 3 spodnie:",
          choices={"A":"5","B":"6","C":"8"}, correct="B",
          explain="2*3=6 kombinacji."),
     dict(q="Drzewo mozliwosci pomaga:",
          choices={"A":"Liczyc systematycznie","B":"Zgadywac","C":"Pomijac"}, correct="A",
          explain="Drzewo pokazuje wszystkie mozliwosci wizualnie."),
     dict(q="3 etapy, w kazdym 2 wybory:",
          choices={"A":"6","B":"8","C":"9"}, correct="B",
          explain="2*2*2=8.")])
LESSONS.append(l43)

# === LEKCJA 44: Liczenie tras ===
l44 = lesson("l44", 44, "Kombinatoryka i liczenie", "H", "Liczenie tras na siatce", "kombinatoryka", 14,
    "Od domu do szkoly idziesz ulicami siatki: tylko w prawo lub w dol. Na ile sposobow mozesz dojsc? To klasyczne zadanie 'liczenia tras'. Rozwiazanie wymaga systematycznego liczenia mozliwosci.",
    "Sztuczka 1: SIATKA 1xN. Jedna trasa - tylko prosto. Liczenie banalne.\n\nSztuczka 2: SIATKA 2x2. Wypisz wszystkie: prawo-dol, dol-prawo = 2 trasy.\n\nSztuczka 3: WIEKSZE SIATKI - LICZENIE NA SKRZYZOWANIACH. W kazdym skrzyzowaniu wpisz liczbe sposobow dojscia do niego. Sumowanie z gory i lewa.\n\nSztuczka 4: TROJKAT PASCALA. Liczby na skrzyzowaniach tworza znany wzor - trojkat liczb (1, 1+1=2, 1+2+1=3...).",
    "Pulapka: zadania z 'najkrotsza droga' tylko w 2 kierunkach. Jezeli wolno cofac sie, liczba tras moze byc nieskonczona. Czytaj uwaznie - 'najkrotsza' = bez cofania.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(44,"v1","w1","3pkt","kombinatoryka","droga 1x1",
            "Siatka 1x1: z A do B (prawy gorny rog) tylko w prawo lub w dol. Ile drog?",
            {"A":"1","B":"2","C":"3","D":"4","E":"5"},"B"),
         gen(44,"v1","w2","3pkt","kombinatoryka","droga 2x1",
            "Siatka 2x1 (2 w prawo, 1 w dol). Ile najkrotszych drog?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         gen(44,"v1","w3","3pkt","kombinatoryka","droga 2x2",
            "Siatka 2x2 (2 w prawo, 2 w dol). Ile najkrotszych drog?",
            {"A":"4","B":"5","C":"6","D":"7","E":"8"},"C"),
         orig(2016,12),
         orig(2024,19)],
        [orig(2022,24),
         gen(44,"v1","c1","5pkt","kombinatoryka","siatka 3x2",
            "Siatka 3x2 (3 w prawo, 2 w dol). Ile najkrotszych drog?",
            {"A":"6","B":"10","C":"12","D":"15","E":"20"},"B")],
        [sol("gen-l44-v1-w1","Z (0,0) do (1,1): prawo-dol lub dol-prawo.","Wypisanie.",["2 drogi"],"B"),
         sol("gen-l44-v1-w2","2 prawo + 1 dol. Wybor pozycji dolu: 3 mozliwosci.","Pozycja dolu.",
            ["Dol moze byc na pozycji 1, 2 lub 3 z 3 krokow","3 mozliwosci"],"B"),
         sol("gen-l44-v1-w3","Wzor trojkata Pascala C(4,2)=6.","Wzor.",
            ["Z (0,0) do (2,2): 4 kroki, wybor 2 prawo z 4","(4*3)/2 = 6"],"C"),
         osol("kangur-maluch-2016-12","Myszka w labiryncie. 5 roznych drog (kazda raz).","C"),
         osol("kangur-maluch-2024-19","60 dzieci, kamizelki zolto-zielone naprzemiennie, plecaki cyklicznie 3 kolory. Zoltej kamizelce + niebieski plecak: 10.","E"),
         osol("kangur-maluch-2022-24","9 skrzyn z waga 1-17 kg, podzial na 3 grupy po 3 z rownymi sumami. W grupie z 6 kg trafila 9 kg.","D"),
         sol("gen-l44-v1-c1","C(5,2) = 10.","Wzor trojkata.",
            ["3 prawo + 2 dol = 5 krokow","Wybor 2 dolu z 5: (5*4)/2 = 10"],"B")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(44,"v2","w1","3pkt","kombinatoryka","droga 1x2",
            "Siatka 1x2 (1 w prawo, 2 w dol). Ile najkrotszych drog?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         gen(44,"v2","w2","3pkt","kombinatoryka","droga 3x1",
            "Siatka 3x1. Ile najkrotszych drog?",
            {"A":"3","B":"4","C":"5","D":"6","E":"10"},"B"),
         gen(44,"v2","w3","3pkt","kombinatoryka","droga 2x3",
            "Siatka 2x3 (2 prawo, 3 dol). Ile najkrotszych drog?",
            {"A":"5","B":"6","C":"10","D":"15","E":"20"},"C"),
         gen(44,"v2","w4","3pkt","kombinatoryka","prosta zasada",
            "W siatce, najkrotsza droga ma:",
            {"A":"Sumę krokow prawo + dol","B":"Tylko prawo","C":"Tylko dol","D":"Pelne kolo","E":"Dowolny ksztalt"},"A"),
         gen(44,"v2","w5","3pkt","kombinatoryka","jedna droga",
            "Z A do B tylko jedna mozliwa droga. Ile drog?",
            {"A":"0","B":"1","C":"2","D":"3","E":"4"},"B")],
        [gen(44,"v2","c1","4pkt","kombinatoryka","siatka 3x3",
            "Siatka 3x3 (3 prawo, 3 dol). Ile najkrotszych drog?",
            {"A":"6","B":"10","C":"15","D":"20","E":"36"},"D"),
         gen(44,"v2","c2","5pkt","kombinatoryka","liczba pasm",
            "Z 5 dzieci wybieram pare do trzymania sie za rece. Na ile sposobow?",
            {"A":"5","B":"6","C":"8","D":"10","E":"20"},"D")],
        [sol("gen-l44-v2-w1","1 prawo + 2 dol = 3 kroki. Wybor pozycji prawa: 3.","Pozycja prawa.",["3 mozliwosci"],"B"),
         sol("gen-l44-v2-w2","3 kroki prawo, 1 dol. Wybor pozycji dolu z 4: 4.","Wybor dolu.",["4 mozliwosci"],"B"),
         sol("gen-l44-v2-w3","C(5,2)=10.","Wzor.",["5 krokow, wybor 2 prawa: (5*4)/2 = 10"],"C"),
         sol("gen-l44-v2-w4","Suma krokow prawo + dol.","Definicja najkrotszej drogi.",["P + D krokow"],"A"),
         sol("gen-l44-v2-w5","Jedna droga - jedna mozliwosc.","Pojedyncza droga.",["1"],"B"),
         sol("gen-l44-v2-c1","C(6,3)=20.","Wzor.",["6 krokow, wybor 3 dolu z 6: (6*5*4)/(3*2*1) = 20"],"D"),
         sol("gen-l44-v2-c2","C(5,2) = 10 par.","Wybor 2 z 5.",["(5*4)/2 = 10"],"D")]),
    [dict(q="Siatka 2x2 ma drog:",
          choices={"A":"4","B":"6","C":"8"}, correct="B",
          explain="C(4,2)=6."),
     dict(q="Najkrotsza droga w siatce:",
          choices={"A":"Bez cofania","B":"Z cofaniem","C":"Po przekatnej"}, correct="A",
          explain="Najkrotsza = tylko prawo lub dol, bez cofania."),
     dict(q="Liczba drog rosnie z:",
          choices={"A":"Wielkoscia siatki","B":"Iloscia drog","C":"Pogoda"}, correct="A",
          explain="Wieksza siatka = wiecej drog (rosnie szybko).")])
LESSONS.append(l44)

# === LEKCJA 45: Ustawianie i kolory ===
l45 = lesson("l45", 45, "Kombinatoryka i liczenie", "H", "Ustawianie i kolory", "kombinatoryka", 16,
    "Na ile sposobow mozesz pomalowac 3 pola, majac 2 kolory? Na ile sposobow ustawisz 4 osoby tak, by Adas i Bartek byli obok? Te zadania lacza podstawy kombinatoryki z dodatkowymi warunkami - daja Kangurowi mnostwo zabawy.",
    "Sztuczka 1: KOLORY PER POLE. Jezeli kazde pole moze byc dowolnego koloru, mnoz: 2 kolory * 3 pola = 2*2*2=8.\n\nSztuczka 2: WARUNKI SASIEDZTWA. 'Adas i Bartek obok' - traktuj ich jako PARE (jedna jednostka). Permutuj pary z innymi, potem mnoz przez 2 (Adas-Bartek lub Bartek-Adas).\n\nSztuczka 3: KOLO. W kole 'Adas obok B' liczy sie inaczej niz w rzedzie (np. pierwszy i ostatni nie sa obok w rzedzie, ale sa w kole).\n\nSztuczka 4: WYKLUCZENIE. Wszystkie mozliwosci minus te z naruszeniem warunku.",
    "Pulapka: 'rozne kolory sasiednie' - to dodatkowy warunek. Jezeli 3 pola sasiedzi i 2 kolory, to nie da sie pokolorowac wszystkich roznymi. Sprawdz wykonalnosc.",
    ver("v1", "Wersja 1 (oryginalna)",
        [gen(45,"v1","w1","3pkt","kombinatoryka","kolorowanie 2 pola 2 kolory",
            "2 pola, 2 kolory. Ile sposobow pomalowania (kazde pole jakims kolorem)?",
            {"A":"2","B":"3","C":"4","D":"6","E":"8"},"C"),
         gen(45,"v1","w2","3pkt","kombinatoryka","kolorowanie 3 pola 2 kolory",
            "3 pola, 2 kolory. Ile sposobow pomalowania?",
            {"A":"3","B":"5","C":"6","D":"8","E":"9"},"D"),
         gen(45,"v1","w3","3pkt","kombinatoryka","sasiednie razem",
            "Anka i Bartek chca stac obok siebie w rzedzie 3 osob. Ile mozliwosci?",
            {"A":"2","B":"3","C":"4","D":"6","E":"12"},"C"),
         orig(2012,15),
         orig(2014,18)],
        [orig(2015,14),
         orig(2024,21)],
        [sol("gen-l45-v1-w1","2 kolory na 2 pola: 2*2=4.","Mnozenie.",["2*2=4"],"C"),
         sol("gen-l45-v1-w2","2*2*2=8.","Mnozenie 3 etapow.",["2*2*2=8"],"D"),
         sol("gen-l45-v1-w3","Anka-Bartek jako para. Pary z 3 elementami: 2 ulozenia, kazdy *2 (AB lub BA): 2*2=4.","Sasiedztwo.",
            ["3 osoby, Anka i Bartek razem (jako para)","Para + 1 osoba = 2 jednostki, 2! ulozenia = 2","Para moze byc AB lub BA: 2*2=4"],"C"),
         osol("kangur-maluch-2012-15","Laura, Igor, Wiktor, Kasia. Kasia i Laura obok, Igor obok Laury. Bloky: I-L-K lub K-L-I. Wiktor przed lub po. 2*2=4.","B"),
         osol("kangur-maluch-2014-18","7 dzieci w kole. Zadna dziewczynka miedzy dwiema, zaden chlopiec obok innego. 4 dziewczynki.","C"),
         osol("kangur-maluch-2015-14","Bartek 4 zabawki. Statek i samolot obok auta. 4 sposoby.","B"),
         osol("kangur-maluch-2024-21","3x3 siatka, w kazdym rzedzie/kolumnie 2 zaby. Dwie zaby przeskocza zachowujac warunek. 3 sposoby.","C")]),
    ver("v2", "Wersja 2 (powtorka)",
        [gen(45,"v2","w1","3pkt","kombinatoryka","kolorowanie 4 pola 2 kolory",
            "4 pola, 2 kolory. Ile sposobow?",
            {"A":"6","B":"8","C":"12","D":"16","E":"24"},"D"),
         gen(45,"v2","w2","3pkt","kombinatoryka","kolorowanie 3 pola 3 kolory",
            "3 pola, 3 kolory, kazde pole inny kolor. Ile sposobow?",
            {"A":"3","B":"6","C":"9","D":"12","E":"27"},"B"),
         gen(45,"v2","w3","3pkt","kombinatoryka","obok w kole",
            "5 osob w kole. Anka i Bartek obok siebie. Ile mozliwosci ustawienia w kole (uznajemy obroty za to samo)?",
            {"A":"6","B":"8","C":"12","D":"24","E":"48"},"C"),
         gen(45,"v2","w4","3pkt","kombinatoryka","wybor pary",
            "5 dzieci, wybor 2 do tanca (kolejnosc bez znaczenia). Ile par?",
            {"A":"5","B":"6","C":"8","D":"10","E":"20"},"D"),
         gen(45,"v2","w5","3pkt","kombinatoryka","prosty wybor 1 koloru",
            "5 kolorow, wybor 1. Ile mozliwosci?",
            {"A":"1","B":"3","C":"5","D":"10","E":"25"},"C")],
        [gen(45,"v2","c1","4pkt","kombinatoryka","obok kolejnosc",
            "3 chlopcow i 3 dziewczynki staja na przemian (CDCDCD lub DCDCDC). Ile ulozen?",
            {"A":"6","B":"36","C":"72","D":"144","E":"720"},"C"),
         orig(2025,15)],
        [sol("gen-l45-v2-w1","2^4=16.","Mnozenie.",["2*2*2*2=16"],"D"),
         sol("gen-l45-v2-w2","3*2*1=6.","Permutacje.",["3 kolory na 3 pola, kazdy inny: 3!=6"],"B"),
         sol("gen-l45-v2-w3","Para AB jako 1 element w kole 4 elementow: (4-1)!=6. AB lub BA: 6*2=12.","Sasiedztwo w kole.",
            ["Para AB + 3 osoby = 4 jednostki w kole","Kolo z 4: (4-1)!=6","AB lub BA: 6*2=12"],"C"),
         sol("gen-l45-v2-w4","C(5,2)=10.","Wybor 2 z 5.",["(5*4)/2=10"],"D"),
         sol("gen-l45-v2-w5","5.","Wybor 1.",["5"],"C"),
         sol("gen-l45-v2-c1","CDCDCD: 3!*3!=36. DCDCDC: 3!*3!=36. Razem: 72.","Naprzemienne.",
            ["3 chlopcow na pozycjach C: 3!=6","3 dziewczynek na pozycjach D: 3!=6","CDCDCD lub DCDCDC: 2 wzory","2*6*6 = 72"],"C"),
         osol("kangur-maluch-2025-15","6 biedronek po 1-6 kropek, 4 zdjecia po 3 biedronki, kazda na 2 zdjeciach. 4. zdjecie laczna ilosc kropek: 43.","C")]),
    [dict(q="3 pola, 2 kolory:", choices={"A":"6","B":"8","C":"9"}, correct="B",
          explain="2*2*2=8 kombinacji."),
     dict(q="Anka i Bartek obok w rzedzie 3 osob:",
          choices={"A":"2","B":"4","C":"6"}, correct="B",
          explain="Para + 1 osoba = 2! * 2 (AB/BA) = 4."),
     dict(q="Permutacja 4 osob:",
          choices={"A":"16","B":"24","C":"64"}, correct="B",
          explain="4!=4*3*2*1=24.")])
LESSONS.append(l45)

# ====================== ZAPIS ======================
for les in LESSONS:
    with open(f"data/lessons/{les['id']}.json", "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
    print(f"{les['id']}: OK ({les['title']})")
print(f"DONE - {len(LESSONS)} lekcji")
