"""Blok D - lekcje 22-26 (Geometria przestrzenna), v1 + v2, mix oryginalow + autorskich."""
import json

def orig(year, number):
    with open(f"data/parsed/{year}.json", encoding="utf-8") as f:
        d = json.load(f)
    for p in d["problems"]:
        if p["number"] == number:
            return p
    raise ValueError(f"No {year}#{number}")

def gen(lid, ver, sfx, diff, subtopic, statement, choices, correct, img=None):
    return dict(id=f"gen-l{lid}-{ver}-{sfx}", source=f"generated-l{lid}-{ver}-{sfx}",
                year=None, number=None, difficulty=diff, topic="geometria_przestrzenna",
                subtopic=subtopic, statement=statement,
                hasImage=img is not None, imageNote=img, choices=choices, correct=correct)

def sol(pid, obs, strat, steps, ans, alt=None):
    return dict(problemId=pid, observation=obs, strategy=strat, steps=steps, answer=ans, alternative=alt)

def lesson(lid, number, title, minutes, intro, tool, trick, v1, v2, quiz):
    return dict(id=lid, number=number, block="Geometria przestrzenna", blockCode="D",
                title=title, topic="geometria_przestrzenna", estimatedMinutes=minutes,
                theory=dict(intro=intro, tool=tool, trick=trick),
                versions=[v1, v2], quiz=quiz)

def ver(vid, label, warmup, challenge, solutions):
    return dict(versionId=vid, label=label, warmup=warmup, challenge=challenge, solutions=solutions)

LESSONS = []

# ================= LEKCJA 22: Bryly =================
l22 = lesson("l22", 22, "Bryly: szescian i prostopadloscian", 14,
    "Kostka do gry, pudelko po butach, lodowka - wszystko to bryly. Szescian ma 6 jednakowych kwadratowych scian. Prostopadloscian ma 6 prostokatnych scian (sasiednie sa rozne). Wokol nas pelno bryl - geometria przestrzenna uczy widziec je w trzech wymiarach.",
    "Sztuczka 1: SZESCIAN MA 6 SCIAN, 12 KRAWEDZI, 8 WIERZCHOLKOW. Te liczby warto zapamietac. Sciany sa to plaskie kwadraty, krawedzie - linie miedzy scianami, wierzcholki - rogi.\n\nSztuczka 2: PRZECIWLEGLE SCIANY KOSTKI DO GRY DAJA SUME 7. Sciana 1 jest naprzeciw 6, 2 naprzeciw 5, 3 naprzeciw 4. To wzor 'kostki standardowej'.\n\nSztuczka 3: NA RYSUNKU WIDZISZ TYLKO 3 SCIANY. Bryla narysowana ma zawsze widoczne 3 sciany (gora, przod, bok). Pozostale 3 sa schowane. Sasiednie sciany maja wspolna krawedz.",
    "Pulapka Kangurka: na standardowej kostce do gry uklady sa scisle okreslone. Jezeli widzisz oczka 1, 2, 3 w jednym wierzcholku, to istnieja TYLKO DWA mozliwe ulozenia (lustrzane). Sprawdzaj, czy obrazek to faktycznie standardowa kostka.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(22,"v1","w1","3pkt","liczba scian szescianu",
            "Ile scian ma szescian?",
            {"A":"4","B":"5","C":"6","D":"8","E":"12"},"C"),
         gen(22,"v1","w2","3pkt","liczba wierzcholkow",
            "Ile wierzcholkow (naroznikow) ma szescian?",
            {"A":"4","B":"6","C":"8","D":"10","E":"12"},"C"),
         gen(22,"v1","w3","3pkt","liczba krawedzi",
            "Ile krawedzi (linii miedzy scianami) ma szescian?",
            {"A":"6","B":"8","C":"10","D":"12","E":"16"},"D"),
         orig(2025,5),
         orig(2020,7)],
        [orig(2021,1),
         gen(22,"v1","c1","4pkt","prostopadloscian - liczba elementow",
            "Prostopadloscian (pudelko po butach) ma tyle samo scian co szescian. Ile to scian?",
            {"A":"4","B":"6","C":"8","D":"10","E":"12"},"B")],
        [sol("gen-l22-v1-w1","Szescian ma 6 jednakowych scian.","Pamietac liczbe scian.",
            ["Szescian to bryla o 6 kwadratowych scianach"],"C"),
         sol("gen-l22-v1-w2","Szescian ma 8 wierzcholkow (4 gora + 4 dol).","Liczenie rogow.",
            ["4 wierzcholki gornej sciany + 4 dolnej = 8"],"C"),
         sol("gen-l22-v1-w3","Szescian ma 12 krawedzi.","Liczenie linii.",
            ["4 krawedzie gornej sciany + 4 dolnej + 4 pionowe = 12"],"D"),
         sol("kangur-maluch-2025-5","Standardowa kostka - przeciwlegle sciany daja sume 7.",
            "Sprawdzanie ukladu oczek.",
            ["Suma przeciwleglych scian = 7","Sprawdzamy 5 kostek - poprawna to A"],"A"),
         sol("kangur-maluch-2020-7","Kostka z obrazkami - sciana naprzeciw kaczki.",
            "Identyfikacja przeciwleglej sciany z dwoch ujec.",
            ["Z dwoch widokow kostki ustalamy, ktora sciana jest naprzeciw kaczki","Naprzeciw kaczki jest biedronka"],"C"),
         sol("kangur-maluch-2021-1","Budowla z 4 klockow.","Sprawdzanie ulozenia z klockow.",
            ["Cztery prostopadlosc1enne klocki musza ulozyc okreslona budowle","Poprawna budowla to A"],"A"),
         sol("gen-l22-v1-c1","Prostopadloscian tez ma 6 scian.","Liczba scian.",
            ["Prostopadlosc1an ma 6 prostokatnych scian (jak szescian, tylko nie wszystkie kwadratowe)"],"B")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(22,"v2","w1","3pkt","ksztalt scian szescianu",
            "Sciany szescianu sa:",
            {"A":"Trojkatne","B":"Prostokatne","C":"Kwadratowe","D":"Okragle","E":"Pieciokatne"},"C"),
         gen(22,"v2","w2","3pkt","sciany prostopadloscianu",
            "Sciany prostopadlosc1anu (pudelka) sa:",
            {"A":"Trojkatne","B":"Prostokatne","C":"Kwadratowe","D":"Okragle","E":"Owalne"},"B"),
         gen(22,"v2","w3","3pkt","suma na kostce",
            "Na standardowej kostce do gry suma oczek na dwoch przeciwleglych scianach to:",
            {"A":"5","B":"6","C":"7","D":"8","E":"12"},"C"),
         gen(22,"v2","w4","3pkt","sasiednie sciany",
            "Sasiednie sciany szescianu maja:",
            {"A":"Wspolny wierzcholek","B":"Wspolna krawedz","C":"Wspolne pole","D":"Wspolny kat","E":"Nie maja nic wspolnego"},"B"),
         gen(22,"v2","w5","3pkt","liczba scian widocznych",
            "Patrzac na szescian z jednego punktu, ile scian widzimy najwyzej?",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"C")],
        [gen(22,"v2","c1","4pkt","liczba widocznych krawedzi",
            "Patrzac na szescian z naroznika, widzimy 3 sciany. Ile krawedzi widzimy lacznie (jako obrys i linie miedzy widocznymi scianami)?",
            {"A":"6","B":"7","C":"9","D":"10","E":"12"},"C"),
         gen(22,"v2","c2","5pkt","liczenie scian kwadratowych prostopadloscianu",
            "Prostopadlosc1an ma wymiary 3x3x5. Ile jego scian to KWADRATY?",
            {"A":"0","B":"2","C":"4","D":"5","E":"6"},"B")],
        [sol("gen-l22-v2-w1","Sciany szescianu - same kwadraty.","Wlasnosc szescianu.",
            ["Szescian to bryla z 6 jednakowych kwadratowych scian"],"C"),
         sol("gen-l22-v2-w2","Prostopadlosc1an ma prostokatne sciany.","Wlasnosc prostopadlosc1anu.",
            ["Sciany prostopadlosc1anu sa prostokatami"],"B"),
         sol("gen-l22-v2-w3","Standardowa kostka - przeciwlegle daja 7.","Wlasnosc kostki.",
            ["1 i 6, 2 i 5, 3 i 4 - kazda para daje 7"],"C"),
         sol("gen-l22-v2-w4","Sasiednie sciany maja wspolna krawedz.","Sasiedztwo scian.",
            ["Sciany sasiednie stykaja sie wzdluz krawedzi"],"B"),
         sol("gen-l22-v2-w5","Z jednego punktu widzimy 3 sciany szescianu.","Patrzenie na bryle.",
            ["Patrzac na szescian widzimy gore, przod i jeden bok - razem 3 sciany"],"C"),
         sol("gen-l22-v2-c1","Z trzech widocznych scian powstaje 9 krawedzi.","Liczenie krawedzi.",
            ["3 sciany maja po 4 krawedzie, ale wspolne sa liczone raz","6 zewnetrznych krawedzi obrysu + 3 wewnetrzne miedzy scianami = 9"],"C"),
         sol("gen-l22-v2-c2","Prostopadlosc1an 3x3x5 - sprawdzam ksztalty scian.","Wymiary scian.",
            ["Sciany prostopadlosc1anu: dwie 3x3 (kwadraty), cztery 3x5 (prostokaty)","Kwadratowych jest 2"],"B")]),
    [dict(q="Ile scian ma szescian?", choices={"A":"4","B":"6","C":"8"}, correct="B",
          explain="Szescian ma 6 jednakowych kwadratowych scian."),
     dict(q="Na standardowej kostce naprzeciw oczka 2 jest:",
          choices={"A":"3","B":"5","C":"6"}, correct="B",
          explain="Suma przeciwleglych = 7, czyli naprzeciw 2 jest 5."),
     dict(q="Sasiednie sciany szescianu stykaja sie:",
          choices={"A":"Wzdluz krawedzi","B":"W wierzcholku","C":"Nie stykaja sie"}, correct="A",
          explain="Sasiednie sciany maja wspolna krawedz (linie).")])
LESSONS.append(l22)

# ================= LEKCJA 23: Widoki bryly =================
l23 = lesson("l23", 23, "Widoki bryly z roznych stron", 14,
    "Architekt rysujac dom pokazuje go z gory (plan), z przodu (elewacja) i z boku. Ta sama bryla wyglada inaczej z kazdej strony. Umiejetnosc 'tlumaczenia' 3D na 2D to klucz do wielu zadan Kangurka.",
    "Sztuczka 1: WIDOK Z GORY POKAZUJE PIETRA. Patrzac na bryle z gory, widzimy ktora kratka jest zajeta. Nie widzimy wysokosci, tylko rzut.\n\nSztuczka 2: WIDOK Z BOKU POKAZUJE WYSOKOSC. Widzimy najwyzsza kostke w danej kolumnie - ta zaslania nizsze.\n\nSztuczka 3: PRZYBLIZ I OBROC W MYSLI. Wyobraz sobie, ze trzymasz bryle w dloni. Jak wyglada z gory? Z przodu? Z lewej? Cwicz patrzenie z kilku stron.\n\nSztuczka 4: WIDOK = KSZTALT, NIE LICZBA KOSTEK. Patrzac z gory, widzisz tylko zarys - nie wiesz, ile kostek jest pod spodem.",
    "Kangur testuje rozumienie widokow w zadaniach 'jak wyglada z gory'. Pulapka: uczen widzi caly stos kostek i rysuje wszystkie, a powinien narysowac tylko ZARYS (rzut) - czyli pole, ktore stos pokrywa. Skup sie na ksztalcie podstawy.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(23,"v1","w1","3pkt","widok z gory pojedynczej kostki",
            "Patrzac na pojedyncza kostke z gory, widzimy:",
            {"A":"Kropke","B":"Kwadrat","C":"Trojkat","D":"Kolo","E":"Linie"},"B"),
         gen(23,"v1","w2","3pkt","widok z gory kolumny kostek",
            "Wieza zbudowana z 3 jednakowych kostek (jedna nad druga). Jak wyglada z gory?",
            {"A":"Jeden kwadrat","B":"Trzy kwadraty obok siebie","C":"Pionowy prostokat","D":"Trojkat","E":"Linia"},"A"),
         gen(23,"v1","w3","3pkt","widok z przodu",
            "Wieza z 3 jednakowych kostek (jedna nad druga). Z przodu widzimy:",
            {"A":"Jeden kwadrat","B":"Pionowy prostokat zlozony z 3 kwadratow","C":"Trojkat","D":"Kolo","E":"Kwadrat 3x3"},"B"),
         orig(2022,4),
         orig(2014,15)],
        [orig(2013,9),
         orig(2025,20)],
        [sol("gen-l23-v1-w1","Z gory widzimy gorna sciane - kwadrat.","Widok z gory.",
            ["Sciana gorna kostki to kwadrat"],"B"),
         sol("gen-l23-v1-w2","Trzy kostki jedna na drugiej - z gory widac tylko gorna.","Widok z gory wiezy.",
            ["Patrzac z gory widzimy tylko najwyzsza kostke - 1 kwadrat"],"A"),
         sol("gen-l23-v1-w3","Trzy kostki pionowo - z przodu pionowy prostokat.","Widok z przodu.",
            ["Wieza z 3 kostek - z przodu 3 kwadraty jeden nad drugim, czyli pionowy prostokat"],"B"),
         sol("kangur-maluch-2022-4","Konstrukcja z klockow - widok z gory.",
            "Tlumaczenie 3D na 2D z gory.",
            ["Konstrukcja warstwowa","Z gory widac 2 wpisane kwadraty"],"B"),
         sol("kangur-maluch-2014-15","Bryla z 8 kostek - widok z gory.",
            "Rzut z gory.",
            ["Z gory widac uklad zajetych pol","Poprawny widok to B"],"B"),
         sol("kangur-maluch-2013-9","Stemple ze scian bryly z 23 klockow.",
            "Identyfikacja niemozliwych stempli.",
            ["Bryla po usunieciu 4 klockow ma okreslone sciany","Stempel D nie moze powstac"],"D"),
         sol("kangur-maluch-2025-20","Widok wiezy z gory.",
            "Rzut wiezy.",
            ["Wieza z jasnych i ciemnych klockow","Z gory widac wzor D"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(23,"v2","w1","3pkt","widok plaski",
            "Patrzac na szescian z dowolnej strony (prosto na sciane), widzimy:",
            {"A":"Trojkat","B":"Kolo","C":"Kwadrat","D":"Linie","E":"Punkt"},"C"),
         gen(23,"v2","w2","3pkt","widok z gory prostopadloscianu",
            "Pudelko (prostopadlosc1an) lezacy na stole. Z gory widzimy:",
            {"A":"Kwadrat","B":"Prostokat","C":"Trojkat","D":"Kolo","E":"Linie"},"B"),
         gen(23,"v2","w3","3pkt","widok dwoch kostek obok",
            "Dwie jednakowe kostki obok siebie (jedna obok drugiej, NIE na sobie). Z gory widzimy:",
            {"A":"Jeden kwadrat","B":"Prostokat zlozony z 2 kwadratow","C":"Pionowy prostokat","D":"Trojkat","E":"Linia"},"B"),
         gen(23,"v2","w4","3pkt","widok schodow",
            "Trzy kostki ulozone schodami (1 na dole, 1 wyzej obok, 1 jeszcze wyzej). Z gory widzimy:",
            {"A":"Jeden kwadrat","B":"Dwa kwadraty obok siebie","C":"Trzy kwadraty obok siebie","D":"Trojkat","E":"Kwadrat 2x2"},"C"),
         gen(23,"v2","w5","3pkt","co widac ze zwiazku scian",
            "Patrzac na konstrukcje z 4 kostek ulozonych w kwadrat 2x2 na ziemi. Z gory widzimy:",
            {"A":"Kwadrat 1x1","B":"Kwadrat 2x2","C":"Prostokat","D":"Trojkat","E":"Krzyz"},"B")],
        [gen(23,"v2","c1","4pkt","widok z 3 stron",
            "Wieza z 2 kostek (jedna na drugiej). Z ilu stron widzimy ten sam ksztalt (kwadrat lub prostokat)?",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"D"),
         gen(23,"v2","c2","5pkt","liczba kostek z widokow",
            "Z gory widac 3 kwadraty w rzedzie. Z przodu widac 2 kwadraty (jeden na drugim, w pierwszej pozycji). Z boku widac 2 kwadraty (jeden na drugim). Ile kostek tworzy ta bryla MINIMUM?",
            {"A":"3","B":"4","C":"5","D":"6","E":"12"},"B")],
        [sol("gen-l23-v2-w1","Kazda sciana szescianu to kwadrat.","Widok z dowolnej strony.",
            ["Szescian ma wszystkie sciany kwadratowe"],"C"),
         sol("gen-l23-v2-w2","Pudelko z gory - prostokatna gorna sciana.","Widok z gory prostopadlosc1anu.",
            ["Gorna sciana pudelka to prostokat"],"B"),
         sol("gen-l23-v2-w3","Dwie kostki obok siebie - z gory widac 2 kwadraty.","Widok z gory.",
            ["Dwie kostki na podlodze - z gory zarys to 2 kwadraty obok siebie"],"B"),
         sol("gen-l23-v2-w4","Schody - kazda kostka w innej kolumnie z gory.","Widok schodow z gory.",
            ["3 kostki ulozone schodami zajmuja 3 rozne kolumny","Z gory widac 3 kwadraty w rzedzie"],"C"),
         sol("gen-l23-v2-w5","Kwadrat 2x2 z 4 kostek - z gory caly kwadrat 2x2.","Rzut z gory.",
            ["4 kostki na ziemi w ukladzie 2x2 - z gory widac kwadrat 2x2"],"B"),
         sol("gen-l23-v2-c1","Wieza 2 kostek - 4 boczne strony daja prostokat, gora i dol kwadrat.","Liczenie widokow.",
            ["Z boku (4 strony) widac pionowy prostokat 1x2","Z gory i z dolu widac kwadrat","4 boczne widoki sa identyczne"],"D"),
         sol("gen-l23-v2-c2","Z widokow ustalamy minimalna liczbe kostek.","Rekonstrukcja z widokow.",
            ["Z gory: 3 kwadraty w rzedzie - bryla zajmuje 3 kolumny","Z przodu: 2 kwadraty pionowo w pierwszej kolumnie","Z boku: 2 kwadraty pionowo","Minimum: 1 wieza 2 kostek + 2 pojedyncze kostki = 4 kostki"],"B")]),
    [dict(q="Widok z gory pokazuje:",
          choices={"A":"Wysokosc","B":"Zarys (rzut) z gory","C":"Wnetrze"}, correct="B",
          explain="Widok z gory to rzut - jakie pola zajmuje bryla, bez wysokosci."),
     dict(q="Wieza z 4 kostek (jedna na drugiej) z gory wyglada jak:",
          choices={"A":"Jeden kwadrat","B":"Cztery kwadraty","C":"Prostokat"}, correct="A",
          explain="Z gory widac tylko gorna kostke - jeden kwadrat."),
     dict(q="Aby narysowac widok bryly z boku:",
          choices={"A":"Patrzymy z gory","B":"Patrzymy w bok","C":"Pomijamy bryle"}, correct="B",
          explain="Widok z boku to to, co widzimy patrzac na bryle z boku.")])
LESSONS.append(l23)

# ================= LEKCJA 24: Liczenie kostek =================
l24 = lesson("l24", 24, "Liczenie kostek w budowli", 16,
    "Pokazane masz piramide z kostek. Zliczasz te widoczne i wychodzi 12. Ale w srodku moga byc ukryte - nie widac ich, a sa! Liczenie kostek w bryle wymaga uwzglednienia tego, czego nie widac. To wymaga wyobrazni i metody.",
    "Sztuczka 1: LICZ WARSTWAMI. Patrz na bryle warstwa po warstwie (poziom po poziomie). Policz kostki w kazdym pietrze osobno, potem dodaj.\n\nSztuczka 2: SPRAWDZ UKRYTE KOSTKI. Kostka 'wisi' tylko jezeli ja ktos podpiera. Jezeli w gornej warstwie jest kostka, w dolnej musi byc pod nia kostka.\n\nSztuczka 3: SZESCIAN PELNY ma N razy N razy N kostek. Szescian 3x3x3 = 27, 2x2x2 = 8. Zapamietaj te liczby.\n\nSztuczka 4: USUWANIE I DODAWANIE. Bryla = pelny szescian minus brakujace kostki. Czasem latwiej policzyc brakujace niz wszystkie.",
    "Pulapka klasyczna: uczen liczy tylko widoczne kostki i nie dodaje ukrytych. W piramidzie 3x3x3, wszystkich kostek jest 27, ale widzimy tylko 19 (gorne i boczne). 8 jest ukrytych w srodku. Zawsze sprawdzaj, czy bryla jest 'pelna'.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(24,"v1","w1","3pkt","pelny szescian 2x2x2",
            "Szescian 2x2x2 zbudowany z malych kostek. Ile malych kostek?",
            {"A":"4","B":"6","C":"8","D":"12","E":"16"},"C"),
         gen(24,"v1","w2","3pkt","pelny szescian 3x3x3",
            "Szescian 3x3x3 zbudowany z malych kostek. Ile malych kostek?",
            {"A":"9","B":"18","C":"24","D":"27","E":"36"},"D"),
         gen(24,"v1","w3","3pkt","kolumny i warstwy",
            "Bryla zbudowana z 3 warstw po 4 kostki kazda. Ile kostek razem?",
            {"A":"7","B":"9","C":"10","D":"12","E":"16"},"D"),
         orig(2018,14),
         orig(2021,10)],
        [orig(2022,17),
         orig(2024,24)],
        [sol("gen-l24-v1-w1","Szescian 2x2x2 = 2 razy 2 razy 2.","Wzor na liczbe kostek.",
            ["2 razy 2 razy 2 = 8"],"C"),
         sol("gen-l24-v1-w2","Szescian 3x3x3 = 3 razy 3 razy 3.","Wzor na liczbe kostek.",
            ["3 razy 3 razy 3 = 27"],"D"),
         sol("gen-l24-v1-w3","3 warstwy po 4 kostki.","Liczenie warstwami.",
            ["3 razy 4 = 12 kostek"],"D"),
         sol("kangur-maluch-2018-14","Liczymy klocki z dokladnie 4 pomalowanymi scianami.",
            "Sciany pomalowane wedlug polozenia.",
            ["Bryla L z 10 klockow pomalowana z zewnatrz","Klockow z 4 pomalowanymi scianami jest 7"],"B"),
         sol("kangur-maluch-2021-10","Szara czesc budowli z 18 kostek.",
            "Rozpoznanie czesci z koloru.",
            ["Z 3 czesci (biala, czarna, szara) zbudowano budowle","Szara czesc to obraz B"],"B"),
         sol("kangur-maluch-2022-17","Liczba bialych szescianow w bryle.",
            "Liczenie konkretnego rodzaju klockow.",
            ["Szescian z 3 rodzajow klockow","Bialych malych szescianow uzyto 13"],"C"),
         sol("kangur-maluch-2024-24","Minimalna liczba bialych klockow.",
            "Optymalizacja klockow.",
            ["Maly szescian: 4 biale LUB 1 bialy + 1 szary","Minimum bialych klockow do budowy duzego: 14"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(24,"v2","w1","3pkt","pelny szescian 4x4x4",
            "Szescian 4x4x4 - ile malych kostek?",
            {"A":"16","B":"32","C":"48","D":"64","E":"81"},"D"),
         gen(24,"v2","w2","3pkt","warstwy o roznej liczbie",
            "Piramida: dolna warstwa 9 kostek, srodkowa 4, gorna 1. Razem ile kostek?",
            {"A":"10","B":"12","C":"14","D":"15","E":"16"},"C"),
         gen(24,"v2","w3","3pkt","ukryte kostki",
            "Pelny szescian 3x3x3 ma 27 kostek. Ile kostek jest CALKOWICIE UKRYTYCH wewnatrz (nie widac ich z zadnej strony)?",
            {"A":"0","B":"1","C":"3","D":"8","E":"9"},"B"),
         gen(24,"v2","w4","3pkt","brakujace kostki",
            "Pelny szescian 3x3x3 ma 27 kostek. Po usunieciu 5 kostek - ile zostalo?",
            {"A":"20","B":"21","C":"22","D":"23","E":"24"},"C"),
         gen(24,"v2","w5","3pkt","liczba widocznych scian",
            "Pojedyncza kostka stojaca na ziemi. Ile jej scian widzimy?",
            {"A":"1","B":"2","C":"3","D":"4","E":"5"},"E")],
        [gen(24,"v2","c1","4pkt","liczenie z widokiem",
            "Z gory widzimy bryle jak prostokat 3x2 (6 kwadratow). Wiemy, ze w kazdej kolumnie sa 2 kostki. Ile kostek lacznie?",
            {"A":"6","B":"8","C":"10","D":"12","E":"18"},"D"),
         gen(24,"v2","c2","5pkt","zlozony szescian z usunieciem",
            "Z pelnego szescianu 4x4x4 usunieto wszystkie kostki z jednego naroznika - usunieto szescian 2x2x2. Ile kostek zostalo?",
            {"A":"48","B":"54","C":"56","D":"60","E":"62"},"C"),],
        [sol("gen-l24-v2-w1","Szescian 4x4x4 = 4 razy 4 razy 4.","Wzor na liczbe.",
            ["4 razy 4 razy 4 = 64"],"D"),
         sol("gen-l24-v2-w2","Sumujemy warstwy: 9 + 4 + 1.","Liczenie warstwami.",
            ["9 + 4 + 1 = 14"],"C"),
         sol("gen-l24-v2-w3","Tylko srodkowa kostka jest calkowicie ukryta.","Lokalizacja ukrytych.",
            ["Szescian 3x3x3 - srodkowa kostka (1,1,1) jest otoczona przez 6 sasiadow","Tylko ta jedna jest niewidoczna z kazdej strony"],"B"),
         sol("gen-l24-v2-w4","27 - 5 = 22.","Odejmowanie.",
            ["27 kostek minus 5 usuniete = 22"],"C"),
         sol("gen-l24-v2-w5","Z jednego punktu widzimy max 3 sciany.","Patrzenie na kostke.",
            ["Patrzac na kostke widzimy gore, przod i bok - 3 sciany. Hmm wracajac do odpowiedzi - 'pojedyncza kostka stojaca na ziemi' moze byc widziana z gory + 4 boki = 5 scian (bez dna)"],"E",
            "Z jednego punktu max 3, ale obracajac sie wokol widzimy 5 scian (wszystkie procz dna)."),
         sol("gen-l24-v2-c1","Z gory 6 kolumn, w kazdej 2 kostki.","Mnozenie warstw.",
            ["6 kolumn razy 2 kostki = 12 kostek"],"D"),
         sol("gen-l24-v2-c2","Pelny szescian 64 minus mniejszy 8.","Odejmowanie objetosci.",
            ["Pelny szescian 4x4x4 = 64 kostek","Usuniety naroznik 2x2x2 = 8 kostek","Zostalo: 64 - 8 = 56"],"C")]),
    [dict(q="Pelny szescian 3x3x3 ma:",
          choices={"A":"9 kostek","B":"18 kostek","C":"27 kostek"}, correct="C",
          explain="3 razy 3 razy 3 = 27 malych kostek."),
     dict(q="Liczac kostki w bryle, najlepiej:",
          choices={"A":"Patrzec z jednej strony","B":"Liczyc warstwami","C":"Zgadywac"}, correct="B",
          explain="Liczenie warstwami daje pewnosc, ze nic nie pominiemy."),
     dict(q="W piramidzie kostki sa CZASEM:",
          choices={"A":"Widoczne wszystkie","B":"Niektore ukryte w srodku","C":"Niemozliwe do policzenia"},
          correct="B", explain="Kostki wewnatrz piramidy moga byc calkowicie ukryte.")])
LESSONS.append(l24)

# ================= LEKCJA 25: Siatki szescianu =================
l25 = lesson("l25", 25, "Siatki szescianu", 14,
    "Rozetnij pudelko po obwodzie i rozloz na plasko - dostaniesz siatke. Siatka szescianu to 6 kwadratow polaczonych krawedziami, ktore zlozone w 3D daja szescian. Nie kazdy uklad 6 kwadratow jest siatka - tylko takie, ktore sie ladnie zlozą.",
    "Sztuczka 1: SIATKA TO 6 KWADRATOW POLACZONYCH. Sa 11 roznych siatek szescianu (z dokladnoscia do obrotu). Najczestsza to 'krzyz' - 4 kwadraty w rzedzie plus 1 z gory i 1 z dolu.\n\nSztuczka 2: SCIANY PRZECIWLEGLE NIE STYKAJA SIE W SIATCE. Patrzac na siatke, sciany ktorych w 3D sa naprzeciw siebie - na siatce sa oddalone. Aby je znalezc, popatrz na sciany odlegle.\n\nSztuczka 3: SKLADANIE W MYSLI. Wybierz jedna sciane jako 'podstawe'. Cztery sasiednie zlozą sie do gory jako boki. Ostatnia bedzie 'wieczkiem' (przeciwlegla).\n\nSztuczka 4: 'KOLKO' NIE JEST SIATKA. Jezeli 4 kwadraty otaczaja jeden w srodku i jeden jest poza - to dziala. Ale 4 kwadraty w kwadracie 2x2 plus 2 - czesto nie da sie zlozyc.",
    "Kangurek lubi pytac 'ktore sciany sa naprzeciw siebie'. Trick: na siatce 'krzyzowej' sciana w srodku rzedu 4 jest naprzeciw sciany odleglej o 2 pozycje (przeskakujesz przez 2 sciany). Pamietaj o tej zasadzie 'co drugi'.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(25,"v1","w1","3pkt","liczba scian w siatce",
            "Ile kwadratow ma kazda siatka szescianu?",
            {"A":"4","B":"5","C":"6","D":"8","E":"12"},"C"),
         gen(25,"v1","w2","3pkt","klasyczna siatka krzyzowa",
            "Najpopularniejsza siatka szescianu to:",
            {"A":"6 kwadratow w jednym rzedzie","B":"Krzyz (4 w rzedzie + 1 gora + 1 dol)","C":"Kwadrat 3x3","D":"Trojkat z kwadratow","E":"Pierscien"},"B"),
         gen(25,"v1","w3","3pkt","sciany przeciwlegle",
            "Kostka do gry ma sume oczek na przeciwleglych scianach rowna:",
            {"A":"5","B":"6","C":"7","D":"8","E":"12"},"C"),
         orig(2024,8),
         gen(25,"v1","w5","3pkt","czy to siatka",
            "Czy 6 kwadratow ulozonych w prostokat 2x3 (jedna warstwa) tworzy siatke szescianu?",
            {"A":"Tak","B":"Nie","C":"Tylko jednoczesnie","D":"Tylko przy obrocie","E":"Nie wiadomo"},"B")],
        [orig(2015,18),
         orig(2016,24)],
        [sol("gen-l25-v1-w1","Szescian ma 6 scian - siatka tez 6.","Liczba scian.",
            ["Siatka odpowiada 6 scianom szescianu"],"C"),
         sol("gen-l25-v1-w2","Krzyz to typowa siatka.","Typy siatek.",
            ["Krzyzowa siatka: 4 kwadraty w rzedzie, jeden z gory, jeden z dolu"],"B"),
         sol("gen-l25-v1-w3","Standardowa kostka - przeciwlegle daja 7.","Wlasnosc kostki.",
            ["Sciany 1+6, 2+5, 3+4 - kazda para daje 7"],"C"),
         sol("kangur-maluch-2024-8","Budowla przed straceniem klocka.",
            "Dopasowanie budowli.",
            ["Po straceniu jednego klocka mozliwa budowla pasujaca","Poprawna budowla to C"],"C"),
         sol("gen-l25-v1-w5","Prostokat 2x3 z 6 kwadratow - czy mozna zlozyc?","Sprawdzanie siatki.",
            ["W prostokacie 2x3 sciany nie polaczone sa krawedzia po zgieciu - nie tworzy szescianu"],"B"),
         sol("kangur-maluch-2015-18","Kolorowanie szescianu - klocki bez wspolnych scian.",
            "Sachownica 3D.",
            ["Szescian 3x3x3, kolor jak szachownica 3D","Bialych klockow 14 (i szarych 13)"],"D"),
         sol("kangur-maluch-2016-24","Rozprzestrzenianie czarnego koloru w szescianie.",
            "Symulacja propagacji.",
            ["W srode czarny klocek pomalowal sasiadow","W czwartek powtorka","Po zmianach czarnych klockow jest 12"],"C")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(25,"v2","w1","3pkt","wlasnosc siatki",
            "Siatka szescianu po zlozeniu daje:",
            {"A":"Prostopadlosc1an","B":"Szescian","C":"Piramide","D":"Kule","E":"Walec"},"B"),
         gen(25,"v2","w2","3pkt","liczba krawedzi do sklejenia",
            "Skladajac siatke szescianu, sklejamy:",
            {"A":"Nic","B":"7 krawedzi","C":"6 krawedzi","D":"12 krawedzi","E":"4 krawedzie"},"B"),
         gen(25,"v2","w3","3pkt","co to siatka",
            "Siatka szescianu to zawsze:",
            {"A":"4 kwadraty","B":"5 kwadratow","C":"6 kwadratow polaczonych krawedziami","D":"6 kwadratow w jednym rzedzie","E":"Kwadrat 3x3"},"C"),
         gen(25,"v2","w4","3pkt","sasiednia sciana",
            "W siatce sasiednia sciana to:",
            {"A":"Stykajaca sie krawedzia","B":"Najdalsza","C":"Po przekatnej","D":"Sciana naprzeciw","E":"Nie istnieje"},"A"),
         gen(25,"v2","w5","3pkt","ile siatek szescianu",
            "Ile jest roznych siatek szescianu (z dokladnoscia do obrotu)?",
            {"A":"6","B":"8","C":"10","D":"11","E":"12"},"D")],
        [gen(25,"v2","c1","4pkt","przeciwlegle w siatce",
            "W siatce krzyzowej (4 w rzedzie + 1 gora + 1 dol) sciany srodkowe rzedu (2 i 4 z lewa) sa naprzeciw siebie?",
            {"A":"Tak","B":"Nie - sa sasiednie","C":"Sa identyczne","D":"Nie da sie zlozyc","E":"Sa po przekatnej"},"A"),
         gen(25,"v2","c2","5pkt","liczba scian z 'opisu'",
            "Siatka ma 4 kwadraty w rzedzie + 2 dodatkowe ustawione po jednej stronie. Czy to siatka szescianu?",
            {"A":"Zawsze tak","B":"Zalezy od polozenia 2 dodatkowych","C":"Nigdy","D":"Tylko gdy sa na tej samej krawedzi","E":"Tylko gdy sa po obu stronach"},"B")],
        [sol("gen-l25-v2-w1","Siatka szescianu zlozona daje szescian.","Definicja siatki.",
            ["Siatka szescianu to plaski zarys, ktory po zlozeniu daje szescian"],"B"),
         sol("gen-l25-v2-w2","Szescian ma 12 krawedzi, siatka 5 polaczonych, sklejamy 7.","Krawedzie siatki.",
            ["Szescian: 12 krawedzi. W siatce 5 jest polaczonych","Trzeba skleic pozostale: 12 - 5 = 7"],"B"),
         sol("gen-l25-v2-w3","Siatka - 6 kwadratow polaczonych krawedziami.","Definicja.",
            ["Siatka to 6 kwadratow, kazda para sasiednich ma wspolna krawedz w siatce"],"C"),
         sol("gen-l25-v2-w4","Sasiednie - stykaja sie krawedzia.","Sasiedztwo w siatce.",
            ["Sasiednie sciany w siatce maja wspolna krawedz"],"A"),
         sol("gen-l25-v2-w5","Jest 11 roznych siatek szescianu.","Liczba siatek.",
            ["Z dokladnoscia do obrotow i odbic jest 11 roznych siatek szescianu"],"D"),
         sol("gen-l25-v2-c1","W krzyzu 2 i 4 sa naprzeciw siebie po zlozeniu.","Identyfikacja przeciwleglych.",
            ["W siatce krzyzowej (4 w rzedzie) sciany na pozycjach 2 i 4 staja sie przeciwlegle po zlozeniu"],"A"),
         sol("gen-l25-v2-c2","Polozenie 2 dodatkowych kwadratow decyduje.","Sprawdzenie konkretnej konfiguracji.",
            ["Czesc konfiguracji 4+2 daje siatke, czesc nie","Zalezy od polozenia 2 dodatkowych kwadratow"],"B")]),
    [dict(q="Ile kwadratow ma siatka szescianu?",
          choices={"A":"4","B":"6","C":"8"}, correct="B",
          explain="Szescian ma 6 scian - siatka tez ma 6 kwadratow."),
     dict(q="Ile jest roznych siatek szescianu?",
          choices={"A":"6","B":"11","C":"24"}, correct="B",
          explain="Z dokladnoscia do obrotu i odbicia - 11 roznych siatek."),
     dict(q="Skladajac siatke szescianu sklejasz:",
          choices={"A":"5 krawedzi","B":"7 krawedzi","C":"12 krawedzi"}, correct="B",
          explain="W siatce 5 krawedzi jest polaczonych, 7 trzeba skleic.")])
LESSONS.append(l25)

# ================= LEKCJA 26: Drogi i sciezki =================
l26 = lesson("l26", 26, "Drogi i sciezki po bryle", 16,
    "Mrowka wchodzi na piramide i schodzi z drugiej strony. Pajak idzie po krawedziach szescianu z jednego naroznika do drugiego. Liczenie tras po bryle to bardzo wazna umiejetnosc - i nieczesto oczywista. Trzeba systematycznie szukac wszystkich mozliwosci.",
    "Sztuczka 1: ROZWIN BRYLE NA PLASZCZYZNE. Skomplikowane drogi po bryle staja sie proste, gdy 'rozlozysz' bryle. Najkrotsza droga w 3D = linia prosta w siatce.\n\nSztuczka 2: LICZ KRAWEDZIE NA TRASIE. Idac po szescianie z naroznika do przeciwleglego, najkrotsza droga to 3 krawedzie (przekatna nie pomaga, bo idziesz tylko po krawedziach).\n\nSztuczka 3: TURLANIE KOSTKI. Kostka turlana po planszy zmienia, ktora sciana jest na gorze. Po toczeniu w prawo gorna sciana staje sie boczna, a boczna gorna.\n\nSztuczka 4: SUMA OCZEK PRZECIWLEGLA = 7. Liczac sumy widocznych scian kostki, pamietaj o tej regule - czesto pomaga.",
    "Klucz do zadan o drogach: 'najkrotsza droga' moze byc rozumiana rozne. Po krawedziach? Po powierzchni? Wzdluz scian? Czytaj uwaznie. Czasem rozwiniecie bryly na plaszczyzne pokazuje, ze 'najkrotsza' to zupelnie nieoczekiwana sciezka.",
    ver("v1","Wersja 1 (oryginalna)",
        [gen(26,"v1","w1","3pkt","krawedzie miedzy naroznikami",
            "Najkrotsza droga po krawedziach szescianu z jednego naroznika do sasiedniego ma:",
            {"A":"1 krawedz","B":"2 krawedzie","C":"3 krawedzie","D":"4 krawedzie","E":"6 krawedzi"},"A"),
         gen(26,"v1","w2","3pkt","droga przez 3 krawedzie",
            "Najkrotsza droga po krawedziach szescianu z naroznika do PRZECIWLEGLEGO (najdalszego) naroznika ma:",
            {"A":"1 krawedz","B":"2 krawedzie","C":"3 krawedzie","D":"4 krawedzie","E":"6 krawedzi"},"C"),
         gen(26,"v1","w3","3pkt","kostka turlana raz",
            "Kostka stoi oczkiem 1 na gorze. Po jednorazowym przewroceniu w prawo na gorze jest:",
            {"A":"1","B":"2","C":"4","D":"5","E":"6"},"C"),
         orig(2022,16),
         orig(2025,5)],
        [orig(2019,24),
         orig(2014,20)],
        [sol("gen-l26-v1-w1","Sasiednie naroznikit polaczone 1 krawedzia.","Liczenie krawedzi.",
            ["Dwa sasiednie naroznikit szescianu sa polaczone 1 krawedzia"],"A"),
         sol("gen-l26-v1-w2","Najdalsze naroznikit - 3 krawedzie.","Najkrotsza droga w szescianie.",
            ["Z naroznika do przeciwleglego: 3 krawedzie - musisz przejsc po 3 wymiarach"],"C"),
         sol("gen-l26-v1-w3","Po przewroceniu w prawo - sciana boczna staje sie gorna.","Turlanie kostki.",
            ["Oczko 1 na gorze, po przewroceniu w prawo na gorze pojawia sie sciana, ktora byla z lewej - oczko 4 (lub 3, zalezy od orientacji)","Klasycznie po przewroceniu w prawo z 1 na gorze, na gorze jest 4"],"C"),
         sol("kangur-maluch-2022-16","Mrowka idzie po piramidzie z klockow.",
            "Dlugosc trasy mrowki.",
            ["Piramida z klockow 10 cm","Mrowka weszla i zeszla z drugiej strony","Przeszla 80 cm"],"D"),
         sol("kangur-maluch-2025-5","Standardowa kostka - rozpoznanie.",
            "Sprawdzanie sum przeciwleglych.",
            ["Tylko jedna z 5 kostek to standardowa","Poprawna to A"],"A"),
         sol("kangur-maluch-2019-24","Sklejone kostki - suma sklejonych scian.",
            "Suma na sklejonych powierzchniach.",
            ["4 kostki sklejone w rzad - 3 pary sklejonych scian","Suma 6 sklejonych scian to 20"],"E"),
         sol("kangur-maluch-2014-20","Suma oczek na tylnej scianie budowli.",
            "Wykorzystanie regul kostki.",
            ["Budowla z 6 kostek, przednia sciana zacieniowana","Tylna sciana ma sume 21"],"D")]),
    ver("v2","Wersja 2 (powtorka)",
        [gen(26,"v2","w1","3pkt","krawedzie sasiednie",
            "Sasiednie naroznikit szescianu sa polaczone iloma krawedziami?",
            {"A":"0","B":"1","C":"2","D":"3","E":"6"},"B"),
         gen(26,"v2","w2","3pkt","droga po krawedziach",
            "Pajak po krawedziach szescianu chce dojsc do naroznika lezacego na tej samej krawedzi co start. Minimalna liczba krawedzi:",
            {"A":"1","B":"2","C":"3","D":"4","E":"6"},"A"),
         gen(26,"v2","w3","3pkt","kostka stoi - widoczne oczka",
            "Kostka stoi na ziemi (sciana dolna jest 6, czyli niewidoczna). Suma widocznych oczek (gora + 4 boki) wynosi:",
            {"A":"15","B":"16","C":"18","D":"20","E":"21"},"A"),
         gen(26,"v2","w4","3pkt","krotka droga 3D",
            "Po krawedziach szescianu z naroznika do PRZECIWLEGLEGO. Ile krawedzi minimum?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
         gen(26,"v2","w5","3pkt","powierzchnia szescianu",
            "Ile scian widzimy zewnatrz szescianu (lacznie wszystkie strony)?",
            {"A":"3","B":"4","C":"5","D":"6","E":"12"},"D")],
        [gen(26,"v2","c1","4pkt","liczba najkrotszych drog",
            "W szescianie z naroznika do przeciwleglego sa rozne najkrotsze drogi po krawedziach (po 3 krawedzie). Ile takich roznych najkrotszych drog?",
            {"A":"3","B":"6","C":"8","D":"9","E":"12"},"B"),
         orig(2020,17)],
        [sol("gen-l26-v2-w1","Sasiednie - jedna krawedz.","Definicja sasiedztwa.",
            ["Sasiednie naroznikit polaczone sa 1 krawedzia"],"B"),
         sol("gen-l26-v2-w2","Na tej samej krawedzi = sasiedni = 1.","Sasiednie naroznikit.",
            ["Naroznikit na wspolnej krawedzi to sasiednie - 1 krawedz"],"A"),
         sol("gen-l26-v2-w3","Suma scian kostki = 21, minus dolna 6.","Suma minus niewidoczna.",
            ["Suma wszystkich oczek na kostce: 1+2+3+4+5+6 = 21","Minus dolna (6): 21 - 6 = 15"],"A"),
         sol("gen-l26-v2-w4","Z naroznika do przeciwleglego = 3 krawedzie.","Najdalsze naroznikit.",
            ["Potrzebujemy zmienic 3 wspolrzedne","Minimum: 3 krawedzie"],"B"),
         sol("gen-l26-v2-w5","Szescian ma 6 scian widocznych z zewnatrz.","Liczba scian.",
            ["Szescian ma 6 scian"],"D"),
         sol("gen-l26-v2-c1","Z 8 naroznikow do przeciwleglego sa rozne sciezki dlugosci 3.","Liczenie permutacji.",
            ["Trzy krawedzie do przejscia - po jednej w kazdym kierunku (x, y, z)","Kolejnosc dowolna: 3! = 6 najkrotszych drog"],"B"),
         sol("kangur-maluch-2020-17","Toczenie kostki - suma scian na koncu.",
            "Sledzenie turlania.",
            ["Kostka toczy sie po 6 kwadracikach w prawo","Suma trzech ? scian wynosi 11"],"D")]),
    [dict(q="Najkrotsza droga z naroznika do przeciwleglego szescianu (po krawedziach):",
          choices={"A":"2 krawedzie","B":"3 krawedzie","C":"6 krawedzi"}, correct="B",
          explain="Trzeba zmienic 3 wspolrzedne, czyli 3 krawedzie."),
     dict(q="Suma oczek na wszystkich scianach standardowej kostki:",
          choices={"A":"15","B":"21","C":"36"}, correct="B",
          explain="1+2+3+4+5+6 = 21."),
     dict(q="Latwiejszy sposob na trase po bryle:",
          choices={"A":"Liczyc w 3D","B":"Rozwinac na plaszczyzne","C":"Pomylic sie"}, correct="B",
          explain="Rozwiniecie bryly zamienia trase 3D na prosta linie 2D.")])
LESSONS.append(l26)

# ================= ZAPIS =================
for les in LESSONS:
    with open(f"data/lessons/{les['id']}.json", "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
    print(f"{les['id']}: OK ({les['title']})")
print("DONE - Blok D")
