"""Generuje Blok B - lekcje 9-13 (Wzory, ciagi, regularnosci). v1 z mixem oryginalow."""
import json

def load_original(year, number):
    with open(f"data/parsed/{year}.json", encoding="utf-8") as f:
        d = json.load(f)
    for p in d["problems"]:
        if p["number"] == number:
            return p
    raise ValueError(f"No problem {year}#{number}")

def gen(sfx, lesson, diff, topic, subtopic, statement, choices, correct):
    return dict(id=f"gen-l{lesson:02d}-{sfx}", source=f"generated-l{lesson:02d}-{sfx}",
                year=None, number=None, difficulty=diff, topic=topic, subtopic=subtopic,
                statement=statement, hasImage=False, imageNote=None, choices=choices, correct=correct)

def sol(pid, obs, strat, steps, ans, alt=None):
    return dict(problemId=pid, observation=obs, strategy=strat, steps=steps, answer=ans, alternative=alt)

def lesson(lid, number, title, topic, minutes, intro, tool, trick, warmup, challenge, solutions, quiz):
    return dict(id=lid, number=number, block="Wzory, ciagi, regularnosci", blockCode="B",
                title=title, topic=topic, estimatedMinutes=minutes,
                theory=dict(intro=intro, tool=tool, trick=trick),
                versions=[dict(versionId="v1", label="Wersja 1 (oryginalna)",
                               warmup=warmup, challenge=challenge, solutions=solutions)],
                quiz=quiz)

# ============= LEKCJA 9: Ciagi liczbowe =============
l09 = lesson("l09", 9, "Ciagi liczbowe - co dalej?", "wzory_i_ciagi", 14,
    "Skaczesz po schodach co dwa stopnie: 2, 4, 6, 8... Jaki bedzie nastepny? Latwo - 10. To ciag liczbowy. Kazdy ciag ma swoja regule, a Twoim zadaniem jest ja odkryc i przewidziec, co bedzie dalej.",
    "Sztuczka 1: ZNAJDZ ROZNICE. Odejmij sasiednie liczby. W ciagu 3, 7, 11, 15 roznica to zawsze 4. Nastepna liczba: 15 + 4 = 19.\n\nSztuczka 2: SPRAWDZ CZY MNOZYSZ. Jezeli roznice rosna, moze zamiast dodawac - mnozysz. 1, 2, 4, 8, 16 - tu kazda liczba to podwojona poprzednia.\n\nSztuczka 3: ROZNICE MOGA ROSNAC. W ciagu 1, 3, 6, 10 roznice to 2, 3, 4 - rosna o 1. Nastepna roznica to 5, czyli liczba 10 + 5 = 15.\n\nSztuczka 4: SUMA DWOCH POPRZEDNICH. W ciagu 1, 1, 2, 3, 5, 8 kazda liczba to suma dwoch przed nia. To slynny ciag Fibonacciego.",
    "Kangur lubi ciagi, gdzie regula nie jest oczywista. Zawsze najpierw policz ROZNICE. Jezeli sa stale - dodajesz. Jezeli rosna - albo mnozysz, albo roznice tworza wlasny ciag. Jezeli liczby szybko rosna - to prawie na pewno mnozenie.",
    warmup=[
        gen("w1",9,"3pkt","wzory_i_ciagi","ciag arytmetyczny - stala roznica",
            "Jaka liczba powinna byc nastepna w ciagu: 2, 4, 6, 8, ?",
            {"A":"9","B":"10","C":"12","D":"14","E":"16"},"B"),
        gen("w2",9,"3pkt","wzory_i_ciagi","ciag co 5",
            "Jaka liczba jest nastepna: 5, 10, 15, 20, ?",
            {"A":"22","B":"24","C":"25","D":"30","E":"35"},"C"),
        gen("w3",9,"3pkt","wzory_i_ciagi","ciag podwajany",
            "W ciagu 1, 2, 4, 8, 16, ? kazda liczba to podwojona poprzednia. Jaka liczba jest nastepna?",
            {"A":"18","B":"24","C":"30","D":"32","E":"64"},"D"),
        gen("w4",9,"3pkt","wzory_i_ciagi","ciag malejacy",
            "Jaka liczba jest nastepna w ciagu malejacym: 30, 26, 22, 18, ?",
            {"A":"16","B":"15","C":"14","D":"12","E":"10"},"C"),
        gen("w5",9,"3pkt","wzory_i_ciagi","ciag z rosnacymi roznicami",
            "W ciagu 1, 3, 6, 10, ? roznice rosna o 1. Jaka liczba jest nastepna?",
            {"A":"13","B":"14","C":"15","D":"16","E":"20"},"C"),
    ],
    challenge=[
        gen("c1",9,"4pkt","wzory_i_ciagi","regula mnozenie plus jeden",
            "W ciagu 2, 5, 11, 23, ? kazda liczba to poprzednia razy 2 plus 1. Jaka jest nastepna?",
            {"A":"35","B":"42","C":"46","D":"47","E":"48"},"D"),
        gen("c2",9,"5pkt","wzory_i_ciagi","ciag Fibonacciego",
            "W ciagu 1, 1, 2, 3, 5, 8, ? kazda liczba to suma dwoch poprzednich. Jaka jest nastepna?",
            {"A":"11","B":"12","C":"13","D":"14","E":"21"},"C"),
    ],
    solutions=[
        sol("gen-l09-w1","Roznica stala - liczymy ja.","Znajdz roznice.",
            ["Roznica: 4-2=2, 6-4=2, 8-6=2","Nastepna: 8 + 2 = 10"],"B"),
        sol("gen-l09-w2","Ciag rosnie co 5.","Znajdz roznice.",
            ["Roznica zawsze 5","Nastepna: 20 + 5 = 25"],"C"),
        sol("gen-l09-w3","Liczby szybko rosna - to mnozenie.","Sprawdz czy mnozysz.",
            ["Kazda liczba to poprzednia razy 2","16 razy 2 = 32"],"D"),
        sol("gen-l09-w4","Ciag maleje - roznica ujemna.","Znajdz roznice.",
            ["Roznica: 26-30=-4, czyli kazda liczba o 4 mniejsza","18 - 4 = 14"],"C"),
        sol("gen-l09-w5","Roznice rosna: 2, 3, 4.","Roznice tworza wlasny ciag.",
            ["Roznice: 3-1=2, 6-3=3, 10-6=4","Nastepna roznica: 5","10 + 5 = 15"],"C",
            "To liczby trojkatne: 1, 3, 6, 10, 15."),
        sol("gen-l09-c1","Roznice rosna szybko - sprawdz regule mnozenia.","Testuj hipoteze razy 2 plus 1.",
            ["2 razy 2 + 1 = 5 OK","5 razy 2 + 1 = 11 OK","11 razy 2 + 1 = 23 OK","23 razy 2 + 1 = 47"],"D"),
        sol("gen-l09-c2","Kazda liczba to suma dwoch przed nia.","Reguly Fibonacciego.",
            ["8 to 3 + 5","Nastepna: 5 + 8 = 13"],"C"),
    ],
    quiz=[
        dict(q="Co robisz NAJPIERW, gdy widzisz ciag liczb?",
             choices={"A":"Liczysz roznice sasiednich liczb","B":"Zgadujesz","C":"Mnozysz wszystko"},
             correct="A", explain="Roznice od razu pokazuja, czy ciag rosnie stale czy nie."),
        dict(q="Ciag 3, 9, 27, 81 - jaka regula?",
             choices={"A":"Dodaj 6","B":"Razy 3","C":"Dodaj 18"}, correct="B",
             explain="Kazda liczba to poprzednia razy 3. Liczby szybko rosna = mnozenie."),
        dict(q="W ciagu 2, 4, 7, 11 roznice to:",
             choices={"A":"Stale (2)","B":"Rosna (2, 3, 4)","C":"Maleja"}, correct="B",
             explain="Roznice 2, 3, 4 - rosna o 1. Nastepna liczba: 11+5=16."),
    ])

# ============= LEKCJA 10: Wzory w obrazkach =============
l10 = lesson("l10", 10, "Wzory w obrazkach", "wzory_i_ciagi", 15,
    "Z patyczkow ukladasz trojkaty. Jeden trojkat to 3 patyczki. Drugi doklejony obok - tylko 2 dodatkowe. Trzeci - znowu 2. Obrazki tez maja swoje reguly, tylko trzeba je przetlumaczyc na liczby.",
    "Sztuczka 1: POLICZ PIERWSZE PRZYPADKI. Narysuj lub policz 1, 2, 3 elementy wzoru. Zapisz liczby. Teraz widzisz ciag - i mozesz uzyc regul z poprzedniej lekcji.\n\nSztuczka 2: ZNAJDZ PRZYROST. O ile rosnie wzor przy kazdym kroku? Trojkaty z patyczkow: 3, 5, 7, 9 - przyrost to zawsze 2.\n\nSztuczka 3: ODDZIEL POCZATEK OD PRZYROSTU. Pierwszy element jest 'specjalny', kazdy nastepny dodaje stala porcje. Trojkaty: pierwszy ma 3, kazdy kolejny +2. Dla 10 trojkatow: 3 + 2 razy 9 = 21.\n\nSztuczka 4: RAMKI I BRZEGI. Liczba elementow na brzegu kwadratu N na N to 4 razy N minus 4 (rogi liczone raz). Dla 10 na 10: 4 razy 10 - 4 = 36.",
    "Kangur uwielbia wzory, gdzie liczenie wszystkiego po kolei zajeloby wieki. Sekret: policz tylko 3 pierwsze przypadki, znajdz przyrost i uogolnij. Nigdy nie ryzykuj liczenia 100 elementow po jednym - znajdz regule.",
    warmup=[
        gen("w1",10,"3pkt","wzory_i_ciagi","patyczki - trojkaty",
            "Z patyczkow uklada sie trojkaty w rzedzie: 1 trojkat to 3 patyczki, 2 trojkaty to 5, 3 trojkaty to 7. Ile patyczkow na 5 trojkatow?",
            {"A":"9","B":"10","C":"11","D":"13","E":"15"},"C"),
        gen("w2",10,"3pkt","wzory_i_ciagi","zapalki - kwadraty",
            "Z zapalek uklada sie kwadraty w rzedzie: 1 kwadrat to 4 zapalki, 2 to 7, 3 to 10. Ile zapalek na 6 kwadratow?",
            {"A":"16","B":"18","C":"19","D":"21","E":"24"},"C"),
        gen("w3",10,"3pkt","wzory_i_ciagi","wzor kropek w rzedach",
            "Wzor z kropek: rzad 1 ma 1 kropke, rzad 2 ma 3 kropki, rzad 3 ma 5. Ile kropek ma rzad 6?",
            {"A":"9","B":"11","C":"12","D":"13","E":"6"},"B"),
        load_original(2012,3),
        load_original(2019,6),
    ],
    challenge=[
        gen("c1",10,"4pkt","wzory_i_ciagi","suma poziomow choinki",
            "Choinka z klockow: gorny poziom ma 1 klocek, drugi 3, trzeci 5, czwarty 7. Ile klockow ma cala choinka z 5 poziomami?",
            {"A":"15","B":"20","C":"25","D":"30","E":"35"},"C"),
        gen("c2",10,"5pkt","wzory_i_ciagi","brzeg ramki kwadratowej",
            "Ramka kwadratowa z plytek: ramka 3x3 ma 8 plytek na brzegu, 4x4 ma 12, 5x5 ma 16. Ile plytek na brzegu ramki 10x10?",
            {"A":"32","B":"36","C":"40","D":"44","E":"48"},"B"),
    ],
    solutions=[
        sol("gen-l10-w1","Pierwszy trojkat 3, kazdy kolejny +2.","Oddziel poczatek od przyrostu.",
            ["1 trojkat: 3 patyczki","Kazdy kolejny dodaje 2","5 trojkatow: 3 + 2+2+2+2 = 3 + 8 = 11"],"C"),
        sol("gen-l10-w2","Pierwszy kwadrat 4, kazdy kolejny +3.","Oddziel poczatek od przyrostu.",
            ["1 kwadrat: 4 zapalki","Kazdy kolejny dodaje 3","6 kwadratow: 4 + 3 razy 5 = 4 + 15 = 19"],"C"),
        sol("gen-l10-w3","Liczby kropek: 1, 3, 5, 7... rosna o 2.","Znajdz przyrost.",
            ["Rzad 1: 1, rzad 2: 3, rzad 3: 5","Kazdy rzad ma 2 wiecej","Rzad 6: 1, 3, 5, 7, 9, 11 - czyli 11"],"B"),
        sol("kangur-maluch-2012-3","Sasiednie reczniki dziela klamerke.","Znajdz przyrost na recznik.",
            ["1 recznik: 2 klamerki","Kazdy kolejny dodaje 1 klamerke (dzieli z sasiadem)","12 recznikow: 2 + 11 = 13"],"B",
            "Wzor: liczba klamerek = liczba recznikow + 1."),
        sol("kangur-maluch-2019-6","Pierwsze zdjecie 4 pinezki, kazde kolejne +2.","Oddziel poczatek od przyrostu.",
            ["3 zdjecia = 8 pinezek, sprawdza sie: 4 + 2 + 2 = 8","7 zdjec: 4 + 2 razy 6 = 4 + 12 = 16"],"B"),
        sol("gen-l10-c1","Poziomy maja 1, 3, 5, 7, 9 klockow. Sumujemy.","Suma ciagu.",
            ["Poziomy: 1, 3, 5, 7, 9","Suma: 1+3+5+7+9 = 25"],"C",
            "Suma pierwszych n liczb nieparzystych to n razy n: 5 razy 5 = 25."),
        sol("gen-l10-c2","Liczba plytek na brzegu: 8, 12, 16 - rosnie o 4.","Wzor brzegu.",
            ["Ramka N na N: 4 razy N - 4 (rogi nie liczone podwojnie)","Sprawdz 3x3: 4 razy 3 - 4 = 8 OK","10x10: 4 razy 10 - 4 = 36"],"B"),
    ],
    quiz=[
        dict(q="Wzor z patyczkow rosnie o 2 na element, pierwszy ma 3. Dla 4 elementow:",
             choices={"A":"8","B":"9","C":"11"}, correct="B",
             explain="3 + 2+2+2 = 9. Pierwszy specjalny + przyrosty."),
        dict(q="Co policzyc NAJPIERW przy wzorze obrazkowym?",
             choices={"A":"Wszystkie 100 elementow","B":"3 pierwsze przypadki","C":"Tylko ostatni"},
             correct="B", explain="3 pierwsze przypadki pokazuja przyrost i regule."),
        dict(q="Brzeg kwadratu 6x6 plytek to:",
             choices={"A":"20","B":"24","C":"36"}, correct="A",
             explain="4 razy 6 - 4 = 20. Rogi liczone raz."),
    ])

# ============= LEKCJA 11: Magiczne kwadraty =============
l11 = lesson("l11", 11, "Magiczne kwadraty", "wzory_i_ciagi", 15,
    "Magiczny kwadrat to siatka liczb, w ktorej kazdy wiersz, kazda kolumna i obie przekatne daja te sama sume. Wyglada jak czary, ale to czysta logika - i da sie go rozwiazac krok po kroku.",
    "Sztuczka 1: ZNAJDZ SUME MAGICZNA. Jezeli jeden wiersz lub kolumna jest kompletny - jego suma to suma magiczna calego kwadratu. Wszystkie inne linie musza dac tyle samo.\n\nSztuczka 2: BRAKUJACA LICZBA. Gdy w wierszu sa 2 liczby z 3, brakujaca to suma magiczna minus te dwie. Wiersz z 8 i 1, suma 15: brakuje 15 - 8 - 1 = 6.\n\nSztuczka 3: SRODEK JEST SPECJALNY. W magicznym kwadracie 3x3 z liczb 1-9 srodek to zawsze 5, a suma magiczna to 15. Srodek to suma magiczna podzielona przez 3.\n\nSztuczka 4: SPRAWDZAJ SPOJNOSC. Gdy szukasz bledu, policz sume kazdego wiersza i kolumny. Linia, ktora odstaje, wskazuje pole z blednym wpisem - to pole nalezace do dwoch odstajacych linii.",
    "W zadaniach 'znajdz blad' nie zgaduj. Policz sumy wszystkich wierszy i kolumn. Bledne pole lezy na przecieciu dwoch linii, ktore daja zla sume. To zawsze dziala.",
    warmup=[
        gen("w1",11,"3pkt","wzory_i_ciagi","srodek magicznego kwadratu",
            "W magicznym kwadracie 3x3 z liczb od 1 do 9 suma kazdego rzedu wynosi 15. Jaka liczba jest w samym srodku?",
            {"A":"3","B":"4","C":"5","D":"6","E":"9"},"C"),
        gen("w2",11,"3pkt","wzory_i_ciagi","brakujaca liczba w wierszu",
            "W magicznym kwadracie suma rzedu to 15. W jednym rzedzie sa juz liczby 8 i 1. Jaka jest trzecia liczba?",
            {"A":"4","B":"5","C":"6","D":"7","E":"8"},"C"),
        gen("w3",11,"3pkt","wzory_i_ciagi","brakujaca liczba przy innej sumie",
            "W magicznym kwadracie suma kolumny to 18. W kolumnie sa juz 7 i 5. Jaka jest trzecia liczba?",
            {"A":"5","B":"6","C":"7","D":"8","E":"9"},"B"),
        gen("w4",11,"3pkt","wzory_i_ciagi","suma przekatnej",
            "W magicznym kwadracie na przekatnej sa liczby 2, 5 i 8. Ile wynosi suma magiczna tego kwadratu?",
            {"A":"12","B":"13","C":"14","D":"15","E":"16"},"D"),
        load_original(2022,5),
    ],
    challenge=[
        load_original(2012,12),
        gen("c2",11,"5pkt","wzory_i_ciagi","brakujaca liczba przy duzej sumie",
            "W magicznym kwadracie 3x3 wszystkie sumy wynosza 24. W jednym wierszu sa juz liczby 11 i 7. Jaka jest trzecia liczba w tym wierszu?",
            {"A":"5","B":"6","C":"7","D":"8","E":"9"},"B"),
    ],
    solutions=[
        sol("gen-l11-w1","Magiczny kwadrat 3x3 z 1-9 - srodek to zawsze suma magiczna : 3.","Regula srodka.",
            ["Suma magiczna 15","Srodek = 15 : 3 = 5"],"C",
            "Srodek nalezy do 4 linii (wiersz, kolumna, 2 przekatne) - dlatego jest specjalny."),
        sol("gen-l11-w2","Brakujaca = suma magiczna minus dwie znane.","Brakujaca liczba.",
            ["15 - 8 - 1 = 6"],"C"),
        sol("gen-l11-w3","Brakujaca = suma minus dwie znane.","Brakujaca liczba.",
            ["18 - 7 - 5 = 6"],"B"),
        sol("gen-l11-w4","Przekatna tez musi dac sume magiczna.","Suma linii.",
            ["2 + 5 + 8 = 15","To wlasnie suma magiczna"],"D"),
        sol("kangur-maluch-2022-5","Policz sumy wierszy i kolumn, znajdz odstajaca.","Sprawdzanie spojnosci.",
            ["Wiersze: 9+1+5=15, 3+7+6=16, 4+7+4=15","Kolumny: 9+3+4=16, 1+7+7=15, 5+6+4=15","Odstaja: wiersz 2 i kolumna 1 (oba 16)","Wspolne pole: liczba 3 w lewym polu wiersza 2","Zamiana 3 na 2 naprawia obie linie"],"B"),
        sol("kangur-maluch-2012-12","Wyniki dzialan wpisane do siatki, potem uzupelnianie jak sudoku.",
            "Najpierw policz dzialania, potem uzupelnij sudoku 4x4.",
            ["Dzialania daja liczby: 1*1=1, 1*3=3, 6-3=3, 6-5=1, 4-1=3, 1+3=4, 9-7=2","W siatce kazda liczba 1-4 raz w wierszu i kolumnie","Po uzupelnieniu w szarym polu wychodzi 3"],"C"),
        sol("gen-l11-c2","Brakujaca = suma magiczna minus dwie znane.","Brakujaca liczba.",
            ["24 - 11 - 7 = 6"],"B"),
    ],
    quiz=[
        dict(q="Jak znalezc sume magiczna kwadratu?",
             choices={"A":"Z kompletnego wiersza lub kolumny","B":"Zgadnac","C":"Pomnozyc rogi"},
             correct="A", explain="Kompletna linia od razu pokazuje sume, ktora musza miec wszystkie."),
        dict(q="Suma magiczna 21, w wierszu sa 9 i 6. Trzecia liczba:",
             choices={"A":"5","B":"6","C":"7"}, correct="B",
             explain="21 - 9 - 6 = 6."),
        dict(q="Szukasz bledu w kwadracie. Bledne pole lezy:",
             choices={"A":"Zawsze w rogu","B":"Na przecieciu dwoch odstajacych linii","C":"W srodku"},
             correct="B", explain="Pole nalezace do dwoch linii o zlej sumie to wlasnie blad."),
    ])

# ============= LEKCJA 12: Rozkladanie na sume lub iloczyn =============
l12 = lesson("l12", 12, "Rozkladanie na sume lub iloczyn", "wzory_i_ciagi", 15,
    "Masz 6 zlotych w monetach 2 zl i 1 zl. Na ile sposobow mozesz je ulozyc? To pytanie o rozklad liczby. Liczby mozna rozkladac na sumy i na iloczyny - a Kangur czesto pyta 'na ile sposobow'.",
    "Sztuczka 1: WYPISUJ SYSTEMATYCZNIE. Zeby nie zgubic zadnego sposobu, idz po kolei. Liczba 5 jako suma dwoch dodatnich: 1+4, 2+3. Zaczynaj od najmniejszej i zwiekszaj.\n\nSztuczka 2: ILOCZYN - SZUKAJ PAR DZIELNIKOW. Liczba 12 jako iloczyn: 1x12, 2x6, 3x4. Sprawdzaj po kolei 1, 2, 3... az dojdziesz do srodka.\n\nSztuczka 3: KOLEJNOSC CZASEM NIE LICZY SIE. Zwroc uwage, czy 1+4 i 4+1 to ten sam sposob czy dwa rozne. W zadaniach Kangurka zwykle to ten sam sposob.\n\nSztuczka 4: DZIELNIKI. Dzielnik liczby to liczba, przez ktora dzieli sie ona bez reszty. Liczba 12 ma dzielniki: 1, 2, 3, 4, 6, 12 - czyli 6 dzielnikow.",
    "Klucz do zadan 'na ile sposobow' to SYSTEMATYCZNOSC. Nie skacz losowo - idz po kolei od najmniejszej liczby. Wtedy nie zgubisz zadnego sposobu i nie policzysz dwa razy tego samego.",
    warmup=[
        gen("w1",12,"3pkt","wzory_i_ciagi","rozklad na sume dwoch liczb",
            "Na ile sposobow mozna zapisac liczbe 5 jako sume dwoch liczb wiekszych od 0? (kolejnosc nie ma znaczenia)",
            {"A":"1","B":"2","C":"3","D":"4","E":"5"},"B"),
        gen("w2",12,"3pkt","wzory_i_ciagi","rozklad na iloczyn",
            "Na ile sposobow mozna zapisac liczbe 12 jako iloczyn dwoch liczb? (np. 2 razy 6)",
            {"A":"2","B":"3","C":"4","D":"6","E":"12"},"B"),
        gen("w3",12,"3pkt","wzory_i_ciagi","rozmiana monet",
            "Na ile sposobow mozna ulozyc 6 zlotych z monet 2 zl i 1 zl?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"C"),
        gen("w4",12,"3pkt","wzory_i_ciagi","suma trzech jednakowych",
            "Liczba 9 to suma trzech jednakowych liczb. Jaka to liczba?",
            {"A":"2","B":"3","C":"4","D":"6","E":"9"},"B"),
        gen("w5",12,"3pkt","wzory_i_ciagi","rozklad na dwie rozne liczby",
            "Na ile sposobow zapisac 7 jako sume dwoch ROZNYCH liczb wiekszych od 0?",
            {"A":"2","B":"3","C":"4","D":"5","E":"6"},"B"),
    ],
    challenge=[
        gen("c1",12,"4pkt","wzory_i_ciagi","suma kolejnych liczb",
            "Liczbe 15 mozna zapisac jako sume kolejnych liczb naturalnych, np. 7+8 lub 4+5+6. Na ile sposobow da sie to zrobic (nie liczac samej liczby 15)?",
            {"A":"1","B":"2","C":"3","D":"4","E":"5"},"C"),
        gen("c2",12,"5pkt","wzory_i_ciagi","liczba dzielnikow",
            "Ile dzielnikow ma liczba 24 (liczb, przez ktore dzieli sie bez reszty)?",
            {"A":"6","B":"7","C":"8","D":"9","E":"12"},"C"),
    ],
    solutions=[
        sol("gen-l12-w1","Wypisuje sumy systematycznie od najmniejszej.","Systematyczne wypisywanie.",
            ["1 + 4 = 5","2 + 3 = 5","3 + 2 to to samo co 2 + 3","Czyli 2 sposoby"],"B"),
        sol("gen-l12-w2","Szukam par dzielnikow 12.","Pary dzielnikow.",
            ["1 razy 12","2 razy 6","3 razy 4","Czyli 3 sposoby"],"B"),
        sol("gen-l12-w3","Licze ile monet 2 zl: 0, 1, 2 lub 3.","Systematyczne wypisywanie.",
            ["0 monet 2zl + 6 monet 1zl","1 moneta 2zl + 4 monety 1zl","2 monety 2zl + 2 monety 1zl","3 monety 2zl + 0 monet 1zl","Czyli 4 sposoby"],"C"),
        sol("gen-l12-w4","Trzy jednakowe liczby daja 9.","Dzielenie.",
            ["9 : 3 = 3","3 + 3 + 3 = 9"],"B"),
        sol("gen-l12-w5","Liczby musza byc rozne - wypisuje pary.","Systematyczne wypisywanie.",
            ["1 + 6 = 7","2 + 5 = 7","3 + 4 = 7","Czyli 3 sposoby (wszystkie pary rozne)"],"B"),
        sol("gen-l12-c1","Szukam ciagow kolejnych liczb sumujacych sie do 15.","Systematyczne sprawdzanie.",
            ["Dwie liczby: 7 + 8 = 15","Trzy liczby: 4 + 5 + 6 = 15","Piec liczb: 1 + 2 + 3 + 4 + 5 = 15","Czyli 3 sposoby"],"C"),
        sol("gen-l12-c2","Wypisuje dzielniki parami.","Pary dzielnikow.",
            ["1 i 24","2 i 12","3 i 8","4 i 6","Razem: 1,2,3,4,6,8,12,24 - 8 dzielnikow"],"C"),
    ],
    quiz=[
        dict(q="Jak nie zgubic zadnego sposobu przy 'na ile sposobow'?",
             choices={"A":"Wypisywac systematycznie od najmniejszej","B":"Zgadywac","C":"Liczyc szybko"},
             correct="A", explain="Systematyczne wypisywanie po kolei gwarantuje komplet."),
        dict(q="Liczba 10 jako iloczyn dwoch liczb - ile par?",
             choices={"A":"1","B":"2","C":"3"}, correct="B",
             explain="1x10 i 2x5. Dwie pary."),
        dict(q="Dzielnik liczby to:",
             choices={"A":"Liczba dzielaca ja bez reszty","B":"Zawsze liczba parzysta","C":"Tylko 1"},
             correct="A", explain="Dzielnik dzieli liczbe bez reszty - np. 3 jest dzielnikiem 12."),
    ])

# ============= LEKCJA 13: Znajdz regule =============
l13 = lesson("l13", 13, "Znajdz regule i przewidz nastepny krok", "wzory_i_ciagi", 15,
    "Maszyna dostaje liczbe i wypluwa inna: 2 zamienia w 5, 3 w 7, 4 w 9. Jaka regula? Kazda liczba razy 2 plus 1. Gdy zlapiesz regule - przewidzisz kazdy nastepny krok. To esencja myslenia matematycznego.",
    "Sztuczka 1: PORownaj WEJSCIE Z WYJSCIEM. Gdy 2 daje 5, a 3 daje 7 - sprawdz: czy mnozysz? czy dodajesz? 2 razy 2 + 1 = 5, 3 razy 2 + 1 = 7. Regula: razy 2 plus 1.\n\nSztuczka 2: SPRAWDZ HIPOTEZE NA WSZYSTKICH PRZYKLADACH. Znalazles regule? Sprawdz ja na KAZDYM podanym przykladzie. Jezeli pasuje wszedzie - jest dobra.\n\nSztuczka 3: WZORY CYKLICZNE. Jezeli obrazki lub kolory sie powtarzaja (kolo, kwadrat, trojkat, kolo, kwadrat...), uzyj reszty z dzielenia. 10. element: 10 podzielone przez 3 daje reszte 1 - czyli pierwszy w cyklu.\n\nSztuczka 4: KWADRATY LICZB. Ciag 1, 4, 9, 16, 25 to liczby pomnozone przez siebie: 1x1, 2x2, 3x3... Rozpoznasz go, gdy roznice rosna o 2.",
    "Najwazniejsze: gdy znajdziesz regule, NIE ufaj jej od razu. Sprawdz ja na wszystkich podanych przykladach. Czesto pierwsza hipoteza pasuje do dwoch przypadkow, ale lamie sie na trzecim - wtedy szukaj dalej.",
    warmup=[
        gen("w1",13,"3pkt","wzory_i_ciagi","regula maszyny - razy 2 plus 1",
            "Maszyna: 2 zamienia w 5, 3 w 7, 4 w 9. Jaka liczbe da dla 5?",
            {"A":"10","B":"11","C":"12","D":"13","E":"9"},"B"),
        gen("w2",13,"3pkt","wzory_i_ciagi","regula - kwadrat liczby",
            "Maszyna: 1 daje 1, 2 daje 4, 3 daje 9, 4 daje 16. Jaka liczbe da dla 5?",
            {"A":"20","B":"25","C":"30","D":"24","E":"36"},"B"),
        gen("w3",13,"3pkt","wzory_i_ciagi","wzor cykliczny",
            "Figury powtarzaja sie: kolo, kwadrat, trojkat, kolo, kwadrat, trojkat... Jaka figura jest dziesiata w kolejnosci?",
            {"A":"kolo","B":"kwadrat","C":"trojkat","D":"gwiazda","E":"serce"},"A"),
        gen("w4",13,"3pkt","wzory_i_ciagi","regula odejmowania",
            "Maszyna: 10 daje 8, 8 daje 6, 6 daje 4. Jaka liczbe da dla 4?",
            {"A":"0","B":"1","C":"2","D":"3","E":"6"},"C"),
        load_original(2025,1),
    ],
    challenge=[
        gen("c1",13,"4pkt","wzory_i_ciagi","ciag kwadratow liczb",
            "W ciagu 1, 4, 9, 16, 25, ... kazda liczba to kolejna liczba pomnozona przez sama siebie. Jaka liczba jest na siodmym miejscu?",
            {"A":"36","B":"42","C":"49","D":"56","E":"64"},"C"),
        gen("c2",13,"5pkt","wzory_i_ciagi","ciag z rosnacymi roznicami",
            "W ciagu 1, 2, 4, 7, 11, 16, ? roznice rosna: 1, 2, 3, 4, 5. Jaka liczba jest nastepna?",
            {"A":"20","B":"21","C":"22","D":"23","E":"24"},"C"),
    ],
    solutions=[
        sol("gen-l13-w1","Porownuje wejscie z wyjsciem.","Testuj hipoteze razy 2 plus 1.",
            ["2 razy 2 + 1 = 5 OK","3 razy 2 + 1 = 7 OK","4 razy 2 + 1 = 9 OK","Dla 5: 5 razy 2 + 1 = 11"],"B"),
        sol("gen-l13-w2","Kazda liczba pomnozona przez sama siebie.","Rozpoznaj kwadraty.",
            ["1x1=1, 2x2=4, 3x3=9, 4x4=16","Dla 5: 5 razy 5 = 25"],"B"),
        sol("gen-l13-w3","Cykl ma 3 figury - uzyj reszty z dzielenia.","Wzor cykliczny.",
            ["Cykl: kolo (1), kwadrat (2), trojkat (3)","10 : 3 = 3 reszta 1","Reszta 1 = pierwszy w cyklu = kolo"],"A"),
        sol("gen-l13-w4","Kazda liczba zmniejszona o 2.","Regula odejmowania.",
            ["10 - 2 = 8, 8 - 2 = 6, 6 - 2 = 4","Dla 4: 4 - 2 = 2"],"C"),
        sol("kangur-maluch-2025-1","Budowa szescianu 3x3x3 - 5 etapow, czwarty od konca.",
            "Etapy budowy to ciag rosnacy.",
            ["Szescian 3x3x3 ma 27 klockow","5 zdjec pokazuje rosnaca liczbe klockow","Czwarte zdjecie to przedostatni, prawie pelny etap"],"D"),
        sol("gen-l13-c1","Ciag kwadratow: 1x1, 2x2, 3x3...","Rozpoznaj kwadraty liczb.",
            ["1, 4, 9, 16, 25, 36, 49","Siodme miejsce: 7 razy 7 = 49"],"C"),
        sol("gen-l13-c2","Roznice rosna o 1.","Roznice tworza wlasny ciag.",
            ["Roznice: 1, 2, 3, 4, 5","Nastepna roznica: 6","16 + 6 = 22"],"C"),
    ],
    quiz=[
        dict(q="Znalazles regule ciagu. Co robisz dalej?",
             choices={"A":"Sprawdzasz ja na wszystkich przykladach","B":"Od razu odpowiadasz","C":"Zgadujesz"},
             correct="A", explain="Regula musi pasowac do KAZDEGO przykladu - inaczej szukaj dalej."),
        dict(q="Figury w cyklu 4-elementowym. Ktora jest 12. w kolejnosci?",
             choices={"A":"Pierwsza","B":"Czwarta","C":"Druga"}, correct="B",
             explain="12 : 4 = 3 reszta 0 - czyli ostatnia (czwarta) w cyklu."),
        dict(q="Ciag 1, 4, 9, 16 to:",
             choices={"A":"Kwadraty liczb","B":"Dodawanie 3","C":"Mnozenie przez 4"},
             correct="A", explain="1x1, 2x2, 3x3, 4x4 - kolejne liczby razy same siebie."),
    ])

for les in [l09, l10, l11, l12, l13]:
    with open(f"data/lessons/{les['id']}.json", "w", encoding="utf-8") as f:
        json.dump(les, f, ensure_ascii=False, indent=2)
    print(f"{les['id']}: OK")
print("DONE")
